### ISSUE TITLE
[rfe_id:609]VMIheadless [rfe_id:609]Creating a VirtualMachineInstance with headless [test_id:713]should have more memory on pod when headless

### ISSUE THREAD

**Issue by akrejcir** [kubevirt/kubevirt#3822] opened 2020-07-14 14:14 UTC
/kind bug
/triage build-officer

**What happened**:
```
/root/go/src/kubevirt.io/kubevirt/tests/vmi_headless_test.go:100
Unexpected Warning event received: testvmigwb2v4v8qwnsds8g8xfgtdfzdgk6hndb4kwb6cpx258c5m5q,f8faaecb-7ff8-4ff3-a815-fbc420da56a4: server error. command SyncVMI failed: "LibvirtError(Code=38, Domain=0, Message='Unable to open /dev/kvm: Operation not permitted')"
Expected
    <string>: Warning
not to equal
    <string>: Warning
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:410
```

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2694/pull-kubevirt-e2e-k8s-1.16/1282643157204340740

**Comment by rmohr** [comment] 2020-07-15 15:34
/assign

Failing on /dev/kvm not permitted. That's not related to the test. Will close it and create an extra issue for that if I find more reports which belong to it.

**Comment by rmohr** [comment] 2020-08-18 11:27
/close

Thanks @akrejcir, closing this as duplicate of #3872

**Closed by rmohr** 2020-08-18 11:27 UTC
Labels: kind/bug, triage/build-officer
