### ISSUE TITLE
Multiple nic interfaces support 

### ISSUE THREAD

**Issue by sheetaljoshi** [kubevirt/kubevirt#977] opened 2018-04-30 18:30 UTC
I am trying to schedule VM with multiple network interfaces allowed. Does kubevirt allow me to schedule such a workload today? if so can you please share details? VNFs are the candidates for scope of deployment.

Thanks,
Sheetal

**Comment by xsgordon** [comment] 2018-05-01 14:11
Hi @sheetaljoshi, not right now - we are working on this though in the context of the Kubernetes proposals to get multiple networks to a pod (which we can then leverage in KubeVirt).

**Comment by fabiand** [comment] 2018-05-01 22:17
Heya!

As @xsgordon said, but a few more details.

KubeVirt VMs consumes resources of a pod. Thus in order to let a VM consume multiple network interfaces, a pod needs ot be able to provide multiple.

There are two sides to this feature - a frontend (towards the guest) and backend side.

On the backend side we are discussing with upstream how multiple networks can be brought to pods. Currently there are three approaches we are looking into:

- Network CRDs
- Network Device Plugins
- NetworkServices

There is work by @phoracek demoing how Network Device Plugins could work. The other two approaches are still being looked at.

The issue is that this work could not yet be used, because we miss the KubeVirt integration, thus on the frontend side we are now working on an API draft to see how defining multiple interfaces for a VM could look. Once we have settled on something here, we can work on the glue in order to at least POC the whole flow from Network DP up to a VM with multiple nics.

Let me note that there are more details - as you probably know - to this. I.e. how interfaces are exposed to pods and VMs (netlink interface, pci device, sriov device, shared mem for userspace networking, …) - so far the mechanics are there to expose it in the on or other way.
And only the NetworkService approach seems to be the one which includes enough meta-data to allow an "optimal" binding of interfaces to VMs.

**Comment by edsealing** [comment] 2018-05-08 03:52
Not sure if this helps, but the Multus CNI currently allows for multiple NICs in pods, connected to different CNI children.
https://github.com/Intel-Corp/multus-cni

By default, it creates the first interface as "eth0" additional pod interfaces as "net0", "net1", etc.

I've used Calico, flannel, SR-IOV interfaces all within the same pod (effectively 3 interfaces connected to 3 different networks) and it seems to work and be pretty stable.

**Comment by jdandrea** [comment] 2018-05-21 17:27
@edsealing, if I'm reading the README for Multus CNI correctly, does this mean I could take that and KubeVirt and for example, use SR-IOV straight away? That's rather compelling stuffs, as is the Multi part. I like options.

**Comment by phoracek** [comment] 2018-05-22 12:26
@edsealing @jdandrea the problem is, that all Pods on a Node with configured Multus will be connected to all its networks (correct me if I am wrong). Not sure if that is what you want.

However, like Fabian mentioned, there is ongoing work on multiple-networks support in Kubernetes, where you can select networks per each Pod/VM. It should be available for testing very soon.

**Comment by edsealing** [comment] 2018-05-22 12:40
@phoracek That is incorrect. Multus creates a "network" CRD. Each network CNI that you connect to Multus gets an associated network element.

To connect a pod to multiple networks of your choice, you simply add a network annotation. Here is an example I use for testing:
```
  template:
    metadata:
      annotations:
        networks: '[  
        { "name": "calico" },
        { "name": "ovs-plugin" }
        ]'
```

@jdandrea My team and I recently open-sourced a platform that has Multus installed out-of-the box, as well as kubevirt 0.5.0: [EDCOP](https://github.com/sealingtech/EDCOP): https://github.com/sealingtech/EDCOP (still working on the project documentation)

I did some initial testing with Multus & kubevirt recently. The Pod gets two NICs as expacted (in this example, the calico network and OVS network), the VM is only attached to eth0.

**Comment by phoracek** [comment] 2018-05-22 12:52
@edsealing Did not know it's already implemented there, thanks. Draft of KubeVirt networking API was recently posted on kubevirt-dev mailing list, take a look https://groups.google.com/forum/#!topic/kubevirt-dev/Tk1bxwRsoXs. Once that is implemented, you should be able to connect VM to Pod's interfaces.

**Comment by fabiand** [comment] 2018-05-23 12:02
depends on https://github.com/kubevirt/kubevirt/issues/1067

**Comment by rmohr** [comment] 2018-05-24 07:58
@edsealing there is a proposal on the kubevirt mailing list which would heavily affect you as early adopters: https://groups.google.com/forum/#!topic/kubevirt-dev/CU_VskPIisg. Input from you or you people would be higly appreciated.

**Comment by fabiand** [comment] 2018-05-24 09:53
@edsealing in addition - considering that multus is the only broader implementation which supports the Network CRD de-facto standard, it does make sense to add support to kubevirt as well, which would then allow (ideally) the consumption sr-iov devices with vms.

The API would allow you to connect mutliple available NICs of the POD to the VMs.

For your sr-iov case - how would you connect the interface to the VM? Using passthrough or some other method?

**Comment by fabiand** [comment] 2018-09-05 08:40
This is done. The API changes were merged.

**Closed by fabiand** 2018-09-05 08:40 UTC
Labels: do-not-merge/release-note-label-needed, kind/enhancement, needs/documentation, size/XL, topic/api, topic/network
