### ISSUE TITLE
InterfaceBridge missing definition in OpenAPI

### ISSUE THREAD

**Issue by tripledes** [kubevirt/kubevirt#1181] opened 2018-06-19 11:56 UTC
Using the Python client, I hit an error about `v1.InterfaceBridge`, https://github.com/kubevirt/client-python/issues/21, looking further I found the [API definition](https://github.com/kubevirt/kubevirt/blob/master/api/openapi-spec/swagger.json#L3829) contains the type, but it's empty, therefore the python client generated references to it, but has no implementation for it.

**Comment by fabiand** [comment] 2018-06-21 12:55
@SchSeba can you take a look?

**Comment by SchSeba** [comment] 2018-06-25 12:01
I take a look at the issue. The problem is the swagger-codegen don't generate empty structs I also was not able to find any hack to tell the codegen to create the model. The problem will be fixed if we implement the delegate variable inside the bridge struct or any other configuration inside of it.

**Comment by SchSeba** [comment] 2018-07-02 09:39
After a quick talk with @rmohr I will hard coded our both empty class (bridge interface and slirp interface) to create an empty module for our python-sdk.

@fabiand @booxter @vladikr  It sounds good?

I have an open issue on the [swagger-codegen page](https://github.com/swagger-api/swagger-codegen/issues/8356) but no one answer there.

This can be a short term solution and after that I can try to make a pull request on the swagger repo.

**Comment by SchSeba** [comment] 2018-07-02 15:44
My PR is ready waiting to [this issue](https://github.com/kubevirt/client-python/issues/23) to be resolved before push it because I cant test it now.

**Closed** 2018-08-20 08:31 UTC
Labels: kind/bug, topic/api, topic/network
