### ISSUE TITLE
Unable to create VM 

### ISSUE THREAD

**Issue by ansijain** [kubevirt/kubevirt#5358] opened 2021-03-31 12:25 UTC
VM creation failed due to Critical network error
  Warning  SyncFailed        2s    virt-handler, minikube     failed to configure vmi network: Critical network error: could not retrieve pid 52093 selinux label: operation not supported

I tried VM cration following lab https://kubevirt.io/labs/kubernetes/lab1

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
/kind bug
> /kind enhancement

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): Client Version: version.Info{GitVersion:"v0.39.0", GitCommit:"6493f7130788fc2242f0ebbda2ace06dc12a4ad0", GitTreeState:"clean", BuildDate:"2021-03-10T15:29:59Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.39.0-dirty", GitCommit:"6493f7130788fc2242f0ebbda2ace06dc12a4ad0", GitTreeState:"dirty", BuildDate:"2021-03-10T15:56:17Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications: https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/vm.yaml

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
$ kubectl describe virtualmachineinstance.kubevirt.io/testvm
Name:         testvm
Namespace:    default
Labels:       kubevirt.io/domain=testvm
              kubevirt.io/nodeName=minikube
              kubevirt.io/size=small
Annotations:  kubevirt.io/latest-observed-api-version: v1
              kubevirt.io/storage-observed-api-version: v1alpha3
API Version:  kubevirt.io/v1
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:             2021-03-31T11:51:50Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2021-03-31T11:52:01Z
  Finalizers:
    foregroundDeleteVirtualMachine
  Generation:  9
  Managed Fields:
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubevirt.io/latest-observed-api-version:
          f:kubevirt.io/storage-observed-api-version:
        f:labels:
          .:
          f:kubevirt.io/domain:
          f:kubevirt.io/nodeName:
          f:kubevirt.io/size:
        f:ownerReferences:
      f:spec:
        .:
        f:domain:
          .:
          f:devices:
            .:
            f:disks:
            f:interfaces:
          f:firmware:
            .:
            f:uuid:
          f:machine:
            .:
            f:type:
          f:resources:
            .:
            f:requests:
              .:
              f:memory:
        f:networks:
        f:volumes:
      f:status:
        .:
        f:activePods:
          .:
          f:da902f50-e05e-42c9-8438-1667095b9312:
        f:conditions:
        f:guestOSInfo:
        f:nodeName:
        f:qosClass:
    Manager:      virt-controller
    Operation:    Update
    Time:         2021-03-31T11:52:01Z
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:migrationMethod:
        f:phase:
    Manager:    virt-handler
    Operation:  Update
    Time:       2021-03-31T11:52:01Z
  Owner References:
    API Version:           kubevirt.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  VirtualMachine
    Name:                  testvm
    UID:                   6c0025f2-a3fe-43a8-b828-e1e1511001c0
  Resource Version:        15182
  UID:                     aca16bd8-1133-49a1-841b-fca43cec5447
Spec:
  Domain:
    Cpu:
      Cores:    1
      Sockets:  1
      Threads:  1
    Devices:
      Disks:
        Disk:
          Bus:  virtio
        Name:   containerdisk
        Disk:
          Bus:  virtio
        Name:   cloudinitdisk
      Interfaces:
        Bridge:
        Name:  default
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:  5a9fc181-957e-5c32-9e5a-2de5e9673531
    Machine:
      Type:  q35
    Resources:
      Requests:
        Cpu:     100m
        Memory:  64M
  Networks:
    Name:  default
    Pod:
  Volumes:
    Container Disk:
      Image:              quay.io/kubevirt/cirros-container-disk-demo
      Image Pull Policy:  Always
    Name:                 containerdisk
    Cloud Init No Cloud:
      userDataBase64:  SGkuXG4=
    Name:              cloudinitdisk
Status:
  Active Pods:
    da902f50-e05e-42c9-8438-1667095b9312:  minikube
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Message:               cannot migrate VMI which does not use masquerade to connect to the pod network
    Reason:                InterfaceNotLiveMigratable
    Status:                False
    Type:                  LiveMigratable
  Guest OS Info:
  Migration Method:  BlockMigration
  Node Name:         minikube
  Phase:             Failed
  Qos Class:         Burstable
Events:
  Type     Reason            Age   From                       Message
  ----     ------            ----  ----                       -------
  Normal   SuccessfulCreate  18s   virtualmachine-controller  Created virtual machine pod virt-launcher-testvm-jppdp
  Warning  SyncFailed        7s    virt-handler, minikube     failed to configure vmi network: Critical network error: could not retrieve pid 63474 selinux label: operation not supported
  Warning  Stopped           7s    virt-handler, minikube     The VirtualMachineInstance crashed.
  Normal   SuccessfulDelete  7s    virtualmachine-controller  Deleted virtual machine pod virt-launcher-testvm-jppdp

**Comment by phoracek** [comment] 2021-03-31 14:39
Thanks for reporting this, it should be resolved with 0.39.1.

Duplicate of https://github.com/kubevirt/kubevirt/issues/5220.

**Closed by phoracek** 2021-03-31 14:39 UTC
Labels: kind/bug
