### ISSUE TITLE
networkData not effective

### ISSUE THREAD

**Issue by papandadj** [kubevirt/kubevirt#8495] opened 2022-09-21 03:33 UTC
Recently, I use kubevirt as virtual machine. But after restart machine, I found that ip address cannot be assigned.
The default network config:
<img width="613" alt="Screen Shot 2022-09-21 at 11 23 08" src="https://user-images.githubusercontent.com/25424898/191407893-dc502fea-d69e-4100-baec-ee9d2b41ae4b.png">

So, I add networkData filed in vm.yaml, as shown below.
<img width="326" alt="Screen Shot 2022-09-21 at 11 22 09" src="https://user-images.githubusercontent.com/25424898/191407436-7d516e0a-95e4-4c8e-9bbd-cdd544002314.png">

BUT, I found that added filed doesn't seem to work. In vm pod， the network is still the same default network config.
Where am i doing wrong?

**Comment by usrbinkat** [comment] 2022-09-21 14:41
This type of network configuration debugging can be difficult to diagnose. As a first step, can you share a code formatted VM yaml that you are using here?

**Comment by papandadj** [comment] 2022-09-22 01:27
> This type of network configuration debugging can be difficult to diagnose. As a first step, can you share a code formatted VM yaml that you are using here?

thanks for you replay. `spec.source.http.url` image is ubuntu20.04 store in minio
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    description: ""
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  creationTimestamp: "2022-09-20T05:20:57Z"
  generation: 8
  labels:
    create-user: "5627"
    display-name: dongjia-test2
    osType: linux
    cloud.cn/vm: dongjia-test2-wryllx
  name: dongjia-test2-wryllx
  namespace: vm
  resourceVersion: "199820327"
  selfLink: /apis/kubevirt.io/v1/namespaces/vm/virtualmachines/dongjia-test2-wryllx
  uid: 4574b5d2-d20d-4adf-ac7f-5102041d2c30
spec:
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        labels:
          display-name: system-disk
          managed-by: kubevirt
          owned-by: dongjia-test2-wryllx
          owned-by-display-name: dongjia-test2
          system-volume: "true"
          cloud.cn/vm: dongjia-test2-wryllx
        name: dongjia-test2-system-disk-d8ah8n
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 40Gi
          storageClassName: csi-rbd-sc
          volumeMode: Block
        source:
          http:
            url: http://10.0.34.12:9000/kubevirt/ubuntu2004.qcow2
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        cloud.cn/vm: dongjia-test2-wryllx
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: system-disk
            - disk:
                bus: virtio
              name: cloudinitdisk
        machine:
          type: q35
        memory:
          guest: 2Gi
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
      priorityClassName: vm-medium-critical
      volumes:
        - cloudInitNoCloud:
            networkData: |
              network:
                version: 2
                ethernets:
                  enp1s0:
                    dhcp4: true
                  enp1s1:
                    dhcp4: true
            userData: |-
              #cloud-config
              password: dev
              chpasswd: { expire: False }
              ssh_pwauth: True
              disable_root: False
          name: cloudinitdisk
        - dataVolume:
            name: dongjia-test2-system-disk-d8ah8n
          name: system-disk

```

**Comment by papandadj** [comment] 2022-09-23 03:21
Hi @usrbinkat , thinks for your answer. Maybe It is because of a problem with my mirror.
another question. How do i download the image `docker://docker.io/containercraft/ubuntu:20.04` from docker?
If download the image, I want to push this to minio.

**Comment by papandadj** [comment] 2022-09-23 06:02
Thank you @usrbinkat , I using the official mirror and it's fine.

**Comment by usrbinkat** [comment] 2022-09-23 15:16
> How do I download the image docker://docker.io/containercraft/ubuntu:20.04 from docker?

@papandadj FYI, this image is built by CI in a [project that I run](https://github.com/ContainerCraft/kmi); it is not an official Kubevirt or Canonical image.

> I using the official mirror and it's fine.

Awesome! Glad to hear you made progress. If the issue is resolved please kindly close the issue :)

**Comment by papandadj** [comment] 2022-09-24 04:41
Thinks. i will close this issue.

**Closed** 2022-09-24 04:41 UTC
Labels: kind/enhancement
