### ISSUE TITLE
kubevirt v0.7.0-alpha.2 doesn't work with k8s 1.11

### ISSUE THREAD

**Issue by bej-syan** [kubevirt/kubevirt#1279] opened 2018-07-05 07:25 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

When my cluster is up and running, I applied the following two commands. 
    # export VERSION=v0.7.0-alpha.2
    # kubectl create     -f https://github.com/kubevirt/kubevirt/releases/download/$VERSION/kubevirt.yaml

**What happened**:
Got one error: 
error: error validating "https://github.com/kubevirt/kubevirt/releases/download/v0.7.0-alpha.2/kubevirt.yaml": error validating data: [ValidationError(CustomResourceDefinition.status): missing required field "conditions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionStatus, ValidationError(CustomResourceDefinition.status): missing required field "storedVersions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionStatus]; if you choose to ignore these errors, turn validation off with --validate=false

**What you expected to happen**:
No errors, and then deploy a virtualmachine following steps from http://kubevirt.io/get_kubevirt/#deploy-a-virtualmachine 

**How to reproduce it (as minimally and precisely as possible)**:
1, Use 'kubeadm' to set up a cluster (one master and one node) 
2, Both "kubect get pods --all-namespaces" and "kubectl get nodes" output expected results. 
3, run these two commands from http://kubevirt.io/get_kubevirt/#deploy-kubevirt

**Anything else we need to know?**:
N/A 

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:08:34Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
- VM or VMI specifications: 
- Cloud provider or hardware configuration: Virtualmachines for both k8s master and its node
- OS (e.g. from /etc/os-release): RHEL7.5
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by slintes** [comment] 2018-07-05 15:36
Hi, the missing field "storedVersions" is new in Kubernetes 1.11, which we don't support yet. I will check our plans regarding this and report back. In the meanwhile you might want to run kubevirt on a 1.10 Kubernetes cluster. Thanks for reporting!

**Comment by slintes** [comment] 2018-07-20 11:55
Turned out that this issue is caused by unneeded CRD status fields in our manifests. This was fixed already in the library we use for generating the manifests, see https://github.com/ant31/crd-validation/pull/5

Once the PR is merged and a new release is published, KubeVirt will work on k8s 1.11

**Closed** 2018-07-22 06:34 UTC
Labels: kind/bug, priority/critical-urgent
