### ISSUE TITLE
[Flakey Test] Configurations VirtualMachineInstance definition [rfe_id:893][crit:medium][vendor:cnv-qe@redhat.com][level:component]with rng [test_id:1675]should not have the virtio rng device when not present

### ISSUE THREAD

**Issue by shwetaap** [kubevirt/kubevirt#4003] opened 2020-08-17 20:34 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
>  /triage build-officer 

**What happened**:

Test fails
Configurations VirtualMachineInstance definition [rfe_id:893][crit:medium][vendor:cnv-qe@redhat.com][level:component]with rng [test_id:1675]should not have the virtio rng device when not present

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3938/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1294113012638027776

**What you expected to happen**:
Test should pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment] 2020-08-18 08:54
/close

Thanks @shwetaap closing this as a duplicate of #2566

**Closed by rmohr** 2020-08-18 08:54 UTC
