### ISSUE TITLE
[Flaky CI] Configurations VirtualMachineInstance definition [rfe_id:3077][crit:medium][vendor:cnv-qe@redhat.com][level:component]with input devices [test_id:3073]should start the VMI with tablet input device with usb bus

### ISSUE THREAD

**Issue by tomob** [kubevirt/kubevirt#4197] opened 2020-09-18 09:26 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/triage build-watcher

**What happened**:
CI Test failed

```
/root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:764
Unexpected Warning event received: testvmi4dr7j89t9wmxs7nnxb7899xzfrxgvdlbmh5hldplgph8m4bn,610dc30a-1377-48c6-ae80-edfc92b697d4: server error. command SyncVMI failed: "LibvirtError(Code=38, Domain=0, Message='cannot open /dev/null: Operation not permitted')"
```
Prow link: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4083/pull-kubevirt-e2e-k8s-1.16/1306513737737310208

**What you expected to happen**:
CI tests should pass.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Might be related to #4180 (Same error message, different test)

**Environment**:

Test lane: pull-kubevirt-e2e-k8s-1.16

**Comment by rmohr** [comment] 2020-09-18 15:36
/close

Thanks for reporting. Duplicate of #2566. Sadly an infra issue which we so far can only make happen less often and could not identify the root cause.

**Closed by rmohr** 2020-09-18 15:36 UTC
Labels: kind/bug, triage/build-watcher
