### ISSUE TITLE
panic: timed out waiting for domain to be defined

### ISSUE THREAD

**Issue by talcoh2x** [kubevirt/kubevirt#4556] opened 2020-11-15 14:43 UTC
>
**What happened**:
I'm trying to run a clean ubuntu18 VM image by using "container registry" as follow here:
https://github.com/kubevirt/kubevirt/blob/master/docs/container-register-disks.md
I need your help guys. 

steps : 
1 - create new VM image (clean ubunt18)
2 - create DockerFile:
cat /tmp/vmdisk/Dockerfile
FROM kubevirt/container-disk-v1alpha
ADD  ubuntu18_kubevirt.qcow2  /disk
3) run VM: 
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvm3
spec:
  domain:
    devices:
      disks:
      - type: ContainerDisk:v1alpha
        - source:
          name: vmkubevirt:latest
        - target:
          device: sda

> 
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:68","timestamp":"2020-11-15T14:39:17.996509Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:71","timestamp":"2020-11-15T14:39:17.996584Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu:///system","pos":"libvirt.go:380","timestamp":"2020-11-15T14:39:18.000733Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory')","pos":"libvirt.go:388","timestamp":"2020-11-15T14:39:18.001031Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 6.0.0, package: 16.fc31 (Unknown, 2020-04-07-15:55:55, )","subcomponent":"libvirt","thread":"70","timestamp":"2020-11-15T14:39:18.022000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: testvm-ubt18","subcomponent":"libvirt","thread":"70","timestamp":"2020-11-15T14:39:18.022000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Child process (/usr/sbin/dmidecode -q -t 0,1,2,3,4,17) unexpected exit status 1: /dev/mem: No such file or directory","pos":"virCommandWait:2709","subcomponent":"libvirt","thread":"70","timestamp":"2020-11-15T14:39:18.022000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:396","timestamp":"2020-11-15T14:39:18.502454Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:394","timestamp":"2020-11-15T14:39:18.504960Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:71","timestamp":"2020-11-15T14:39:18.505083Z"}
panic: timed out waiting for domain to be defined

goroutine 1 [running]:
main.waitForDomainUUID(0x45d964b800, 0xc000526660, 0xc0017d4300, 0x1c1cce0, 0xc00170e070, 0xc000526660)
        cmd/virt-launcher/virt-launcher.go:213 +0x3f4
main.main()
        cmd/virt-launcher/virt-launcher.go:427 +0xe6c
{"component":"virt-launcher","level":"error","msg":"dirty virt-launcher shutdown","pos":"virt-launcher.go:508","reason":"exit status 2","timestamp":"2020-11-15T14:44:18.513338Z"}
> 

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment] 2020-11-16 07:51
@talcoh2x the k8s events should very likely show you some warnings which can help you. Btw, your VMI yaml looks invalid. Can it be that you don't have webhooks enabled on your machine? Otherwise I have no idea how you could post such a VMI definition.

**Comment by rmohr** [comment] 2020-11-16 07:52
Here a cirros example with cloud-init: https://kubevirt.io/user-guide/#/architecture?id=example

**Comment by talcoh2x** [comment] 2020-11-16 10:41
@rmohr Maybe you can help me understand how to provision a clean VM -ubuntu 18.04 ? 
what is the faster way to do it?
please help thanks

**Comment by jean-edouard** [comment] 2020-12-02 17:04
This looks like a duplicate of https://github.com/kubevirt/kubevirt/issues/3933

**Closed** 2021-05-01 19:14 UTC
Labels: lifecycle/rotten
