### ISSUE TITLE
[Flaky CI] Configurations VirtualMachineInstance definition [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]with guestAgent [test_id:4628]should not return the whole data when agent is not present

### ISSUE THREAD

**Issue by tomob** [kubevirt/kubevirt#4211] opened 2020-09-18 15:14 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-watcher

**What happened**:

CI Test failed with libvirt error:

```
Configurations  VirtualMachineInstance definition  [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]with  guestAgent [test_id:4628]should not return the whole data when agent is  not present 

/root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:1286 Unexpected Warning event received: testvmir4jw9v5zxmvkl4rjr5wmqlv2pnt9lp4xd4ssppnqbwk66ndw,31bd762f-aa38-45fb-bb43-41f366148b1a: server error. command SyncVMI failed: "LibvirtError(Code=67, Domain=10, Message='unsupported configuration: Domain requires KVM, but it is not available. Check that virtualization is enabled in the host BIOS, and host configuration is setup to load the kvm modules.')" Expected     <string>: Warning not to equal     <string>: Warning /root/go/src/kubevirt.io/kubevirt/tests/utils.go:357
```

Prow link: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4035/pull-kubevirt-e2e-k8s-1.16/1305762285783879680

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Test lane: pull-kubevirt-e2e-k8s-1.16

**Comment by rmohr** [comment] 2020-09-18 15:41
/close

Thanks for reporting. Duplicate of #3872. Sadly an infra issue which we so far can only make happen less often and could not identify the root cause.

**Closed** 2020-09-18 15:41 UTC
Labels: kind/bug, triage/build-watcher
