### ISSUE TITLE
[rfe_id:609]VMIheadless [rfe_id:609]Creating a VirtualMachineInstance with headless [test_id:714][posneg:positive]should not have vnc graphic device in xml

### ISSUE THREAD

**Issue by tiraboschi** [kubevirt/kubevirt#3748] opened 2020-07-03 10:51 UTC
/kind bug
/triage build-officer

**What happened**:

`[rfe_id:609]VMIheadless [rfe_id:609]Creating a VirtualMachineInstance with headless [test_id:714][posneg:positive]should not have vnc graphic device in xml`

```
/root/go/src/kubevirt.io/kubevirt/tests/vmi_headless_test.go:62
Unexpected Warning event received: testvminhsqq2b977qxzxmdvkcppcfzbq8czxm8pncd5l5pp65tgxvn,b821b0a8-c3c7-4056-aeb6-0f0915db15f1: server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: Failed to start QEMU binary /usr/libexec/qemu-kvm for probing: ')"
Expected
    <string>: Warning
not to equal
    <string>: Warning
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:410
```

**How to reproduce it (as minimally and precisely as possible)**:
[Prow Job Link](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3517/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1278805176970383360)
**Lane**:
pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6

**Comment by rmohr** [comment] 2020-08-18 11:48
/close

Thanks @tiraboschi  closing this as a duplicate of #3757

**Closed by rmohr** 2020-08-18 11:48 UTC
Labels: kind/bug, triage/build-officer
