### ISSUE TITLE
Kubeadm init blocks waiting for  "control plane to become ready".

### ISSUE THREAD

**Issue by kenzhaoyihui** [kubevirt/kubevirt#43] opened 2017-01-11 10:11 UTC
Hi, all
     From the quick start guide, i will have a try, but after executed the "vagrant up", it will stucked by the script "cluster/vagrant/setup_kubernetes_master.sh". It  was executing "kubeadm init --api-advertise-addresses=$ADVERTISED_MASTER_IP --pod-network-cidr=10.244.0.0/16 --token abcdef.1234567890123456 --use-kubernetes-version v1.4.5" and blocks waiting for "control plane to become ready".

 If get rid of the parameter "--use-kubernetes-version v1.4.5", i was successfully to finish the guide.
Maybe kubeadm use default kuernetes version v1.5.1,  does the kubernetes version affect the installation?
   
Thanks

**Comment by rmohr** [comment] 2017-01-11 14:33
Hi,

The version should not matter as long as it is at least 1.4.5. I just recreated the vagrant environment a few hours ago with v1.4.5 and it worked without issues. I will retry it.

**Comment by rmohr** [comment] 2017-01-11 18:17
Tried a fresh deployment two times with 1.4.5. Works like expected for me.
Closing this. Feel free to reopen it if you see this again.

**Comment by fabiand** [comment] 2017-01-12 14:05
@kenzhaoyihui could you please provide the exact steps you took to run into this issue?

**Comment by kenzhaoyihui** [comment] 2017-01-13 05:20
@fabiand Hi fabiand, i will provide the exact steps to you.

ENV:
Fedora25 workstation
vagrant-1.8.5-2.fc25.noarch
vagrant-libvirt-0.0.35-1.fc25.noarch
kubelet-1.5.1-0.x86_64
kubernetes-cni-0.3.0.1-0.07a8a2.x86_64
kubectl-1.5.1-0.x86_64
kubeadm-1.6.0-0.alpha.0.2074.a092d8e0f95f52.x86_64

Steps:
Just follow the "Getting started guide"

Issue:
 # vagrant up
...
==> master: [apiclient] Created API client, waiting for the control plane to become ready

Stucked by this  step.

Additional info:
1. I just finished the guide successfully one time via modify the "set_kubernetes_master.sh", 
    get rid of the parameter "--use-kubernetes-version v1.4.5"
2. But i retry it on a fresh env today, it also met the issue. So maybe there is no relation about the parameter "--use-kubernetes-version v1.4.5".
3. I don't know what the thread affect "kubeadm init".

**Comment by kenzhaoyihui** [comment] 2017-01-13 14:22
@fabiand Hi fabiand,  I retry  it again.  met same issue with this . 

But found the strange question about the scripts "set_kubernetes_master.sh". 
I use the command " dig +short master" on the VM master .  But the result is not the VM master's ip

Like this:  root@master# dig +short master                    -->  192.168.121.209
                root@master#ip a s                                         -->   192.168.121.68

So while execute "kubeadm init --api-advertise-addresses=$ADVERTISED_MASTER_IP --pod-network-cidr=10.244.0.0/16 --token abcdef.1234567890123456 --use-kubernetes-version v1.4.5",   it would appear that "waiting for control plane to become ready".


Workaround: Get rid of the parament "--api-advertise-addresses=$ADVERTISED_MASTER_IP" ,use command "kubeadm init  --pod-network-cidr=10.244.0.0/16 --token abcdef.1234567890123456 --use-kubernetes-version v1.4.5". it can work well for me.

Thanks

**Comment by rmohr** [comment] 2017-01-16 08:28
@kenzhaoyihui Could you share the following?

 * OS versoin
 * vagrant version
 * libvirt version
 * vagrant-libvirt version

**Comment by kenzhaoyihui** [comment] 2017-01-16 08:33
@rmohr 
ENV:
Fedora25 workstation
vagrant-1.8.5-2.fc25.noarch
vagrant-libvirt-0.0.35-1.fc25.noarch
libvirt-2.2.0-2.fc25.x86_64

kubelet-1.5.1-0.x86_64
kubernetes-cni-0.3.0.1-0.07a8a2.x86_64
kubectl-1.5.1-0.x86_64
kubeadm-1.6.0-0.alpha.0.2074.a092d8e0f95f52.x86_64

**Comment by rmohr** [comment] 2017-01-16 09:26
@kenzhaoyihui thx, the versions look fine. I create #50, which should fix your problem. Like you suggested, I removed the advertise IP

Could you do me one more favour?

Could you checkout #50 and do the following:

```
vagrant destroy
export VAGRANT_NUM_NODES=1
vagrant up
```

This should create two VMs, `master` and `node0`. I am wondering if the `dig +short master` call on `node0` works (we need it on the node, to discover the master to register to ...). Note that it takes some time until `master` is ready and that you will see a few times

```
==> node0: [discovery] Failed to request cluster info, will try again: [Get http://192.168.121.75:9898/cluster-info/v1/?token-id=abcdef: dial tcp 192.168.121.75:9898: getsockopt: connection refused]
```

from the node.

For me it works, but it worked for me before too ...

**Comment by kenzhaoyihui** [comment] 2017-01-17 07:11
Yes, it works for me by my env.

**Comment by rmohr** [comment] 2017-01-17 11:12
Thanks for your help :+1:

**Comment by kenzhaoyihui** [comment] 2017-03-29 07:37
When try to the latest git, I met the previous issue.  Blocked by this step.
```
==> master: [kubeadm] WARNING: kubeadm is in alpha, please do not use it for production clusters.
==> master: [preflight] Running pre-flight checks
==> master: [init] Using Kubernetes version: v1.5.4
==> master: [tokens] Validating provided token
==> master: [tokens] Accepted provided token
==> master: [certificates] Generated Certificate Authority key and certificate.
==> master: [certificates] Generated API Server key and certificate
==> master: [certificates] Generated Service Account signing keys
==> master: [certificates] Created keys and certificates in "/etc/kubernetes/pki"
==> master: [kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
==> master: [kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
==> master: [apiclient] Created API client, waiting for the control plane to become ready
```

The /var/log/messages on master:
```
Mar 29 07:25:43 master kubelet: I0329 07:25:43.574433   18454 kubelet.go:255] Adding manifest file: /etc/kubernetes/manifests
Mar 29 07:25:43 master kubelet: I0329 07:25:43.574471   18454 kubelet.go:265] Watching apiserver
Mar 29 07:25:43 master kubelet: E0329 07:25:43.577591   18454 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:382: Failed to list *v1.Service: Get https://192.168.200.2:6443/api/v1/services?resourceVersion=0: dial tcp 192.168.200.2:6443: getsockopt: connection refused
Mar 29 07:25:43 master kubelet: E0329 07:25:43.577692   18454 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://192.168.200.2:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dmaster&resourceVersion=0: dial tcp 192.168.200.2:6443: getsockopt: connection refused
Mar 29 07:25:43 master kubelet: E0329 07:25:43.577728   18454 reflector.go:190] k8s.io/kubernetes/pkg/kubelet/kubelet.go:390: Failed to list *v1.Node: Get https://192.168.200.2:6443/api/v1/nodes?fieldSelector=metadata.name%3Dmaster&resourceVersion=0: dial tcp 192.168.200.2:6443: getsockopt: connection refused
Mar 29 07:25:43 master kubelet: W0329 07:25:43.579236   18454 kubelet_network.go:70] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
Mar 29 07:25:43 master kubelet: I0329 07:25:43.579258   18454 kubelet.go:494] Hairpin mode set to "hairpin-veth"
Mar 29 07:25:43 master kubelet: W0329 07:25:43.579306   18454 cni.go:157] Unable to update cni config: No networks found in /etc/cni/net.d
Mar 29 07:25:43 master kubelet: W0329 07:25:43.579621   18454 cni.go:157] Unable to update cni config: No networks found in /etc/cni/net.d
Mar 29 07:25:43 master kubelet: W0329 07:25:43.583479   18454 cni.go:157] Unable to update cni config: No networks found in /etc/cni/net.d
Mar 29 07:25:43 master kubelet: I0329 07:25:43.583493   18454 docker_service.go:187] Docker cri networking managed by cni
Mar 29 07:25:43 master kubelet: error: failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from docker cgroup driver: "systemd"
Mar 29 07:25:43 master systemd: kubelet.service: main process exited, code=exited, status=1/FAILURE
Mar 29 07:25:43 master systemd: Unit kubelet.service entered failed state.
Mar 29 07:25:43 master systemd: kubelet.service failed.
```

Packages verison if need:
```
Fedora 25 
vagrant-libvirt-0.0.35-3.fc25.noarch
vagrant-1.8.5-2.fc25.noarch
libvirt-daemon-driver-storage-2.2.0-2.fc25.x86_64
libvirt-glib-0.2.3-2.fc24.x86_64
libvirt-daemon-driver-secret-2.2.0-2.fc25.x86_64
vagrant-libvirt-0.0.35-3.fc25.noarch
libvirt-daemon-driver-qemu-2.2.0-2.fc25.x86_64
libvirt-daemon-driver-nodedev-2.2.0-2.fc25.x86_64
libvirt-gobject-0.2.3-2.fc24.x86_64
rubygem-ruby-libvirt-0.7.0-1.fc25.x86_64
rubygem-fog-libvirt-0.3.0-1.fc25.noarch
libvirt-daemon-driver-nwfilter-2.2.0-2.fc25.x86_64
libvirt-daemon-2.2.0-2.fc25.x86_64
libvirt-gconfig-0.2.3-2.fc24.x86_64
libvirt-daemon-kvm-2.2.0-2.fc25.x86_64
libvirt-libs-2.2.0-2.fc25.x86_64
libvirt-daemon-driver-interface-2.2.0-2.fc25.x86_64
libvirt-daemon-driver-network-2.2.0-2.fc25.x86_64
libvirt-devel-2.2.0-2.fc25.x86_64

kubernetes-cni-0.5.1-0.x86_64
kubeadm-1.6.0-0.alpha.0.2074.a092d8e0f95f52.x86_64
kubectl-1.6.0-0.x86_64
cockpit-kubernetes-131-3.el7.centos.x86_64
kubelet-1.6.0-0.x86_64
```

Additional info:
Already close selinux and disable firewalld on Fedora 25 host.
```
systemctl stop firewalld
systemctl disable firewalld
setenforce 0

[root@dhcp-8-120 ~]# getenforce 
Permissive

```

So, is it my network problem ? Could you give me some ideas?

**Comment by rmohr** [comment] 2017-03-29 09:01
Can reproduce this. Something seems to have changed in a dependency somewhere.

**Comment by rmohr** [comment] 2017-03-29 09:11
Ok, apparently latest docker release on centos switched from "cgroupfs" to "systemd" cgroup driver.

**Comment by kenzhaoyihui** [comment] 2017-03-29 09:16
Yes, the /var/log/messages mentioned this error.

**Comment by rmohr** [comment] 2017-03-29 13:20
@kenzhaoyihui it should work now, could you retry it?

**Comment by rmohr** [comment] 2017-04-03 09:42
Broken again. #179 should solve it.

**Comment by rmohr** [comment] 2017-04-03 10:17
Works again.

**Closed by rmohr** 2017-04-03 10:17 UTC
Labels: bug

**Comment by kenzhaoyihui** [comment] 2017-04-07 04:57
1. Kube-apiserver don't run (latest git) , master log is here:
"dial tcp 192.168.200.2:6443: getsockopt: connection refused"
Unfortunately, It works failed for me.

Any ideas ?

```
Apr  7 04:50:43 master kubelet: E0407 04:50:43.444165   15973 reflector.go:188] pkg/kubelet/kubelet.go:386: Failed to list *api.Node: Get https://192.168.200.2:6443/api/v1/nodes?fieldSelector=metadata.name%3Dmaster&resourceVersion=0: dial tcp 192.168.200.2:6443: getsockopt: connection refused
Apr  7 04:50:43 master kubelet: E0407 04:50:43.445245   15973 reflector.go:188] pkg/kubelet/config/apiserver.go:44: Failed to list *api.Pod: Get https://192.168.200.2:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dmaster&resourceVersion=0: dial tcp 192.168.200.2:6443: getsockopt: connection refused
Apr  7 04:50:43 master kubelet: E0407 04:50:43.446310   15973 reflector.go:188] pkg/kubelet/kubelet.go:378: Failed to list *api.Service: Get https://192.168.200.2:6443/api/v1/services?resourceVersion=0: dial tcp 192.168.200.2:6443: getsockopt: connection refused
Apr  7 04:50:44 master kubelet: E0407 04:50:44.444853   15973 reflector.go:188] pkg/kubelet/kubelet.go:386: Failed to list *api.Node: Get https://192.168.200.2:6443/api/v1/nodes?fieldSelector=metadata.name%3Dmaster&resourceVersion=0: dial tcp 192.168.200.2:6443: getsockopt: connection refused
Apr  7 04:50:44 master kubelet: E0407 04:50:44.445864   15973 reflector.go:188] pkg/kubelet/config/apiserver.go:44: Failed to list *api.Pod: Get https://192.168.200.2:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dmaster&resourceVersion=0: dial tcp 192.168.200.2:6443: getsockopt: connection refused
Apr  7 04:50:44 master kubelet: E0407 04:50:44.446847   15973 reflector.go:188] pkg/kubelet/kubelet.go:378: Failed to list *api.Service: Get https://192.168.200.2:6443/api/v1/services?resourceVersion=0: dial tcp 192.168.200.2:6443: getsockopt: connection refused
Apr  7 04:50:44 master kubelet: E0407 04:50:44.594433   15973 kube_docker_client.go:324] Cancel pulling image "gcr.io/google_containers/pause-amd64:3.0" because of no progress for 1m0s, latest progress: "Trying to pull repository gcr.io/google_containers/pause-amd64 ... "
Apr  7 04:50:44 master kubelet: E0407 04:50:44.594887   15973 docker_manager.go:2183] Failed to create pod infra container: ErrImagePull; Skipping pod "kube-controller-manager-master_kube-system(bb3e17a6a89b089d8c5b893c8562aca0)": image pull failed for gcr.io/google_containers/pause-amd64:3.0, this may be because there are no credentials on this request.  details: (net/http: request canceled)
Apr  7 04:50:44 master kubelet: E0407 04:50:44.594958   15973 pod_workers.go:184] Error syncing pod bb3e17a6a89b089d8c5b893c8562aca0, skipping: failed to "StartContainer" for "POD" with ErrImagePull: "image pull failed for gcr.io/google_containers/pause-amd64:3.0, this may be because there are no credentials on this request.  details: (net/http: request canceled)"
Apr  7 04:50:44 master dockerd-current: time="2017-04-07T04:50:44.595614576Z" level=info msg="{Action=create, LoginUID=4294967295, PID=15973}"
Apr  7 04:50:45 master kubelet: E0407 04:50:45.214421   15973 event.go:208] Unable to write event: 'dial tcp 192.168.200.2:6443: getsockopt: connection refused' (may retry after sleeping)
Apr  7 04:50:45 master kubelet: E0407 04:50:45.214455   15973 event.go:143] Unable to write event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"master.14b3017571053476", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]api.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:api.ObjectReference{Kind:"Node", Namespace:"", Name:"master", UID:"master", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientDisk", Message:"Node master status is now: NodeHasSufficientDisk", Source:api.EventSource{Component:"kubelet", Host:"master"}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63627134305, nsec:508734070, loc:(*time.Location)(0x3efd3e0)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63627134305, nsec:508734070, loc:(*time.Location)(0x3efd3e0)}}, Count:1, Type:"Normal"}' (retry limit exceeded!)
Apr  7 04:50:45 master kubelet: E0407 04:50:45.215361   15973 event.go:208] Unable to write event: 'dial tcp 192.168.200.2:6443: getsockopt: connection refused' (may retry after sleeping)
Apr  7 04:50:45 master kubelet: E0407 04:50:45.445613   15973 reflector.go:188] pkg/kubelet/kubelet.go:386: Failed to list *api.Node: Get https://192.168.200.2:6443/api/v1/nodes?fieldSelector=metadata.name%3Dmaster&resourceVersion=0: dial tcp 192.168.200.2:6443: getsockopt: connection refused
Apr  7 04:50:45 master kubelet: E0407 04:50:45.446627   15973 reflector.go:188] pkg/kubelet/config/apiserver.go:44: Failed to list *api.Pod: Get https://192.168.200.2:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dmaster&resourceVersion=0: dial tcp 192.168.200.2:6443: getsockopt: connection refused
Apr  7 04:50:45 master kubelet: E0407 04:50:45.447815   15973 reflector.go:188] pkg/kubelet/kubelet.go:378: Failed to list *api.Service: Get https://192.168.200.2:6443/api/v1/services?resourceVersion=0: dial tcp 192.168.200.2:6443: getsockopt: connection refused
```

```
==> master: [kubeadm] WARNING: kubeadm is in alpha, please do not use it for production clusters.
==> master: [preflight] Running pre-flight checks
==> master: [init] Using Kubernetes version: v1.5.4
==> master: [tokens] Validating provided token
==> master: [tokens] Accepted provided token
==> master: [certificates] Generated Certificate Authority key and certificate.
==> master: [certificates] Generated API Server key and certificate
==> master: [certificates] Generated Service Account signing keys
==> master: [certificates] Created keys and certificates in "/etc/kubernetes/pki"
==> master: [kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
==> master: [kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
==> master: [apiclient] Created API client, waiting for the control plane to become ready
```

**Comment by rmohr** [comment] 2017-04-07 06:43
@kenzhaoyihui how long did you wait? What you are seeing there is not necessarely an error.

There is only one line which might be suspicious:

```
Apr  7 04:50:45 master kubelet: E0407 04:50:45.214455   15973 event.go:143] Unable to write event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"master.14b3017571053476", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]api.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:api.ObjectReference{Kind:"Node", Namespace:"", Name:"master", UID:"master", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientDisk", Message:"Node master status is now: NodeHasSufficientDisk", Source:api.EventSource{Component:"kubelet", Host:"master"}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63627134305, nsec:508734070, loc:(*time.Location)(0x3efd3e0)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63627134305, nsec:508734070, loc:(*time.Location)(0x3efd3e0)}}, Count:1, Type:"Normal"}' (retry limit exceeded!)
```

The other errors are pretty normal, since it takes its time until the apiserver is ready to accept connections. I have them too in my logs.

I ran it myself right now from latest master and it worked. Can you verify that you are on latest master and try again?

**Comment by kenzhaoyihui** [comment] 2017-04-07 07:30
@rmohr  This try is on latest master. Unfortunately,I execute it many times and keep the status "  [apiclient] Created API client, waiting for the control plane to become ready", I wait for a long time, for example an hour or two hours.  

```
[root@dhcp-8-213 kubevirt]# git pull
Already up-to-date.
[root@dhcp-8-213 kubevirt]# vagrant up
```

Find some errors in master /var/log/messages:
```
Apr  7 07:06:53 master kubelet: E0407 07:06:53.282330   15979 cni.go:163] error updating cni config: No networks found in /etc/cni/net.d
```

```
Apr  7 07:06:55 master kubelet: E0407 07:06:55.697618   15979 event.go:143] Unable to write event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:     ""}, ObjectMeta:api.ObjectMeta{Name:"master.14b30ba6f975a82d", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, Crea     tionTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds     :(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]api.OwnerReference(nil), Finalizers:[]string(nil), ClusterN     ame:""}, InvolvedObject:api.ObjectReference{Kind:"Node", Namespace:"", Name:"master", UID:"master", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Im     ageGCFailed", Message:"unable to find data for container /", Source:api.EventSource{Component:"kubelet", Host:"master"}, FirstTimestamp:unversioned.Time{Time:ti     me.Time{sec:63627145513, nsec:367480365, loc:(*time.Location)(0x3efd3e0)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63627145513, nsec:367480365, loc:(     *time.Location)(0x3efd3e0)}}, Count:1, Type:"Warning"}' (retry limit exceeded!)
```

Anything about the network ?

***Detail information about log:***
[Detail messages log](https://raw.githubusercontent.com/kenzhaoyihui/issue_picture/master/master_var_log_messages)

**Comment by rmohr** [comment] 2017-04-07 07:36
Hm, do you have any other VMs running? Maybe the IP 192.168.200.2 is routed somewhere else? But really just guessing at the moment.

The CNI network error is ok, it will be deployed after the apiserver is ready. Until then you see from time to time complains that CNI is not yet ready.

**Comment by kenzhaoyihui** [comment] 2017-04-07 07:52
@rmohr No any other VMs running. Anyting error about the route?

```
[root@master ~]# ip route
default via 192.168.121.1 dev eth0  proto static  metric 101 
169.254.0.0/16 dev eth1  scope link  metric 1003 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
192.168.121.0/24 dev eth0  proto kernel  scope link  src 192.168.121.159  metric 100 
192.168.122.0/24 dev virbr0  proto kernel  scope link  src 192.168.122.1 
192.168.200.0/24 dev eth1  proto kernel  scope link  src 192.168.200.2 
```

```
[root@master ~]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.121.1   0.0.0.0         UG    101    0        0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U     1003   0        0 eth1
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.121.0   0.0.0.0         255.255.255.0   U     100    0        0 eth0
192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 virbr0
192.168.200.0   0.0.0.0         255.255.255.0   U     0      0        0 eth1
```

```
[root@dhcp-8-213 log]# ip route
default via 10.66.11.254 dev eno1  proto static  metric 100 
10.66.8.0/22 dev eno1  proto kernel  scope link  src 10.66.8.213  metric 100 
10.72.17.5 via 10.66.11.254 dev eno1  proto dhcp  metric 100 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 linkdown 
192.168.121.0/24 dev virbr0  proto kernel  scope link  src 192.168.121.1 
192.168.200.0/24 dev virbr1  proto kernel  scope link  src 192.168.200.1 
```

**Comment by rmohr** [comment] 2017-04-07 11:21
Hm, it looks completely equal.

Are the libvirt and vagrant versions above still the ones you are using? Could you do a `virsh dumpxml kubevirt_master`?

**Comment by cynepco3hahue** [comment] 2017-07-20 07:01
@rmohr Hi Roman, I have the same issue on my Fedora26
```
==> master: [kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
==> master: [kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
==> master: [apiclient] Created API client, waiting for the control plane to become ready
```
Versions:
```
4.11.10-300.fc26.x86_64
vagrant-1.9.1-2.fc26.noarch
vagrant-libvirt-0.0.37-5.fc26.noarch
```
Vagrant VM:
```
[vagrant@master ~]$ ip route
default via 192.168.121.1 dev eth0  proto static  metric 100 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
192.168.121.0/24 dev eth0  proto kernel  scope link  src 192.168.121.188  metric 100
```
/var/log/messages

[messages.txt](https://github.com/kubevirt/kubevirt/files/1161418/messages.txt)

**Comment by cynepco3hahue** [comment] 2017-07-20 07:02
@rmohr Just forgot to mention, removing `--apiserver-advertise-address=$ADVERTISED_MASTER_IP` fixes the problem

**Comment by rmohr** [comment] 2017-07-20 08:11
@cynepco3hahue I am pretty sure, that this only solves the problem of the master/node registration, but there is a good chance that your k8s networking setup is still broken. Could you try out #330 and see if your deployment works?

**Comment by cynepco3hahue** [comment] 2017-07-20 09:01
@rmohr with #330 kubernetes succeeds to start `make test` pass without any failures

**Comment by rmohr** [comment] 2017-07-20 09:09
@cynepco3hahue you need to run `make functests` after you ran `cluster/sync.sh`. Did you do that too?

**Comment by cynepco3hahue** [comment] 2017-07-20 09:28
My steps:
- `vagrant up`
- `make vagrant-deploy`
- `make functests` - PASS
It looks nice, but sometimes it looses route to cluster network until I run `vagrant reload`
dial tcp 192.168.200.2:8184: getsockopt: no route to host 
I will put additional information when I will able to reproduce it.

**Comment by rmohr** [comment] 2017-07-20 09:40
Cool thx. Yes this `getsockopt` issue is annoying. Was not aware that `vagrant reload` fixes this. I always restarted my vagrant machines then.
