### ISSUE TITLE
[Flaky CI] Configurations VirtualMachineInstance definition [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]with guestAgent [test_id:4627]should return the whole data when agent is present

### ISSUE THREAD

**Issue by mhenriks** [kubevirt/kubevirt#4190] opened 2020-09-17 12:26 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-watcher
> /kind enhancement

**What happened**:

```Unexpected Warning event received: testvmijgh5kxh5m7ntgpz27pjbqw9mx2lx55zd67ch5pgts5xk9mjw,6c7f05f5-e43b-44de-a5f0-3cd7e14c8e24: server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor: 2020-09-16T09:14:26.831150Z qemu-kvm: -object rng-random,id=objrng0,filename=/dev/urandom: Could not open '/dev/urandom': Operation not permitted')"```

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4115/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1306138390030192642

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment] 2020-09-18 15:37
/close

Thanks for reporting. Duplicate of #2566. Sadly an infra issue which we so far can only make happen less often and could not identify the root cause.

**Closed by rmohr** 2020-09-18 15:38 UTC
Labels: kind/bug, triage/build-watcher
