### ISSUE TITLE
[flaky ci] [test_id:1199]Probes for liveness should not fail the VMI with working TCP probe and tcp server

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3669] opened 2020-06-25 17:39 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

[ref_id:1182]Probes for liveness should not fail the VMI [test_id:1199][posneg:positive]with working TCP probe and tcp server

/root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43 VMI testvmiz2fc8bwwnx999mwml2xqbw6j9ktgp478npb8579f86xg8v49 unexpectedly stopped. State: Failed Expected     <bool>: true to be false /root/go/src/kubevirt.io/kubevirt/tests/utils.go:2657

Failing job- https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1275865685297205248

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment] 2020-06-28 06:09
duplicate of #3575 
i see the panic at 
5_kubevirt_virt-handler-ns8lw-virt-handler_previous.log

**Comment by rmohr** [comment] 2020-06-29 15:56
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3509/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1277077919100833792

**Comment by oshoval** [comment] 2020-06-29 16:13
> https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3509/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1277077919100833792

this link appears at
https://github.com/kubevirt/kubevirt/issues/3697
and indeed is dupe of #3575 
but i am close to a final PR for it

**Comment by oshoval** [comment] 2020-07-05 11:28
#3713 merged, please close

**Comment by rmohr** [comment] 2020-07-06 07:28
@oshoval the logs don't contain a hint that virt-handler crashed. It looks different. Leaving it open for now.

**Comment by oshoval** [comment] 2020-07-06 07:30
> @oshoval the logs don't contain a hint that virt-handler crashed. It looks different. Leaving it open for now.

Crashed here,
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1275865685297205248/artifacts/pods/5_kubevirt_virt-handler-ns8lw-virt-handler_previous.log

(referring to the link in the original post)

**Comment by rmohr** [comment] 2020-07-06 07:34
@oshoval that are the wrong results. It seems like since we updated prow that the junit results are now sorted in the overview. That is a little bit annoying but the first test which failed was this one, not the 5th one.

**Comment by oshoval** [comment] 2020-07-06 07:38
> @oshoval that are the wrong results. It seems like since we updated prow that the junit results are now sorted in the overview. That is a little bit annoying but the first test which failed was this one, not the 5th one.

You right thanks, just a nit
upon refreshing 
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1275865685297205248

Junit order changes...

**Closed** 2020-12-05 10:10 UTC
Labels: kind/bug, lifecycle/rotten, sig/network, triage/build-watcher
