### ISSUE TITLE
vmlifecycle test fails on Openshift

### ISSUE THREAD

**Issue by gbenhaim** [kubevirt/kubevirt#700] opened 2018-02-01 16:44 UTC
I've tried to run Kubvirt's functional tests on Openshift 3.7, and `vmlifecycle_test` failed with the following error:

```
• Failure [25.393 seconds]
Vmlifecycle
/root/go/src/kubevirt.io/kubevirt/tests/vmlifecycle_test.go:41
  New VM given
  /root/go/src/kubevirt.io/kubevirt/tests/vmlifecycle_test.go:60
    New VM that will be killed
    /root/go/src/kubevirt.io/kubevirt/tests/vmlifecycle_test.go:200
      Should be in Failed phase [It]
      /root/go/src/kubevirt.io/kubevirt/tests/vmlifecycle_test.go:201

      Expected
          <*errors.StatusError | 0xc42056a360>: {
              ErrStatus: {
                  TypeMeta: {Kind: "", APIVersion: ""},
                  ListMeta: {SelfLink: "", ResourceVersion: "", Continue: ""},
                  Status: "Failure",
                  Message: "pods \"vm-killer\" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used securityContext.runAsUser: Invalid value: 0: UID on container vm-killer does not match required range.  Found 0, required min: 1000150000 max: 1000159999 provider restricted: .spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed provider restricted: .spec.containers[0].securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used]",
                  Reason: "Forbidden",
                  Details: {Name: "vm-killer", Group: "", Kind: "pods", UID: "", Causes: nil, RetryAfterSeconds: 0},
                  Code: 403,
              },
          }
      to be nil

      /root/go/src/kubevirt.io/kubevirt/tests/vmlifecycle_test.go:212

```

Both `kubevirt-controller` and `kubevirt-privileged` were granted privileged scc.

**Comment by fabiand** [comment] 2018-03-15 09:53
@gbenhaim @cynepco3hahue @rmohr do you still see this test failing on the recent openshift tests?

**Comment by cynepco3hahue** [comment] 2018-03-15 10:16
@fabiand Nope, also from the error message I can see that the problem is `scc` so with correct permissions it will work and we currently set `privileged`(that not really good, but I hope we will create more strict policies in the future) to all service accounts.

**Comment by fabiand** [comment] 2018-03-15 11:07
Ack, thanks. Closing this.

**Closed by fabiand** 2018-03-15 11:07 UTC
Labels: kind/bug, topic/ci
