### ISSUE TITLE
qemu-kvm process on host consumes high cpu, much higher than observed inside guest 

### ISSUE THREAD

**Issue by chenxinlong** [kubevirt/kubevirt#10126] opened 2023-07-17 10:33 UTC
qemu-kvm process on host (using top command, and only one vm in this node)  : 
```
top - 18:21:03 up 26 days, 19:54,  1 user,  load average: 3.70, 3.40, 3.03
Tasks: 862 total,   1 running, 861 sleeping,   0 stopped,   0 zombie
%Cpu(s):  4.0 us,  1.8 sy,  0.0 ni, 93.6 id,  0.0 wa,  0.0 hi,  0.6 si,  0.0 st
MiB Mem :  64342.9 total,  39150.2 free,  19351.0 used,   5841.6 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  44337.6 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
24790 uuidd     20   0   13.0g  11.2g  21048 S 228.1  17.9  71:51.19 qemu-kvm
...
```

It is a windows guest , domain xml  as following : 
```xml
<domain type='kvm' id='1'>
  <name>hc-zone-cz-2-10291_vm-2aln7y8y</name>
  <uuid>774571ea-dbd2-536d-ae59-46a584040f6e</uuid>
  <metadata>
    <kubevirt xmlns="http://kubevirt.io">
      <uid/>
    </kubevirt>
  </metadata>
  <memory unit='KiB'>11719680</memory>
  <currentMemory unit='KiB'>11718752</currentMemory>
  <vcpu placement='static'>8</vcpu>
  <iothreads>1</iothreads>
  <sysinfo type='smbios'>
    <system>
      <entry name='manufacturer'>KubeVirt</entry>
      <entry name='product'>None</entry>
      <entry name='uuid'>774571ea-dbd2-536d-ae59-46a584040f6e</entry>
      <entry name='family'>KubeVirt</entry>
    </system>
  </sysinfo>
  <os>
    <type arch='x86_64' machine='pc-q35-rhel9.2.0'>hvm</type>
    <loader readonly='yes' secure='no' type='pflash'>/usr/share/OVMF/OVMF_CODE.secboot.fd</loader>
    <nvram template='/usr/share/OVMF/OVMF_VARS.fd'>/tmp/hc-zone-cz-2-10291_vm-2aln7y8y</nvram>
    <smbios mode='sysinfo'/>
  </os>
  <features>
    <acpi/>
  </features>
  <cpu mode='host-passthrough' check='none' migratable='on'>
    <topology sockets='1' dies='1' cores='8' threads='1'/>
  </cpu>
  <clock offset='utc'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <emulator>/usr/libexec/qemu-kvm</emulator>
    <disk type='block' device='disk' model='virtio-non-transitional'>
      <driver name='qemu' type='raw' cache='none' error_policy='stop' io='native' discard='unmap'/>
      <source dev='/dev/sysdisk' index='4'/>
      <backingStore/>
      <target dev='vda' bus='virtio'/>
      <boot order='1'/>
      <alias name='ua-sysdisk'/>
      <address type='pci' domain='0x0000' bus='0x05' slot='0x00' function='0x0'/>
    </disk>
    <disk type='file' device='disk' model='virtio-non-transitional'>
      <driver name='qemu' type='raw' cache='none' error_policy='stop' discard='unmap'/>
      <source file='/var/run/kubevirt-ephemeral-disks/cloud-init-data/hc-zone-cz-2-10291/vm-2aln7y8y/noCloud.iso' index='3'/>
      <backingStore/>
      <target dev='vdb' bus='virtio'/>
      <alias name='ua-cloudinitdisk'/>
      <address type='pci' domain='0x0000' bus='0x06' slot='0x00' function='0x0'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='qcow2' cache='none' error_policy='stop' discard='unmap'/>
      <source file='/var/run/kubevirt-ephemeral-disks/disk-data/virtiocontainerdisk/disk.qcow2' index='1'/>
      <backingStore type='file' index='2'>
        <format type='raw'/>
        <source file='/var/run/kubevirt/container-disks/disk_2.img'/>
      </backingStore>
      <target dev='sda' bus='sata'/>
      <readonly/>
      <alias name='ua-virtiocontainerdisk'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <controller type='usb' index='0' model='qemu-xhci'>
      <alias name='usb'/>
      <address type='pci' domain='0x0000' bus='0x02' slot='0x00' function='0x0'/>
    </controller>
    <controller type='scsi' index='0' model='virtio-non-transitional'>
      <alias name='scsi0'/>
      <address type='pci' domain='0x0000' bus='0x03' slot='0x00' function='0x0'/>
    </controller>
    <controller type='virtio-serial' index='0' model='virtio-non-transitional'>
      <alias name='virtio-serial0'/>
      <address type='pci' domain='0x0000' bus='0x04' slot='0x00' function='0x0'/>
    </controller>
    <controller type='sata' index='0'>
      <alias name='ide'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x1f' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pcie-root'>
      <alias name='pcie.0'/>
    </controller>
    <controller type='pci' index='1' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='1' port='0x10'/>
      <alias name='pci.1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0' multifunction='on'/>
    </controller>
    <controller type='pci' index='2' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='2' port='0x11'/>
      <alias name='pci.2'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x1'/>
    </controller>
    <controller type='pci' index='3' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='3' port='0x12'/>
      <alias name='pci.3'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x2'/>
    </controller>
    <controller type='pci' index='4' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='4' port='0x13'/>
      <alias name='pci.4'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x3'/>
    </controller>
    <controller type='pci' index='5' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='5' port='0x14'/>
      <alias name='pci.5'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x4'/>
    </controller>
    <controller type='pci' index='6' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='6' port='0x15'/>
      <alias name='pci.6'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x5'/>
    </controller>
    <controller type='pci' index='7' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='7' port='0x16'/>
      <alias name='pci.7'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x6'/>
    </controller>
    <controller type='pci' index='8' model='pcie-root-port'>
      <model name='pcie-root-port'/>
      <target chassis='8' port='0x17'/>
      <alias name='pci.8'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x7'/>
    </controller>
    <interface type='ethernet'>
      <mac address='00:00:00:12:f7:d3'/>
      <target dev='tap0' managed='no'/>
      <model type='virtio-non-transitional'/>
      <mtu size='1400'/>
      <alias name='ua-default'/>
      <rom enabled='no'/>
      <address type='pci' domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
    </interface>
    <serial type='unix'>
      <source mode='bind' path='/var/run/kubevirt-private/f78e9785-2890-45b4-8a3a-2868fadce6c5/virt-serial0'/>
      <target type='isa-serial' port='0'>
        <model name='isa-serial'/>
      </target>
      <alias name='serial0'/>
    </serial>
    <console type='unix'>
      <source mode='bind' path='/var/run/kubevirt-private/f78e9785-2890-45b4-8a3a-2868fadce6c5/virt-serial0'/>
      <target type='serial' port='0'/>
      <alias name='serial0'/>
    </console>
    <channel type='unix'>
      <source mode='bind' path='/var/run/kubevirt-private/libvirt/qemu/channel/target/domain-1-hc-zone-cz-2-10291_v/org.qemu.guest_agent.0'/>
      <target type='virtio' name='org.qemu.guest_agent.0' state='connected'/>
      <alias name='channel0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
    <input type='tablet' bus='usb'>
      <alias name='ua-tablet'/>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='mouse' bus='ps2'>
      <alias name='input1'/>
    </input>
    <input type='keyboard' bus='ps2'>
      <alias name='input2'/>
    </input>
    <graphics type='vnc' socket='/var/run/kubevirt-private/f78e9785-2890-45b4-8a3a-2868fadce6c5/virt-vnc'>
      <listen type='socket' socket='/var/run/kubevirt-private/f78e9785-2890-45b4-8a3a-2868fadce6c5/virt-vnc'/>
    </graphics>
    <audio id='1' type='none'/>
    <video>
      <model type='vga' vram='16384' heads='1' primary='yes'/>
      <alias name='video0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x0'/>
    </video>
    <memballoon model='virtio-non-transitional' freePageReporting='on'>
      <stats period='10'/>
      <alias name='balloon0'/>
      <address type='pci' domain='0x0000' bus='0x07' slot='0x00' function='0x0'/>
    </memballoon>
  </devices>
</domain>
```
But inside guest, the observed cpu usage as pic follow which is only 22% : 

![image](https://github.com/kubevirt/kubevirt/assets/9261954/d972ccb6-21c6-49b0-bd2f-b11bbb9f8bea)

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.0
- Kubernetes version (use `kubectl version`): v1.24.7
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): ubuntu 20.04
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by jdtate101** [comment] 2023-07-20 08:12
I'm also suffering the same issue. K3S 1.27, kubevirt 1.0.0 on ubuntu 20.04 LTS. qemu-KVM CPU is VERY high even when the guest is idle. QEMU is not using software emulation as hypervisor support is enabled on host.

virt-host-validate shows all ok.

when I inspect the qemu process it looks like CPU/0 is pinned at 100% and other cores are idle (8 core guest manifest)

Threads:  13 total,   1 running,  12 sleeping,   0 stopped,   0 zombie
%Cpu(s): 13.9 us, 10.5 sy,  0.0 ni, 74.0 id,  0.6 wa,  0.0 hi,  0.6 si,  0.4 st
MiB Mem :  24022.7 total,    482.5 free,  21722.3 used,   1817.9 buff/cache
MiB Swap:   8192.0 total,   8174.3 free,     17.7 used.   1854.2 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                               
3792679 syslog    20   0 9918.0m   7.5g  21104 R  92.0  32.0  65:09.86 CPU 0/KVM                                                                                                             
3792669 syslog    20   0 9918.0m   7.5g  21104 S  22.7  32.0  17:37.77 qemu-kvm                                                                                                              
3792681 syslog    20   0 9918.0m   7.5g  21104 S   3.7  32.0  14:14.97 CPU 2/KVM                                                                                                             
3792683 syslog    20   0 9918.0m   7.5g  21104 S   3.3  32.0  10:39.60 CPU 4/KVM                                                                                                             
3792685 syslog    20   0 9918.0m   7.5g  21104 S   3.3  32.0   9:11.65 CPU 6/KVM                                                                                                             
3792686 syslog    20   0 9918.0m   7.5g  21104 S   3.3  32.0   8:59.19 CPU 7/KVM                                                                                                             
3792682 syslog    20   0 9918.0m   7.5g  21104 S   3.0  32.0  10:06.05 CPU 3/KVM                                                                                                             
3792684 syslog    20   0 9918.0m   7.5g  21104 S   3.0  32.0   9:06.18 CPU 5/KVM                                                                                                             
3792680 syslog    20   0 9918.0m   7.5g  21104 S   2.7  32.0  41:14.80 CPU 1/KVM                                                                                                             
3792672 syslog    20   0 9918.0m   7.5g  21104 S   0.0  32.0   0:00.14 qemu-kvm                                                                                                              
3792674 syslog    20   0 9918.0m   7.5g  21104 S   0.0  32.0   0:00.00 IO iothread1                                                                                                          
3792678 syslog    20   0 9918.0m   7.5g  21104 S   0.0  32.0   0:00.70 IO mon_iothread                                                                                                       
3792690 syslog    20   0 9918.0m   7.5g  21104 S   0.0  32.0   0:02.57 vnc_worker 

Performance of the guest UI is VERY sluggish....it's Windows 10.

**Comment by xpivarc** [comment] 2023-08-01 16:08
@chenxinlong Could you please share per thread usage?

@jdtate101 Thank you for the report. What is the CPU usage of the guest?

Were you able to reproduce this behavior with an older version?

**Comment by chenxinlong** [comment] 2023-08-02 02:31
> @chenxinlong Could you please share per thread usage? 

```
root@kcp-hc-worker020:~# ps aux | grep qemu-kvm
root      3293  0.0  0.0   6432   720 pts/0    S+   10:27   0:00 grep --color=auto qemu-kvm
uuidd    24485  159 17.8 13991760 11778320 ?   SLl  Jul17 36123:46 /usr/libexec/qemu-kvm -name guest=hc-zone-cz-2-10291_vm-s2qh4m65,debug-threads=on -S -object {"qom-type":"secret","id":"masterKey0","format":"raw","file":"/var/run/kubevirt-private/libvirt/qemu/lib/domain-1-hc-zone-cz-2-10291_v/master-key.aes"} -blockdev {"driver":"file","filename":"/usr/share/OVMF/OVMF_CODE.secboot.fd","node-name":"libvirt-pflash0-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-pflash0-format","read-only":true,"driver":"raw","file":"libvirt-pflash0-storage"} -blockdev {"driver":"file","filename":"/tmp/hc-zone-cz-2-10291_vm-s2qh4m65","node-name":"libvirt-pflash1-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-pflash1-format","read-only":false,"driver":"raw","file":"libvirt-pflash1-storage"} -machine pc-q35-rhel9.2.0,usb=off,dump-guest-core=off,memory-backend=pc.ram,pflash0=libvirt-pflash0-format,pflash1=libvirt-pflash1-format -accel kvm -cpu host,migratable=on -m 11445 -object {"qom-type":"memory-backend-ram","id":"pc.ram","size":12000952320} -overcommit mem-lock=off -smp 8,sockets=1,dies=1,cores=8,threads=1 -object {"qom-type":"iothread","id":"iothread1"} -uuid 697c0793-bb39-5e3c-bb1c-3841fb4669a6 -smbios type=1,manufacturer=KubeVirt,product=None,uuid=697c0793-bb39-5e3c-bb1c-3841fb4669a6,family=KubeVirt -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=19,server=on,wait=off -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc -no-shutdown -boot strict=on -device {"driver":"pcie-root-port","port":16,"chassis":1,"id":"pci.1","bus":"pcie.0","multifunction":true,"addr":"0x2"} -device {"driver":"pcie-root-port","port":17,"chassis":2,"id":"pci.2","bus":"pcie.0","addr":"0x2.0x1"} -device {"driver":"pcie-root-port","port":18,"chassis":3,"id":"pci.3","bus":"pcie.0","addr":"0x2.0x2"} -device {"driver":"pcie-root-port","port":19,"chassis":4,"id":"pci.4","bus":"pcie.0","addr":"0x2.0x3"} -device {"driver":"pcie-root-port","port":20,"chassis":5,"id":"pci.5","bus":"pcie.0","addr":"0x2.0x4"} -device {"driver":"pcie-root-port","port":21,"chassis":6,"id":"pci.6","bus":"pcie.0","addr":"0x2.0x5"} -device {"driver":"pcie-root-port","port":22,"chassis":7,"id":"pci.7","bus":"pcie.0","addr":"0x2.0x6"} -device {"driver":"pcie-root-port","port":23,"chassis":8,"id":"pci.8","bus":"pcie.0","addr":"0x2.0x7"} -device {"driver":"pcie-root-port","port":24,"chassis":9,"id":"pci.9","bus":"pcie.0","addr":"0x3"} -device {"driver":"qemu-xhci","id":"usb","bus":"pci.2","addr":"0x0"} -device {"driver":"virtio-scsi-pci-non-transitional","id":"scsi0","bus":"pci.3","addr":"0x0"} -device {"driver":"virtio-serial-pci-non-transitional","id":"virtio-serial0","bus":"pci.4","addr":"0x0"} -blockdev {"driver":"host_device","filename":"/dev/sysdisk","aio":"native","node-name":"libvirt-4-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-4-format","read-only":false,"discard":"unmap","cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-4-storage"} -device {"driver":"virtio-blk-pci-non-transitional","bus":"pci.5","addr":"0x0","drive":"libvirt-4-format","id":"ua-sysdisk","bootindex":1,"write-cache":"on","werror":"stop","rerror":"stop"} -blockdev {"driver":"file","filename":"/var/run/kubevirt-ephemeral-disks/cloud-init-data/hc-zone-cz-2-10291/vm-s2qh4m65/noCloud.iso","node-name":"libvirt-3-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-3-format","read-only":false,"discard":"unmap","cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-3-storage"} -device {"driver":"virtio-blk-pci-non-transitional","bus":"pci.6","addr":"0x0","drive":"libvirt-3-format","id":"ua-cloudinitdisk","write-cache":"on","werror":"stop","rerror":"stop"} -blockdev {"driver":"file","filename":"/var/run/kubevirt/container-disks/disk_2.img","node-name":"libvirt-2-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-2-format","read-only":true,"discard":"unmap","cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-2-storage"} -blockdev {"driver":"file","filename":"/var/run/kubevirt-ephemeral-disks/disk-data/virtiocontainerdisk/disk.qcow2","node-name":"libvirt-1-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":true,"discard":"unmap","cache":{"direct":true,"no-flush":false},"driver":"qcow2","file":"libvirt-1-storage","backing":"libvirt-2-format"} -device {"driver":"ide-cd","bus":"ide.0","drive":"libvirt-1-format","id":"ua-virtiocontainerdisk","write-cache":"on","werror":"stop","rerror":"stop"} -netdev {"type":"tap","fd":"20","vhost":true,"vhostfd":"22","id":"hostua-default"} -device {"driver":"virtio-net-pci-non-transitional","host_mtu":1400,"netdev":"hostua-default","id":"ua-default","mac":"00:00:00:f3:27:c6","bus":"pci.1","addr":"0x0","romfile":""} -chardev socket,id=charserial0,fd=17,server=on,wait=off -device {"driver":"isa-serial","chardev":"charserial0","id":"serial0","index":0} -chardev socket,id=charchannel0,fd=18,server=on,wait=off -device {"driver":"virtserialport","bus":"virtio-serial0.0","nr":1,"chardev":"charchannel0","id":"channel0","name":"org.qemu.guest_agent.0"} -device {"driver":"usb-tablet","id":"ua-tablet","bus":"usb.0","port":"1"} -audiodev {"id":"audio1","driver":"none"} -vnc vnc=unix:/var/run/kubevirt-private/bf3e590b-ef21-4c6f-9e70-620775a5822d/virt-vnc,audiodev=audio1 -device {"driver":"VGA","id":"video0","vgamem_mb":16,"bus":"pcie.0","addr":"0x1"} -device {"driver":"vfio-pci","host":"0000:03:00.0","id":"ua-gpu-gpu0","bus":"pci.7","addr":"0x0"} -device {"driver":"virtio-balloon-pci-non-transitional","id":"balloon0","free-page-reporting":true,"bus":"pci.8","addr":"0x0"} -sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny -msg timestamp=on
```

press `H` to show threads in top : 
```
root@kcp-hc-worker020:~# top -p 24485
top - 10:25:39 up 42 days, 11:59,  1 user,  load average: 1.78, 1.84, 1.87
Threads:  14 total,   1 running,  13 sleeping,   0 stopped,   0 zombie
%Cpu(s):  2.0 us,  1.8 sy,  0.0 ni, 96.0 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
MiB Mem :  64342.9 total,  11643.1 free,  46733.6 used,   5966.2 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  16956.4 avail Mem

 PPID   PID nTH USER      PR  NI    VIRT    RES    SHR   SWAP S  %CPU  %MEM     TIME+ COMMAND
24249 24485  14 uuidd     20   0   13.3g  11.2g   4948      0 S  27.6  17.9   6445:29 qemu-kvm
24249 24487  14 uuidd     20   0   13.3g  11.2g   4948      0 S   0.0  17.9   0:00.90 qemu-kvm
24249 24488  14 uuidd     20   0   13.3g  11.2g   4948      0 S   0.0  17.9   0:00.00 IO iothread1
24249 24492  14 uuidd     20   0   13.3g  11.2g   4948      0 S   0.0  17.9  10:47.56 IO mon_iothread
24249 24493  14 uuidd     20   0   13.3g  11.2g   4948      0 R  37.5  17.9   8973:06 CPU 0/KVM
24249 24494  14 uuidd     20   0   13.3g  11.2g   4948      0 S  12.6  17.9   3052:54 CPU 1/KVM
24249 24495  14 uuidd     20   0   13.3g  11.2g   4948      0 S   9.0  17.9   2927:43 CPU 2/KVM
24249 24496  14 uuidd     20   0   13.3g  11.2g   4948      0 S  11.6  17.9   2981:03 CPU 3/KVM
24249 24499  14 uuidd     20   0   13.3g  11.2g   4948      0 S  13.0  17.9   3056:05 CPU 4/KVM
24249 24500  14 uuidd     20   0   13.3g  11.2g   4948      0 S  10.3  17.9   2945:47 CPU 5/KVM
24249 24501  14 uuidd     20   0   13.3g  11.2g   4948      0 S  10.6  17.9   2883:33 CPU 6/KVM
24249 24509  14 uuidd     20   0   13.3g  11.2g   4948      0 S  11.6  17.9   2843:24 CPU 7/KVM
24249 24964  14 uuidd     20   0   13.3g  11.2g   4948      0 S   0.0  17.9   0:00.00 vnc_worker
24249 63682  14 uuidd     20   0   13.3g  11.2g   4948      0 S   0.0  17.9   0:00.00 worker
```

**Comment by xpivarc** [comment] 2023-08-04 06:39
@chenxinlong 
Correct me if I am wrong but Windows shows only up to 100% usage right? In your case, that would mean the sum of CPU threads should show something like 800/5 (~5 because your guest shows 22%) which is ~150%. To me, it seems this is even below it. I am not sure I see the high consumption.

@jdtate101 are you able to reproduce your issue outside of Kubevirt (running the VM directly on the host)?

**Comment by chenxinlong** [comment] 2023-08-14 08:01
> Correct me if I am wrong but Windows shows only up to 100% usage right? In your case, that would mean the sum of CPU threads should show something like 800/5 (~5 because your guest shows 22%) which is ~150%. To me, it seems this is even below it. I am not sure I see the high consumption. 

@xpivarc  My calculations were wrong, thanks for the correction. 

Should I close this issue now ? Seems there's another problem.

**Comment by xpivarc** [comment] 2023-08-14 08:33
I would say let's close this issue if you don't see any regression. 

Other issues are better to discuss on the new issues to not mix positive/negative findings.

**Closed** 2023-08-15 01:37 UTC
Labels: kind/bug
