### ISSUE TITLE
Edit role should be able to access the kubevirt subresource

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/kubevirt#1937] opened 2019-01-15 01:28 UTC
# Bug
CI is failing in [kubevirt-ansible](https://github.com/kubevirt/kubevirt-ansible/pull/536) an rbac test that checks if the `edit` role has `get` access on the kubevirt subresource.  I confirmed this is also happening locally.  Deploy kubevirt with the kubevirt-operator, login to a user with edit permissions, then `kubectl get apiservices v1alpha2.subresources.kubevirt.io`

After adding this ClusterRole to edit, it works. 
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
    kubevirt.io: ""
  name: test-subresource
rules:
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
  - create
  - update
```

 /kind bug

**Comment by rthallisey** [comment] 2019-01-15 11:11
Ci log & [Test code](https://github.com/kubevirt/kubevirt-ansible/blob/master/tests/rbac_test.go#L190)
```
[90m------------------------------[0m
{"command":"/usr/bin/oc create -f tests/manifests/vm-cirros.yaml -n kubevirt-test-alternative","component":"","level":"error","msg":"command failed: cannot run command","output":"","pos":"utils.go:2033","reason":"exit status 1","stderr":"Error from server (Forbidden): error when creating \"tests/manifests/vm-cirros.yaml\": virtualmachines.kubevirt.io is forbidden: User \"kubevirt-test-user\" cannot create virtualmachines.kubevirt.io in the namespace \"kubevirt-test-alternative\": no RBAC policy matched\n","timestamp":"2019-01-14T23:58:49.578947Z"}
{"command":"/usr/bin/virtctl start vm-cirros -n kubevirt-test-alternative","component":"","level":"error","msg":"command failed: cannot run command","output":"Error: VirtualMachineInstance 'vm-cirros' is already running\n","pos":"utils.go:2033","reason":"exit status 1","stderr":"","timestamp":"2019-01-14T23:58:49.627072Z"}
{"command":"/usr/bin/virtctl stop vm-cirros -n kubevirt-test-alternative","component":"","level":"error","msg":"command failed: cannot run command","output":"Error updating VirtualMachine: virtualmachines.kubevirt.io \"vm-cirros\" is forbidden: User \"kubevirt-test-user\" cannot patch virtualmachines.kubevirt.io in the namespace \"kubevirt-test-alternative\": no RBAC policy matched\n","pos":"utils.go:2033","reason":"exit status 1","stderr":"","timestamp":"2019-01-14T23:58:49.695503Z"}
{"command":"/usr/bin/oc delete -f tests/manifests/vm-cirros.yaml -n kubevirt-test-alternative","component":"","level":"error","msg":"command failed: cannot run command","output":"","pos":"utils.go:2033","reason":"exit status 1","stderr":"Error from server (Forbidden): error when deleting \"tests/manifests/vm-cirros.yaml\": virtualmachines.kubevirt.io \"vm-cirros\" is forbidden: User \"kubevirt-test-user\" cannot delete virtualmachines.kubevirt.io in the namespace \"kubevirt-test-alternative\": no RBAC policy matched\n","timestamp":"2019-01-14T23:58:49.863586Z"}
```

**Comment by slintes** [comment] 2019-01-15 11:43
this looks strange, and a bit like RBAC setup is messed up at all. Do you execute `oc adm policy add-scc-to-user privileged -n kubevirt -z kubevirt-operator` in your test cluster?

**Comment by fabiand** [comment] 2019-01-15 15:05
`kubevirt-edit` role should only be able to edit kubevirt worklaod entities, not infrastructure components.

**Comment by fabiand** [comment] 2019-01-15 16:32
You have two personsas (at least) working with kubevirt:

1. Operator deployig managing kubevirt app
2. User using the kubevirt workload entities (VM, VMIRS, VMI, Migration)

the subresource (Which one actually?) is part of 1.

kubevirt-edit, *-view, (the last one) are for 2.

So I am implying that the subresource (registration I assume) is for 1.

**Comment by rthallisey** [comment] 2019-01-15 17:59
last CI run passed.  Looks like it was the missing command `oc adm policy add-scc-to-user privileged -n kubevirt -z kubevirt-operator`

**Comment by rthallisey** [comment] 2019-01-15 20:59
I spoke too soon.  I'm not sure what kubevirt-ansible is doing, but it looks like sometimes these tests are run and sometimes they're not.   I made a minor adjustment after a successful CI run, CI reran, and failed on the same test.

Logs are [here](https://jenkins.ovirt.org/job/kubevirt_kubevirt-ansible_standard-check-pr/2189//artifact/check-patch.openshift_3-11.el7.x86_64/mock_logs/script/stdout_stderr.log).

I think my local test is accurately demonstrating the failure.  Pasting it here again since my original paste had incorrect instructions.
```bash
$ oc create user test-edit
$ oc adm policy add-cluster-role-to-user edit test-edit
$ cat <<EOF | kubectl create -f -
# Create ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
    kubevirt.io: ""
  name: test-subresource
rules:
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
  - create
  - update
EOF
$ oc login -u test-edit -p test
$ oc get apiservices v1alpha3.subresources.kubevirt.io -n kubevirt
FAIL
$ oc login -u admin -p admin
$ oc adm policy add-cluster-role-to-user test-subresource test-edit
$ oc login -u test-edit -p test
$ oc get apiservices v1alpha3.subresources.kubevirt.io -n kubevirt
SUCCESS
```

**Comment by slintes** [comment] 2019-01-16 07:34
the logs looks strange, all tests are failing now?
will checkout your repo and try to reproduce locally...

**Comment by slintes** [comment] 2019-01-16 09:33
I don't understand what wrong with your cluster, but you don't need that permission for apiservices:
```
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/node01:8443/system:admin/default› 
$ oc version
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.11.0+8de5c34-71
kubernetes v1.11.0+d4cacc0
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/node01:8443/system:admin/default› 
$ oc adm policy add-scc-to-user privileged -n kubevirt -z kubevirt-operator
scc "privileged" added to: ["system:serviceaccount:kubevirt:kubevirt-operator"]
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/node01:8443/system:admin/default› 
$ export VERSION=v0.13.0
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/node01:8443/system:admin/default› 
$ kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/$VERSION/kubevirt-operator.yaml
namespace/kubevirt created
customresourcedefinition.apiextensions.k8s.io/kubevirts.kubevirt.io created
clusterrole.rbac.authorization.k8s.io/kubevirt.io:operator created
serviceaccount/kubevirt-operator created
clusterrolebinding.rbac.authorization.k8s.io/kubevirt-operator created
deployment.apps/virt-operator created
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/node01:8443/system:admin/default› 
$ kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/$VERSION/kubevirt-cr.yaml
kubevirt.kubevirt.io/kubevirt created
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/node01:8443/system:admin/default› 
$ oc get crd
NAME                                            CREATED AT
alertmanagers.monitoring.coreos.com             2018-12-09T08:24:18Z
bundlebindings.automationbroker.io              2018-12-09T08:27:02Z
bundleinstances.automationbroker.io             2018-12-09T08:27:03Z
bundles.automationbroker.io                     2018-12-09T08:27:04Z
catalogsources.operators.coreos.com             2018-12-09T08:31:55Z
clusterserviceversions.operators.coreos.com     2018-12-09T08:31:54Z
installplans.operators.coreos.com               2018-12-09T08:31:56Z
kubevirts.kubevirt.io                           2019-01-16T09:05:50Z
prometheuses.monitoring.coreos.com              2018-12-09T08:24:18Z
prometheusrules.monitoring.coreos.com           2018-12-09T08:24:18Z
servicemonitors.monitoring.coreos.com           2018-12-09T08:24:18Z
subscriptions.operators.coreos.com              2018-12-09T08:31:57Z
virtualmachineinstancemigrations.kubevirt.io    2019-01-16T09:06:06Z
virtualmachineinstancepresets.kubevirt.io       2019-01-16T09:06:06Z
virtualmachineinstancereplicasets.kubevirt.io   2019-01-16T09:06:06Z
virtualmachineinstances.kubevirt.io             2019-01-16T09:06:06Z
virtualmachines.kubevirt.io                     2019-01-16T09:06:06Z
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/node01:8443/system:admin/default› 
$ oc get apiservices v1alpha3.subresources.kubevirt.io 
NAME                                CREATED AT
v1alpha3.subresources.kubevirt.io   2019-01-16T09:06:20Z
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/node01:8443/system:admin/default› 
$ oc create user marc
user.user.openshift.io/marc created
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/node01:8443/system:admin/default› 
$ oc login -u marc -p x
Login successful.
...
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹/127-0-0-1:8443/marc› 
$ oc get apiservices v1alpha3.subresources.kubevirt.io 
No resources found.
Error from server (Forbidden): apiservices.apiregistration.k8s.io "v1alpha3.subresources.kubevirt.io" is forbidden: User "marc" cannot get apiservices.apiregistration.k8s.io at the cluster scope: no RBAC policy matched
^^ EXPECTED
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹/127-0-0-1:8443/marc› 
$ oc apply -f ./cluster/examples/vm-cirros.yaml                                                                       
Error from server (Forbidden): ...,  User "marc" cannot get virtualmachines.kubevirt.io in the namespace "default": no RBAC policy matched
^^ EXPECTED
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹/127-0-0-1:8443/marc› 
$ oc login -u admin -p x
Login successful.
...
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/127-0-0-1:8443/admin/default› 
$ oc adm policy add-cluster-role-to-user edit marc    
cluster role "edit" added: "marc"
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/127-0-0-1:8443/admin/default› 
$ oc login -u marc -p x                                
Login successful.
...
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/127-0-0-1:8443/marc/default› 
$ oc get apiservices v1alpha3.subresources.kubevirt.io 
No resources found.
Error from server (Forbidden): apiservices.apiregistration.k8s.io "v1alpha3.subresources.kubevirt.io" is forbidden: User "marc" cannot get apiservices.apiregistration.k8s.io at the cluster scope: no RBAC policy matched
^^ STILL EXPECTED
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/127-0-0-1:8443/marc/default› 
$ oc apply -f ./cluster/examples/vm-cirros.yaml        
virtualmachine.kubevirt.io/vm-cirros created
^^ WORKS NOW
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/127-0-0-1:8443/marc/default› 
$ wget https://github.com/kubevirt/kubevirt/releases/download/v0.13.0/virtctl-v0.13.0-linux-amd64
...
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/127-0-0-1:8443/marc/default› 
$ mv virtctl-v0.13.0-linux-amd64 virtctl
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/127-0-0-1:8443/marc/default› 
$ chmod +x virtctl 
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/127-0-0-1:8443/marc/default› 
$ ./virtctl start vm-cirros  
VM vm-cirros was scheduled to start
^^ ALSO WORKS NOW
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/127-0-0-1:8443/marc/default› 
$ oc get vmi
NAME        AGE       PHASE        IP        NODENAME
vm-cirros   1m        Scheduling
```
I have no clue why the VMI is not starting, but creating the VM using the CRD, and starting it using the subresource works with the edit cluster role.

**Comment by slintes** [comment] 2019-01-16 09:45
ah sorry, `start` is not a subresource. And there is a misconfiguration for the `restart` subresource. Will fix that, recheck the edit role, and check why the VMI does not start.

**Comment by slintes** [comment] 2019-01-16 10:20
Fixed RBAC for "restart" (https://github.com/kubevirt/kubevirt/pull/1942)
In the dev cluster VMIs also start, all subresources (vnc, console, restart) work without apiservices permissions:
```
$ oc create user marc
user.user.openshift.io/marc created
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/node01:8443/system:admin/default› 
$ oc adm policy add-cluster-role-to-user edit marc
cluster role "edit" added: "marc"
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/node01:8443/system:admin/default› 
$ oc login -u marc -p x
Login successful.
...
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/127-0-0-1:8443/marc/default› 
$ oc apply -f ./cluster/examples/vm-cirros.yaml
virtualmachine.kubevirt.io/vm-cirros created
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/127-0-0-1:8443/marc/default› 
$ ./virtctl start vm-cirros
VM vm-cirros was scheduled to start
NAME        AGE       PHASE     IP            NODENAME
vm-cirros   24s       Running   10.128.0.61   node01
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/127-0-0-1:8443/marc/default› 
$ ./virtctl vnc vm-cirros
{"component":"virtctl","level":"info","msg":"connection timeout: 1m0s","pos":"vnc.go:137","timestamp":"2019-01-16T10:59:57.199746Z"}
{"component":"virtctl","level":"info","msg":"remote-viewer connected in 260.237849ms","pos":"vnc.go:148","timestamp":"2019-01-16T10:59:57.459985Z"}
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/127-0-0-1:8443/marc/default› 
$ ./virtctl console vm-cirros
Successfully connected to vm-cirros console. The escape sequence is ^]

login as 'cirros' user. default password: 'gocubsgo'. use 'sudo' for root.
vm-cirros login: %                                                                                                                                              msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/127-0-0-1:8443/marc/default› 
msluiter@slintes 🎩︎  ~/go/src/kubevirt.io/kubevirt ‹master*›  ‹default/127-0-0-1:8443/marc/default› 
$ ./virtctl restart vm-cirros                 
VM vm-cirros was scheduled to restart
```
Will retry if VMIs run on a cluster where I install operator from released manifests...

**Comment by slintes** [comment] 2019-01-16 10:45
ah, VMI only didn't start because it referenced a containerdisk from dev docker registry, which was not runniung. So all fine from our point of view. Will check if I find sth in the ansible repo, which could cause problems.

**Comment by slintes** [comment] 2019-01-17 10:10
Issue in kubevirt-ansible is resolved, will close this

/close

**Closed by slintes** 2019-01-17 10:10 UTC
Labels: kind/bug
