### ISSUE TITLE
kubevirt v1.1.1 works in k8s v1.25.16 but kubevirt v1.2.0 does not work and return message "{"component":"virt-launcher-monitor","level":"error","msg":"failed to run virt-launcher","pos":"virt-launcher-monitor.go:181","reason":"fork/exec /usr/bin/virt-launcher: operation not permitted","timestamp":"2024-04-18T12:20:11.433951Z"}

### ISSUE THREAD

**Issue by wingying** [kubevirt/kubevirt#11766] opened 2024-04-22 07:54 UTC
kubevirt v1.1.1 works in k8s v1.25.16, but kubevirt v1.2.0 does not work in  k8s v1.25.16.
When creating a general vm, it reported error message: "{"component":"virt-launcher-monitor","level":"error","msg":"failed to run virt-launcher","pos":"virt-launcher-monitor.go:181","reason":"fork/exec /usr/bin/virt-launcher: operation not permitted","timestamp":"2024-04-18T12:20:11.433951Z"}

What is difference between kubevirt v1.1.1 and kubevirt v1.2.0?

K8s version:
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.16", GitCommit:"c5f43560a4f98f2af3743a59299fb79f07924373", GitTreeState:"clean", BuildDate:"2023-11-15T22:39:12Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.16", GitCommit:"c5f43560a4f98f2af3743a59299fb79f07924373", GitTreeState:"clean", BuildDate:"2023-11-15T22:28:05Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
Docker version:
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:02 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by EdDev** [comment] 2024-04-23 15:11
Kubernetes 1.26 reached EOL already.
1.27 is due to reach EOL in 2 months.

Ref: https://github.com/kubevirt/sig-release/blob/main/releases/k8s-support-matrix.md

**Comment by xpivarc** [comment] 2024-04-26 12:10
/close
Duplicate of https://github.com/kubevirt/kubevirt/issues/11784

**Closed by xpivarc** 2024-04-26 12:10 UTC
Labels: kind/bug
