### ISSUE TITLE
Our OpenAPI specification should allow to permit certain values

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#1085] opened 2018-05-28 09:15 UTC
For instance our documentation of http://www.kubevirt.io/api-reference/master/definitions.html#_v1_offlinevirtualmachinestatus is simply reflected as a string. In the go-code we use an extra type with known values plus documentation. That shoul be included in the api reference.

**Comment by fabiand** [comment] 2018-06-12 13:28
@rmohr could you explain why this is important for us?

**Comment by fabiand** [comment] 2018-06-18 08:04
https://swagger.io/docs/specification/data-models/enums/

**Comment by fabiand** [comment] 2018-06-18 08:04
This makes sense to have for a lot of fields these days:

- VM status
- Interface models
- Device models

**Comment by booxter** [comment] 2018-06-18 18:34
This issue should probably be a tracker for upstream https://github.com/kubernetes/kubernetes/issues/62325

**Comment by fabiand** [comment] 2018-06-18 20:23
Sad, it's a little out of our hands. Something we could contribute, @booxter ?

**Comment by davidvossel** [comment] 2018-06-18 20:29
> This issue should probably be a tracker for upstream kubernetes/kubernetes#62325 

i don't think openapi-gen builds our docs. I think it's just involved with the crd validation generation.

Our docs appear built by swagger-doc instead. It's something @rmohr built ```go get -u github.com/rmohr/go-swagger-utils/swagger-doc```

**Comment by booxter** [comment] 2018-06-18 21:21
@davidvossel I think there are two potentially separate issues here:

- how we document valid values;
- how we generate api definition.

For the former, indeed it seems that swagger-doc is used. I am not entirely sure if Go even allows to list all possible values for the type (it does seem that semantics of custom types is not exactly strict, and you can still set other unsupported values to "enum"-like fields), but we could probably craft something custom, by explicitly mapping valid values with types, and using the mapping to generate the list of valid values for swagger-doc field descriptions.

As for the latter, this is about api/openapi-spec/swagger.json AFAIU the format of the definition actually allows for enum types as described in https://swagger.io/docs/specification/data-models/enums/. My understanding is that to generate this definition, we leverage openapi-gen in some way (at least, that's the only place where I've found code specifically designed to parse ``omitempty`` and some other json tags), and I would imagine that the right path would be to add support for an additional tag to opengen-api that would list accepted values; and that would be used to generate the list of supported values in swagger.json.

It seems that the description and the title of this issue talks about API specification and not documentation per se, and so the goal of the issue is to tackle the latter. (If the former aspect of the issue can be tackled in the scope of this work, that's of course great too.)

Note that I still vaguely understand all the interrelationships between all the tools and auto-generated .go and .json files, and so everything above may be totally wrong. I am happy to learn how it actually works.

**Comment by fabiand** [comment] 2018-06-18 21:32
I think it's also more about documentation.

To me enum was the closest term, but if we look at the referenced upstream
issue, then it's clear that other options to signal multiple options are
also an option.

**Comment by booxter** [comment] 2018-06-19 00:13
@fabiand ok though if it's only about documentation then it has nothing to offer for https://github.com/kubevirt/kubevirt/pull/1167 in terms of enforcing values passed for model field are from the list of supported types. (I assume swagger.json is being consumed by API controller and hence would provide us with automatic enforcement on POST request if we would have enums there.)

**Comment by rmohr** [comment] 2018-06-19 08:57
The arguments collected by @sttts in https://github.com/kubernetes/kubernetes/issues/62325#issuecomment-398191970 are reasonable to not have enums in the doc. So in contrast to what I initially proposed here, let's not add enums to swagger doc. Instead we need to make sure that our validation webhook does the validations and that the current accepted values appear in the description of the swagger doc.

A way may be to extend `github.com/rmohr/go-swagger-utils/swagger-do` by adding extra documentation lines based on the enums.

**Comment by fabiand** [comment] 2018-06-21 10:42
Just to get back to what the goal was:

1. Provide documentation of the supported values for this field.
2. Ensure that a VM can only be created if the value is one of the supported ones

Point 1. needs the OpenAPI support, as we genereate the API reference from it
Point 2. could be addressed here or elsewhere i.e. in our validating adm controller

Thus the title might be a bit misleading, because both of them do not strictly require enums

**Comment by booxter** [comment] 2018-07-02 19:17
@fabiand since Point 1 would require OpenAPI support, and since it seems like we wouldn't want to adopt enums for APIs for other reasons, we should focus on Point 2 here.

As for Point 2, there are multiple ways to achieve it, including explicit checks against a list per "enum" field, like we already do for network interface models. We could build something more elaborate and abstract here, e.g. storing mapping from field to lists of valid values, and then having some generic code consume it and validate all "enum" fields, instead of having separate code for each of these cases. Is it what we are seeking here?

It's not clear if the abstract / generic way would be better (the cases are not as frequent; and you may want to have non-generic error cause messages for each of them.) So I am not sure if it makes sense to pursue this issue at all.

Note, again, that we already have a way to validate fields against a list of allowed values. (Regular "if" as in isModelSupported.) Whatever we decide to build here won't be visible to users.

**Comment by booxter** [comment] 2018-07-06 16:56
OK I am not convinced there is anything we can do better here that would not end up with a more complex code in validator webhook. I consider explicit checks against a list in code and documenting possible values in api reference with regular text (not generated from a possible values mapping) is good enough for our needs.

I am closing the issue without a code resolution. I hope everyone is ok with it.

**Closed by booxter** 2018-07-06 16:56 UTC
Labels: for/developers, for/users, kind/enhancement, kind/tracker
