### ISSUE TITLE
[Flaky test][test_id:3145]should update kubevirt from previous release to target tested release 

### ISSUE THREAD

**Issue by ksimon1** [kubevirt/kubevirt#3610] opened 2020-06-19 12:13 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Operator [rfe_id:2291][crit:high][vendor:cnv-qe@redhat.com][level:component]should update kubevirt [test_id:3145]from previous release to target tested release 

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3588/pull-kubevirt-e2e-k8s-1.18/1273368964344320000

**Comment by ashleyschuett** [comment] 2020-06-19 14:40
It looks like there is an error when stopping the VMI

```
 "reason": "SyncFailed",
            "message": "unknown error encountered sending command Ping: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix //pods/31816a74-b83c-4c13-bc5c-2de529f74ec6/volumes/kubernetes.io~empty-dir/sockets/launcher-sock: connect: no such file or directory\"",
            "source": {
                "component": "virt-handler",
                "host": "node01"
            },
```

```
            "message": "The VirtualMachineInstance crashed.",
            "source": {
                "component": "virt-handler",
                "host": "node01"
            },
```

**Comment by rmohr** [comment] 2020-06-23 12:44
/assign @davidvossel 

could you also have a look? The operator tests are more stable now but still fail quite often.

**Comment by davidvossel** [comment] 2020-06-24 20:45
I didn't get to this today, but i can take a look soon.

**Comment by qinqon** [comment] 2020-06-26 09:18
New job failing: https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3571/pull-kubevirt-e2e-k8s-1.18/1276202401245696000/build-log.txt

**Comment by davidvossel** [comment] 2020-06-26 12:47
i'm currently debugging this. I hope to have this resolved by eod

**Comment by jean-edouard** [comment] 2020-07-08 19:21
@davidvossel is this fixed now? Thanks.

**Comment by rmohr** [comment] 2020-07-09 11:22
@jean-edouard David is out this week, #3690 eliminates the  flakyness. It does nowever not fix any root cause. See the comments there.

**Comment by awels** [comment] 2021-01-21 18:55
New occurrences: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4853/pull-kubevirt-e2e-k8s-1.17/1351899458249428992 https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4853/pull-kubevirt-e2e-k8s-1.18/1351899458262011904 and https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4853/pull-kubevirt-e2e-k8s-1.19/1351899458232651776

**Comment by fgimenez** [comment] 2021-02-16 08:33
/reopen 

Happened again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1361435416300883969

**Comment by tomob** [comment] 2021-03-03 12:30
And again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4387/pull-kubevirt-e2e-k8s-1.19/1365675040699322368

/reopen

**Closed** 2021-03-17 12:46 UTC
Labels: kind/bug, lifecycle/rotten, triage/build-watcher
