### ISSUE TITLE
[rfe_id:151][crit:high][vendor:cnv-qe@redhat.com][level:component]CloudInit UserData [rfe_id:151][crit:medium][vendor:cnv-qe@redhat.com][level:component]A new VirtualMachineInstance with cloudInitConfigDrive userDataBase64 source [test_id:3178]should have cloud-init data

### ISSUE THREAD

**Issue by tiraboschi** [kubevirt/kubevirt#3749] opened 2020-07-03 10:57 UTC
/kind bug
/triage build-officer

**What happened**:
`[rfe_id:151][crit:high][vendor:cnv-qe@redhat.com][level:component]CloudInit UserData [rfe_id:151][crit:medium][vendor:cnv-qe@redhat.com][level:component]A new VirtualMachineInstance with cloudInitConfigDrive userDataBase64 source [test_id:3178]should have cloud-init data`

```
/root/go/src/kubevirt.io/kubevirt/tests/vmi_cloudinit_test.go:173
Unexpected Warning event received: testvmi4rp4z4f84hthfpj9pcw2nc4cmfqhxwg4smpx7t2kfpgbg6qp,68b21662-0060-4fe5-b4d3-acd1717dfd77: server error. command SyncVMI failed: "preparing ephemeral container disk images failed: qemu-img failed with output '': open /dev/null: operation not permitted"
Expected
    <string>: Warning
not to equal
    <string>: Warning
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:410
```

**How to reproduce it (as minimally and precisely as possible)**:
[Prow Job Link](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3684/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1278456503107325953)
**Lane**:
pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6

**Comment by rmohr** [comment] 2020-08-18 11:25
/close

Thanks @tiraboschi closing this as a duplicate of #2566

**Closed by rmohr** 2020-08-18 11:25 UTC
Labels: kind/bug, triage/build-officer

**Comment by omeryahud** [comment] 2020-09-23 06:52
@rmohr This test failed again, but with this error: `Can't connect to websocket (500): websocket: bad handshake`

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4196/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1306702732689674240
