### ISSUE TITLE
[flaky ci][test_id:4113] VM Live Migration Starting a VirtualMachineInstance with a Cirros disk should be successfully migrate with cloud-init disk with devices on the root bus

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3666] opened 2020-06-25 16:54 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

[rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system]  VM Live Migration Starting a VirtualMachineInstance  with a Cirros disk  [test_id:4113]should be successfully migrate with cloud-init disk with  devices on the root bus

/root/go/src/kubevirt.io/kubevirt/tests/migration_test.go:390 VMI testvmidlflhxlmgdbn7cdj6jrlx62j5p4xtxx88bjfbvjd4r9xv5gd unexpectedly stopped. State: Failed Expected     <bool>: true to be false /root/go/src/kubevirt.io/kubevirt/tests/utils.go:2657

link to the failing job - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1275775060711313408

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment] 2020-06-25 20:42
```
/root/go/src/kubevirt.io/kubevirt/tests/migration_test.go:390
VMI testvmidlflhxlmgdbn7cdj6jrlx62j5p4xtxx88bjfbvjd4r9xv5gd unexpectedly stopped. State: Failed
Expected
    <bool>: true
to be false
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:2657
```

when we see this, its a dupe of https://github.com/kubevirt/kubevirt/issues/3575
usually, for some reason the numbers of the artifacts doesn't correspond the number of the tests
when it happens the previous log of virt-handler shows a panic, i see the panic there, but not with the corresponding number

**Comment by oshoval** [comment] 2020-07-05 11:30
we can close it i think, since #3713 was merged.

**Comment by rmohr** [comment] 2020-07-06 07:31
/close

> we can close it i think, since #3713 was merged.

Yes https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1275775060711313408/artifacts/pods/2_kubevirt_virt-handler-ll6p7-virt-handler_previous.log shows the symptoms. Thanks.

**Closed by rmohr** 2020-07-06 07:31 UTC
Labels: kind/bug, triage/build-officer
