### ISSUE TITLE
Networking VirtualMachineInstance with disabled automatic attachment of interfaces [test_id:1774]should not configure any external interfaces

### ISSUE THREAD

**Issue by awels** [kubevirt/kubevirt#3975] opened 2020-08-11 13:24 UTC
/kind bug
/triage build-officer

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3961/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1293065443069661184

/root/go/src/kubevirt.io/kubevirt/tests/vmi_networking_test.go:511
Unexpected Warning event received: testvmi4nnwm5l4szx6c6pwwkvhdm4wbkvd8vfr7cmd5vw95x49z7wr,ab7635ae-caf0-4267-b06e-b029f57c33b4: server error. command SyncVMI failed: "LibvirtError(Code=38, Domain=0, Message='cannot open /dev/null: Operation not permitted')"
Expected
    <string>: Warning
not to equal
    <string>: Warning
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:359

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment] 2020-08-18 09:02
/close

@awels thanks.

Closing this as a duplicate of #2566

**Closed by rmohr** 2020-08-18 09:02 UTC
Labels: kind/bug, triage/build-officer
