### ISSUE TITLE
[Flaky CI] [test_id:3148][rfe_id:2291][crit:high]infrastructure management should be able to create kubevirt install with custom image tag

### ISSUE THREAD

**Issue by orenc1** [kubevirt/kubevirt#4172] opened 2020-09-13 21:37 UTC
/kind bug
/triage build-watcher

**What happened**:
A flaky CI has been found on IPv6 lane:
```
Operator [rfe_id:2291][crit:high][vendor:cnv-qe@redhat.com][level:component]infrastructure management [test_id:3148]should be able to create kubevirt install with custom image tag 
/root/go/src/kubevirt.io/kubevirt/tests/operator_test.go:617
Unexpected error:
    <*errors.errorString | 0xc0030d1630>: {
        s: "unable to listen on any of the requested ports: [{5000 8444}]",
    }
    unable to listen on any of the requested ports: [{5000 8444}]
occurred
/gimme/.gimme/versions/go1.13.14.linux.amd64/src/reflect/value.go:321
```

**Anything else we need to know?**:
**[Prow Job link](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4165/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1304654863031865345)**

**Comment by oshoval** [comment] 2020-09-14 05:49
Duplicate of
https://github.com/kubevirt/kubevirt/issues/3758
https://github.com/kubevirt/kubevirt/issues/3740
https://github.com/kubevirt/kubevirt/issues/3668

**Comment by oshoval** [comment] 2020-09-14 05:49
Duplicate of
https://github.com/kubevirt/kubevirt/issues/3758
https://github.com/kubevirt/kubevirt/issues/3740
https://github.com/kubevirt/kubevirt/issues/3668

**Closed** 2020-12-10 12:48 UTC
Labels: kind/bug, triage/build-watcher
