### ISSUE TITLE
[Flaky CI] VMIDefaults MemBalloon defaults Should override period in domain if present in virt-config [test_id:4558]with period 0

### ISSUE THREAD

**Issue by brybacki** [kubevirt/kubevirt#4181] opened 2020-09-15 15:20 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-watcher
> /kind enhancement

**What happened**:
Test failed:
```
Unexpected Warning event received: testvmijzvps8l8tpfsghh7p8jdn7p947tkxpsj97q5kpd65pb446px,1118bfaf-2d9b-4345-8d13-54cd7c3ebd84: server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: Could not access KVM kernel module: Operation not permitted\n2020-09-11T21:12:26.475521Z qemu-kvm: failed to initialize KVM: Operation not permitted')"
```
prow link:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4155/pull-kubevirt-e2e-k8s-1.17/1304503239995035648

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Might be similar to: https://github.com/kubevirt/kubevirt/issues/4180 also `operation not permitted`

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment] 2020-09-18 15:39
/close

Thanks for reporting. Duplicate of #3872. Sadly an infra issue which we so far can only make happen less often and could not identify the root cause.

**Comment by rmohr** [comment] 2020-09-18 15:39
Thanks for reporting. Duplicate of #3872. Sadly an infra issue which we so far can only make happen less often and could not identify the root cause.

**Closed by rmohr** 2020-09-18 15:39 UTC
Labels: kind/bug, triage/build-watcher
