### ISSUE TITLE
Putting build dependencies into single file

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/kubevirt#534] opened 2017-10-30 15:28 UTC
Hi,

I would like to consider to put build dependencies into single file in repository,
or create target in Makefile, to have single source what is required to build KubeVirt.

For example now we have two places in repo where are listed:
https://github.com/kubevirt/kubevirt/blob/1ea0de8f4aa1132f900dc7d6d3d6ce5bd9bf6859/.travis.yml#L20-L26
https://github.com/kubevirt/kubevirt/blob/dd76f4d76a2ee2d47d9d3467479e879f44172c5c/automation/test.sh#L64-L65
And if you count in documentation then we have three places:
https://github.com/kubevirt/kubevirt/blob/1ea0de8f4aa1132f900dc7d6d3d6ce5bd9bf6859/docs/getting-started.md#L72-L74

In additional we need to install these dependencies in kubevirt-ansible repo:
https://github.com/kubevirt-incubator/kubevirt-ansible/blob/30e0b39e5c50e353383cfaa6e5f544168b141a02/common/vars/default_vars.yml

It would be good if we could put it into single place from where it could be read out anytime we need it.

**Comment by ifireball** [comment] 2017-10-31 09:46
I suggest we make an `automation/build-artifacts.sh` script that will install all the needed dependencies and trigger builds. Then we can call it from both `test.sh` and Travis as well as make the CI system run it when typing 'ci build please' on PRs.

This will enable people to use [mock_runner.sh](ovirt-infra-docs.readthedocs.io/en/latest/CI/Using_mock_runner/) to locally get builds without worrying about setting up dependencies.

**Comment by rmohr** [comment] 2017-11-03 11:37
@lukas-bednar I have an issue with putting that stuff into the makefile, since the commands install binaries in a user BIN path.

@ifireball I don't think that mock_runner will play any role in KubeVirt (except from your attempt to support standard CI). I think that #447 is the right direction to go.

**Comment by ifireball** [comment] 2017-11-05 07:51
@rmohr how about if we make a 'docker_runner', or a 'vagrant_runner'? The trouble I have with rolling your own custom solutions like in #447 is that it makes it much harder for me to do things like have the CI system figure our that the build environment did not change and an older cached copy can be used, or control where the build environment pulls the build tools from.

**Comment by rmohr** [comment] 2017-11-06 09:56
@ifireball e.g. ` go get -u github.com/golang/dep/cmd/dep ` pulls in the latest version from dep. How do you find out that you have that version in the mock environment, without creating it?

**Comment by ifireball** [comment] 2017-11-06 12:26
@rmohr having a build/test script try to get the latest version of something is a worst-case scenario where the process is not reproducible. But even in that case we can strike a balance by caching the environment for a day or two. It usually ok to use a 2 day old version. We typically key the cache with a checksum of the dependency list file so that devs can change it to force the system to get new versions.

A better scenario is where something like 'dep's lockfile is checked into the repo. When we have that we can key the cache by checksumming it and be sure the when devs want new versions they will change it.

**Comment by rmohr** [comment] 2017-11-06 13:52
Hm, while I agree that it is not always good or useful to pull in the latest version of something, I don't find all that very appealing. I perfer much more the direction, where I can explicitly tell a system what I want to see cached. E.g. the vendor folder.

**Comment by ifireball** [comment] 2017-11-06 14:10
@rmohr you can always pull/install things from the build/test scripts. That makes them invisible as far as the caching system is concerned. 

What I'm talking about, is making sure that that build dependencies that should be cached, can be.

Breaking caching is easy, making it work in the 1st place is the hard part...

**Comment by rmohr** [comment] 2018-01-31 16:42
Fixed by #647

**Closed by rmohr** 2018-01-31 16:42 UTC
