### ISSUE TITLE
VM

### ISSUE THREAD

**Issue by garimaanurag** [kubevirt/kubevirt#5465] opened 2021-04-16 07:52 UTC
I am getting the below issue while creating the VM using Kubevirt

**Is this a BUG REPORT or FEATURE REQUEST?**:

Events:
  Type     Reason            Age   From                       Message
  ----     ------            ----  ----                       -------
  Normal   SuccessfulCreate  17s   virtualmachine-controller  Created virtual machine pod virt-launcher-testvm-dckxk
  Warning  SyncFailed        9s    virt-handler               failed to configure vmi network: Critical network error: could not retrieve pid 11642 selinux label: operation not supported
  Warning  Stopped           9s    virt-handler               The VirtualMachineInstance crashed.
  Normal   SuccessfulDelete  9s    virtualmachine-controller  Deleted virtual machine pod virt-launcher-testvm-dckxk

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ansijain** [comment] 2021-04-21 11:07
@garimaanurag Would you mind closing this issue as it is duplicate of https://github.com/kubevirt/kubevirt/issues/5466

**Closed** 2021-04-21 15:14 UTC
Labels: triage/duplicate
