### ISSUE TITLE
oc cluster up and kubevirt dont work

### ISSUE THREAD

**Issue by karmab** [kubevirt/kubevirt#1333] opened 2018-07-17 13:18 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
try to launch a vm on a 3.10 openshift origjn cluster with kubevirt 0.7.0

**What you expected to happen**:
vm running

**How to reproduce it (as minimally and precisely as possible)**:
deploy openshift with oc cluster up
deploy kubevirt >= 0.7.0
cry

**Anything else we need to know?**:
the issue seems to be missing flags for device plugin to be enabled

**Environment**:
KubeVirt version (use virtctl version):
Client Version: version.Info{GitVersion:"v0.7.0", GitCommit:"b5b91243f540739eb5db61af89b2f1e5ba449dfa", GitTreeState:"clean", BuildDate:"2018-07-04T14:16:40Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: &version.Info{GitVersion:"v0.7.0", GitCommit:"b5b91243f540739eb5db61af89b2f1e5ba449dfa", GitTreeState:"clean", BuildDate:"2018-07-04T14:16:40Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}

Kubernetes version (use kubectl version):
oc v3.10.0-rc.0+c20e215
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO
Server https://kubevirt:8443
openshift v3.10.0-rc.0+e132a20-38
kubernetes v1.10.0+b81c8f8
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by karmab** [comment] 2018-07-17 13:19
virt-handler logs

```
level=info timestamp=2018-07-16T13:07:13.320421Z pos=virt-handler.go:87 component=virt-handler hostname=localhost
level=info timestamp=2018-07-16T13:07:13.331827Z pos=vm.go:210 component=virt-handler msg="Starting virt-handler controller."
level=info timestamp=2018-07-16T13:07:13.332648Z pos=cache.go:151 component=virt-handler msg="Synchronizing domains"
level=info timestamp=2018-07-16T13:07:13.432187Z pos=device_controller.go:131 component=virt-handler msg="Starting device plugin controller"
2018/07/16 13:07:13 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix /var/lib/kubelet/device-plugins/kubelet.sock: connect: no such file or directory"; Reconnecting to {/var/lib/kubelet/device-plugins/kubelet.sock <nil>}
2018/07/16 13:07:14 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix /var/lib/kubelet/device-plugins/kubelet.sock: connect: no such file or directory"; Reconnecting to {/var/lib/kubelet/device-plugins/kubelet.sock <nil>}
2018/07/16 13:07:15 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix /var/lib/kubelet/device-plugins/kubelet.sock: connect: no such file or directory"; Reconnecting to {/var/lib/kubelet/device-plugins/kubelet.sock <nil>}
level=info timestamp=2018-07-16T13:07:18.433996Z pos=device_controller.go:125 component=virt-handler msg="kvm device plugin started"
2018/07/16 13:07:18 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix /var/lib/kubelet/device-plugins/kubelet.sock: connect: no such file or directory"; Reconnecting to {/var/lib/kubelet/device-plugins/kubelet.sock <nil>}
2018/07/16 13:07:18 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: write unix /var/lib/kubelet/device-plugins/kubevirt-kvm.sock->@: write: broken pipe"
2018/07/16 13:07:19 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix /var/lib/kubelet/device-plugins/kubelet.sock: connect: no such file or directory"; Reconnecting to {/var/lib/kubelet/device-plugins/kubelet.sock <nil>}
2018/07/16 13:07:20 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix /var/lib/kubelet/device-plugins/kubelet.sock: connect: no such file or directory"; Reconnecting to {/var/lib/kubelet/device-plugins/kubelet.sock <nil>}
2018/07/16 13:07:22 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial unix /var/lib/kubelet/device-plugins/kubelet.sock: connect: no such file or directory"; Reconnecting to {/var/lib/kubelet/device-plugins/kubelet.sock <nil>}
level=info timestamp=2018-07-16T13:07:23.440245Z pos=device_controller.go:125 component=virt-handler msg="tun device plugin started"
2018/07/16 13:07:23 grpc: Server.Serve failed to create ServerTransport:  connection error: desc = "transport: write unix /var/lib/kubelet/device-plugins/kubevirt-tun.sock->@: write: broken pipe"
```

**Comment by karmab** [comment] 2018-07-17 13:20
install was done with those steps:

```
yum -y install wget docker git bash-completion qemu-img
systemctl enable docker
sed -i "s@# INSECURE_REGISTRY=.*@INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'@" /etc/sysconfig/docker
wget -O /root/oc.tar.gz https://github.com/openshift/origin/releases/download/v3.10.0-rc.0/openshift-origin-client-tools-v3.10.0-rc.0-c20e215-linux-64bit.tar.gz
cd /root ; tar zxvf oc.tar.gz
mv /root/openshift-origin-client-tools-*/oc /usr/bin
rm -rf  /root/openshift-origin-client-tools-*
curl -L https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl -o /usr/bin/kubectl
chmod +x /usr/bin/kubectl
chmod +x /root/*sh
sed -i "s@OPTIONS=.*@OPTIONS='--insecure-registry 172.30.0.0/16'@" /etc/sysconfig/docker
systemctl start docker --ignore-dependencies
 
IP=`ip a l  eth0 | grep 'inet ' | cut -d' ' -f6 | awk -F'/' '{ print $1}'`
PUBLICNAME=$IP.xip.io
oc cluster up --public-hostname $PUBLICNAME --routing-suffix $PUBLICNAME --enable=service-catalog,router,registry,web-console,persistent-volumes,rhel-imagestreams,automation-service-broker
oc login -u system:admin
docker update --restart=always origin
oc adm policy add-cluster-role-to-user cluster-admin developer
 
VERSION="v0.7.0"
oc project kube-system
wget https://github.com/kubevirt/kubevirt/releases/download/$VERSION/kubevirt.yaml
oc adm policy add-scc-to-user privileged -z kubevirt-privileged -n kube-system
oc adm policy add-scc-to-user privileged -z kubevirt-controller -n kube-system
oc create -f kubevirt.yaml
setfacl -m user:107:rwx /root/openshift.local.clusterup/openshift.local.pv/pv*
oc adm policy add-scc-to-user privileged -z kubevirt-controller -n kube-system
```

**Comment by karmab** [comment] 2018-07-17 13:24
logs of origin pod, related to device plugin

```
Starting Device Plugin manager
E0716 06:50:12.326275   13016 eviction_manager.go:246] eviction manager: failed to get get summary stats: failed to get node info: node "localhost" not found
E0716 06:50:13.124711   13016 reflector.go:205] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://localhost:8443/api/v1/pods?fieldSelector=spec.nodeName%3Dlocalhost&limit=500&resourceVersion=0: dial tcp [::1]:8443: getsockopt: connection refused
E0716 06:50:13.125174   13016 reflector.go:205] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:461: Failed to list *v1.Node: Get https://localhost:8443/api/v1/nodes?fieldSelector=metadata.name%3Dlocalhost&limit=500&resourceVersion=0: dial tcp [::1]:8443: getsockopt: connection refused
E0716 06:50:13.126109   13016 reflector.go:205] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/kubelet/kubelet.go:452: Failed to list *v1.Service: Get https://localhost:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp [::1]:8443: getsockopt: connection refused
I0716 06:50:13.250357   13016 kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach
I0716 06:50:13.259133   13016 kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach
I0716 06:50:13.260870   13016 kubelet_node_status.go:82] Attempting to register node localhost
E0716 06:50:13.261335   13016 kubelet_node_status.go:106] Unable to register node "localhost" with API server: Post https://localhost:8443/api/v1/nodes: dial tcp [::1]:8443: getsockopt: connection refused
I0716 06:50:13.273690   13016 kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach
I0716 06:50:13.273947   13016 kubelet_node_status.go:294] Setting node annotation to enable volume controller attach/detach
```

**Comment by fabiand** [comment] 2018-07-17 13:32
Do we know if this is an issue with our DP on oc.

Or is it that oc has an issue with all DPs?

**Comment by karmab** [comment] 2018-07-17 13:32
the proper way to enable device plugin in *oc cluster up* is to add the following snippet to /etc/origin/node/node-config.yaml ( and restart origin container)

```
kubeletArguments:
 feature-gates:
 - DevicePlugins=true
```

**Comment by karmab** [comment] 2018-07-17 13:33
@fabiand issue is not related to kubevirt DP, but to DP initialization on oc cluster up

**Comment by fabiand** [comment] 2018-07-18 11:49
Thanks @karmab 

Are there any additional insights? @karmab @stu-gott 

@scollier this is something you probably want to own

**Comment by karmab** [comment] 2018-07-18 13:48
same issue as https://github.com/kubevirt/kubevirt/issues/1316

**Comment by karmab** [comment] 2018-07-25 14:08
yes

**Comment by fabiand** [comment] 2018-09-05 08:26
Fix https://github.com/openshift/origin/pull/20351

Dupe of #1316

**Closed by fabiand** 2018-09-05 08:26 UTC
Labels: for/users, kind/bug, topic/integration

**Comment by fabiand** [comment] 2018-09-06 12:13
https://github.com/kubevirt/demo/pull/71 conains a workaround: https://github.com/kubevirt/demo/pull/71/files#diff-7efff1768a14c4df93c738d9c406385aR37

**Comment by priley86** [comment] 2018-10-10 14:35
hi - can you possibly include instructions for macOS? I seem to be having some troubles on this step in the workaround mentioned above:

```
| ~/GitHub/web-ui @ dhcp129-176 (priley)
| => sudo mount -o bind $KUBELET_ROOTFS/var/lib/kubelet/device-plugins /var/lib/kubelet/device-plugins
mount: You must specify a filesystem type with -t.
```
