### ISSUE TITLE
Zen topology issue

### ISSUE THREAD

**Issue by sHaggYcaT** [kubevirt/kubevirt#1994] opened 2019-01-31 09:19 UTC
If hardware node has Zen-based CPU, then CPU topology of VMI can't be setting up correct

/kind bug

**What happened**:

VMI has incorrect amount of cores and threads. In my example:

```
Thread(s) per core:    1
Core(s) per socket:    6
Socket(s):             4
``` 

**What you expected to happen**:

VMI should has correct topology, in my example:

```
"cores": 2,
"sockets": 4,
"threads": 3
```

**How to reproduce it (as minimally and precisely as possible)**:

* Install minishift in Zen-based(I expect, this bug should exist in each Ryzen, Threadripper, Epyc) linux box. You can use this script (edit amount of vCPU if you don't have enough):
https://raw.githubusercontent.com/sHaggYcaT/kubevirt_tools_and_scripts/master/cpu_cores_threads_sockets/zen_issue/install_minishift.sh

* Next, install VM with sockets, cores and threads, example:

```
oc apply -f https://raw.githubusercontent.com/sHaggYcaT/kubevirt_tools_and_scripts/master/cpu_cores_threads_sockets/zen_issue/vm_manifest.yaml
```
* next, login in the VM's console, and check CPU topology:

```
############ debug end   ##############
  ____               ____  ____
 / __/ __ ____ ____ / __ \/ __/
/ /__ / // __// __// /_/ /\ \ 
\___//_//_/  /_/   \____/___/ 
   http://cirros-cloud.net


login as 'cirros' user. default password: 'gocubsgo'. use 'sudo' for root.
vm13-16 login: cirros
Password: 
$ lscpu 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    1
Core(s) per socket:    6
Socket(s):             4
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 1
Model name:            AMD EPYC Processor
Stepping:              2
CPU MHz:               3500.018
BogoMIPS:              7166.84
Virtualization:        AMD-V
L1d cache:             32K
L1i cache:             64K
L2 cache:              512K
L3 cache:              8192K
NUMA node0 CPU(s):     0-23
Flags:                 fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush acpi mmx fxsr sse sse2 ss ht syscall nx mmxext pdpe1gb rdtscp lm 3dnowext 3dnow rep_good nopl extd_apicid eagerfpu pni pclmulqdq monitor ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes xsave hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a 3dnowprefetch vmmcall fsgsbase bmi1 smep bmi2 erms mpx adx smap pcommit clflushopt clwb xsaveopt xgetbv1 arat
```
**Anything else we need to know?**:

Probably bug locates in the qemu/project's qemu patches, maybe in libvirt(but I think in the qemu), not in the kubevirt golang code which generates XML. 

XML file in the pod: 

https://raw.githubusercontent.com/sHaggYcaT/kubevirt_tools_and_scripts/master/cpu_cores_threads_sockets/zen_issue/vm.xml 

Has correct topology

Possible quick fix/workaround can use specific XML/libvirt syntax, example:

```
  <cpu mode='host-passthrough' check='none'>
    <topology sockets='1' cores='3' threads='2'/>
    <feature policy='require' name='topoext'/>
  </cpu>

```
It fixes topology issue in my dedicated setup of qemu and libvirt (not inside kubevirt's pod). Also possible to use check=full (also works). 

**Environment**:
- KubeVirt version (use `virtctl version`):

```virtctl version
Client Version: version.Info{GitVersion:"v0.13.2", GitCommit:"6d86849015c1f504268ba6d30a2c95bd5ccda88c", GitTreeState:"clean", BuildDate:"2019-01-24T15:12:16Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.13.2", GitCommit:"6d86849015c1f504268ba6d30a2c95bd5ccda88c", GitTreeState:"clean", BuildDate:"2019-01-24T15:12:16Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):

```kubectl version
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-01-29T15:19:24Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}```

Also I seen this bug in the kubevirt v12(not only v13). 

- VM or VMI specifications: 

see above

- Cloud provider or hardware configuration:

```lscpu 
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              24
On-line CPU(s) list: 0-23
Thread(s) per core:  2
Core(s) per socket:  12
Socket(s):           1
NUMA node(s):        2
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               1
Model name:          AMD Ryzen Threadripper 1920X 12-Core Processor
Stepping:            1
CPU MHz:             3682.791
CPU max MHz:         3500.0000
CPU min MHz:         2200.0000
BogoMIPS:            6999.14
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           64K
L2 cache:            512K
L3 cache:            8192K
NUMA node0 CPU(s):   0-5,12-17
NUMA node1 CPU(s):   6-11,18-23
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca


```

- OS (e.g. from /etc/os-release):

Fedora release 29 (Twenty Nine)
(my host system). And standard minishift

- Kernel (e.g. `uname -a`):
4.19.15-300.fc29.x86_64
(my host system). And standard minishift

- Install tools:
oc, kubevirt, virtctl, minishift

- Others:

**Comment by simon3z** [comment] 2019-01-31 14:13
cc @fabiand @MarSik

**Comment by michalskrivanek** [comment] 2019-01-31 19:08
yes, we need proper topology (missing in UI too), that's fairly easy.
But what about NUMA?

**Comment by fabiand** [comment] 2019-02-08 11:43
In other words:

You request
```
"threads": 3,
"cores": 2,
"sockets": 4,
```

but you get
```
Thread(s) per core:    1
Core(s) per socket:    6
Socket(s):             4
```

and you are saying this can be fixed by adding the `topoext` flag?

```
  <cpu mode='host-passthrough' check='none'>
    <topology sockets='1' cores='3' threads='2'/>
    <feature policy='require' name='topoext'/>
  </cpu>
```

@sHaggYcaT as @vladikr requested - could you provide the domxml to see what domxml kubevirt generates?

@berrange are you aware of an issue in qemu which could lead to this?

**Comment by sHaggYcaT** [comment] 2019-02-08 15:01
> @sHaggYcaT could you also please post the libvirt xml from the virt-launcher pod?

Already posted. Again: https://raw.githubusercontent.com/sHaggYcaT/kubevirt_tools_and_scripts/master/cpu_cores_threads_sockets/zen_issue/vm.xml

> And your original vmi yaml file?

This is it. I've uploaded, but not added link in first message:
https://raw.githubusercontent.com/sHaggYcaT/kubevirt_tools_and_scripts/master/cpu_cores_threads_sockets/zen_issue/vm_manifest.yaml

>You request

Yes,

> but you get

yes. Full lspcu:

https://raw.githubusercontent.com/sHaggYcaT/kubevirt_tools_and_scripts/master/cpu_cores_threads_sockets/zen_issue/lscpu.txt

>and you are saying this can be fixed by adding the topoext flag?

In my own qemu/libvirt in host system (outside kubevirt, just installed directly in my own Threadripper desktop) this topology issue usually fixed  if I use:

1) cpu mode='host-passthrough'
2) topoext

It's not kubevirt issue, I think. Kubevirt generates correct XML file. Just qemu or libvirt can't apply it correct for Zen host system. I can do additional research and run everything without libvirt, and using different qemu versions, is it requires?

**Comment by vladikr** [comment] 2019-02-08 18:09
I think the problem is that you are asking for 3 threads - this just doesn't exist on these cpus. I think it's just being adjusted to a better equivalent which is 4 sockets, 6 cores, and 1 thread.

@sHaggYcaT Can you please try launching a VM with 1 or 2 threads?

**Comment by sHaggYcaT** [comment] 2019-02-08 18:45
@vladikr could you please just run this test: https://github.com/kubevirt/kubevirt-ansible/pull/537
In the Zen host?
I've wrote automation. 
It generates a lot of different cases (cpu/threads/sockets/etc), and run this VMs
Sorry for dirty code. This PR still in progress. 

So, this test works in official CI (with Xeons), but always fail in the Zen desktop. 
Example from this test: 

https://github.com/sHaggYcaT/kubevirt_tools_and_scripts/blob/master/cpu_cores_threads_sockets/zen_issue/vm13-11.json
https://github.com/sHaggYcaT/kubevirt_tools_and_scripts/blob/master/cpu_cores_threads_sockets/zen_issue/vm13-11.txt

Here cores and threads confused between each other, and amount of total required vcpu really low - only 2.

My tests passed in AMD box, if I comment lines between 507 to 520 (tests for amount of cores and threads inside VM)

And if you check my script for openshift/kubevirt, you can find that it's setting up different amount of vCPUs

**Comment by berrange** [comment] 2019-02-11 10:08
On Intel CPUs you can typically fake whatever topology you want for guest CPUs and it will be visible to the guest as requested.

With AMD this isn't so simple. IIUC, the mechanism for expressing topology to the guest simply has no way to represent threads != 1 traditionally. When AMD introduced SMT for their CPUs, the topoext feature was introduced to provide a mechanism to represent threads != 1 to the guest.

The guest is using "host-passthrough", so if that host CPU supported SMT it would already have "topoext". Since it was found necessary to explicitly add "topoext" in the guest config, the host CPU must not support SMT.

IOW, I don't think I'd consider any of this a bug.

As a general point you should *NEVER* expose threads != 1  to the guest OS, unless the guest OS vCPUS have been strictly 1:1 pinned to host CPUs and those host CPUs have threads != 1. Ignoring this rule will actively harm performance of the guest.

If the guest vCPUs are allowed to float freely only cores / sockets should be used for topology.

So in any sanely configured deployment I would consider this "topoext" edge case to be a non-issue, as a host that lacks SMT should never expose SMT to a guest.

**Comment by sHaggYcaT** [comment] 2019-02-11 13:40
1) I suggest to do additional investigation and performance tests. 

2) At least we have to change a behaviour of the kubevirt(what it generates for libvirt/qemu) if the user tries to setting up threads in the Zen hardware node. I think, nobody expects confusing threads and cores inside VM.
And sometimes somebody can use custom topology not only for performance, but for some kind of test their own software - maybe somebody going to use kubevirt as development platform, and test an application which should change a behaviour if it runs in the box with different topology. 
I think, it's a good idea to ignore thread option in kubevirt users yamls, and/or add some kind of _amd_thread_forse: boolean_ option

**Closed** 2019-07-20 08:56 UTC
Labels: kind/bug, lifecycle/rotten
