### ISSUE TITLE
[sig-network] [Serial]Services bridge interface binding with a subdomain and a headless service given [test_id:1549]should be able to reach the vmi via its unique fully qualified domain name

### ISSUE THREAD

**Issue by ormergi** [kubevirt/kubevirt#4372] opened 2020-10-14 16:47 UTC
/kind bug
/triage build-watcher

**What happened**:
Flakefinder reported a flakey test:
```[Serial][rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:component]Networking VirtualMachineInstance with masquerade binding mechanism [Conformance][test_id:1780][label:masquerade_binding_connectivity]should allow regular network connection without a specific port number```
In this prow job:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4128/pull-kubevirt-e2e-k8s-1.17/1315959478050361344

**What you expected to happen**:
Test to pass 

**How to reproduce it (as minimally and precisely as possible)**:
See Prow job

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment] 2020-10-23 12:58
/close

@ormergi thanks for creating. Duplicate of #3872 and hopefully finally fixed in #4400.

```
Unexpected Warning event received: testvmizgq9c4gqht74rwm9x4vvgpb68c7w8szrxvvcmrhb6dt7lbhv,88af2959-bc9e-4ef7-a5bd-abf796795696: server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor: Could not access KVM kernel module: Operation not permitted\n2020-10-13T13:53:42.146914Z qemu-kvm: failed to initialize KVM: Operation not permitted')"
```

**Closed by rmohr** 2020-10-23 12:58 UTC
Labels: kind/bug, triage/build-watcher
