### ISSUE TITLE
Windows Example not working

### ISSUE THREAD

**Issue by christianh814** [kubevirt/kubevirt#1079] opened 2018-05-25 18:13 UTC
I created a `pvc`

```
[root@ip-172-31-0-35 ~]# oc get pvc
NAME           STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
disk-windows   Bound     pvc-d5c52988-5f0b-11e8-975f-066d0d31b564   10Gi       RWO            glusterfs-storage   1d
```

Then created the vm

```
oc create -f https://raw.githubusercontent.com/kubevirt/kubevirt/master/cluster/examples/vm-windows.yaml
```

But it's not working. I get this in the logs of the pod

```
level=info timestamp=2018-05-25T18:12:34.346791Z pos=client.go:131 component=virt-launcher msg="domain status: 5:6"
level=info timestamp=2018-05-25T18:12:34.347614Z pos=client.go:157 component=virt-launcher msg="processed event"
level=info timestamp=2018-05-25T18:12:34.352137Z pos=client.go:148 component=virt-launcher msg="Libvirt event 0 with reason 1 received"
level=error timestamp=2018-05-25T18:12:34.365580Z pos=manager.go:173 component=virt-launcher namespace=cnv name=vm-windows kind= uid=dc3b125d-6046-11e8-975f-066d0d31b564 reason="virError(Code=38, Domain=18, Message='Cannot access storage file '/var/run/kubevirt-private/vm-disks/pvcvolume/disk.img' (as uid:107, gid:107): No such file or directory')" msg="Starting the VM failed."
level=error timestamp=2018-05-25T18:12:34.365633Z pos=server.go:59 component=virt-launcher namespace=cnv name=vm-windows kind= uid=dc3b125d-6046-11e8-975f-066d0d31b564 reason="virError(Code=38, Domain=18, Message='Cannot access storage file '/var/run/kubevirt-private/vm-disks/pvcvolume/disk.img' (as uid:107, gid:107): No such file or directory')" msg="Failed to sync vm"

```

**Comment by cynepco3hahue** [comment] 2018-05-27 08:12
Windows example is the problematic one because you can not make it public for everyone. If you will want to use it, you will need to create your own windows image and attach it to VM via PVC.
See https://www.kubevirt.io/user-guide/#/workloads/virtual-machines/disks-and-volumes?id=persistentvolumeclaim for more details

**Comment by fabiand** [comment] 2018-05-28 14:17
@christianh814 a few more details in addition to what @cynepco3hahue said:
The Windows example will work, if you create a PVC (as you did) but which _also_ includes a Windows disk image.
Internally we are using this mechanism with a Windows disk image, but due to licensing we can not publicly share the image.

Please give it a try with a custom image fom your side.

But as this is not a bug, I'm now closing this issue.

**Closed by fabiand** 2018-05-28 14:17 UTC
