### ISSUE TITLE
[flakey test] Creating a VirtualMachineInstance when virt-handler is not responsive [test_id:1634]the node controller should react

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#3561] opened 2020-06-15 07:48 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

This test fails with:

```
/root/go/src/kubevirt.io/kubevirt/tests/vmi_lifecycle_test.go:609
Timed out after 180.000s.
Expected
    <v1.VirtualMachineInstancePhase>: Running
to equal
    <v1.VirtualMachineInstancePhase>: Failed
/root/go/src/kubevirt.io/kubevirt/tests/vmi_lifecycle_test.go:637
```

It was observed 5 times in last week: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2020-06-14-168h.html#row3

It happened on k8s 1.17 and 1.18 lanes.

Example failed run: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3540/pull-kubevirt-e2e-k8s-1.18/1271432801274564608

**What you expected to happen**:

It should pass.

**Comment by dhiller** [comment] 2020-06-16 07:25
Two of the failures observed from flakefinder look different than the others, i.e. they are not a timeout after 180 seconds, [one is a panic](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3534/pull-kubevirt-e2e-k8s-1.17/1270527327452794880), the other is waiting on [condition "Virthandler should be ready to work" to be true](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3546/pull-kubevirt-e2e-k8s-1.17/1271647692564467712).

So the flake count goes down to one on k8s-1.17 and 2 on k8s-1.18.

**Comment by stu-gott** [comment] 2020-06-16 17:07
The panic test run is caused by an oddball race condition that we're doing to ourselves. We have OwnerReferences for things like a VMI which has a VM as a parent. if the VM is deleted, then k8s will cascade that deletion to the VMI and possibly to container disks and the like... the next thing we do is attempt to delete the same VMI -- and then we panic on an "isNotFound" error. https://github.com/kubevirt/kubevirt/pull/3581

**Comment by rmohr** [comment] 2020-06-17 07:57
What I see is that the virt-launcher pods get actually deleted (see the deletion timestamp):

```
                "name": "virt-launcher-testvmih5b472qswtlcwlbxpk4mpj7xqln6vf62m4wl5zcj7m",
                "generateName": "virt-launcher-testvmih5b472qswtlcwlbxpk4mpj7xqln6vf62m4wl5grzx48xd864-",
                "namespace": "kubevirt-test-default",
                "selfLink": "/api/v1/namespaces/kubevirt-test-default/pods/virt-launcher-testvmih5b472qswtlcwlbxpk4mpj7xqln6vf62m4wl5zcj7m",
                "uid": "d6f8ce74-a16d-4574-9b70-c3bc00e550f1",
                "resourceVersion": "1119773",
                "creationTimestamp": "2020-06-09T19:49:37Z",
                "deletionTimestamp": "2020-06-09T19:50:33Z",
```

but the pod does not terminate. If the containers don't exit, our node-controller does not react, since this may corrupt the associated VMI.

It is very likely related to the fact that the Pod status looks like this:

```
            "status": {
                "phase": "Pending",
[...]
                "containerStatuses": [
                    {
                        "name": "compute",
                        "state": {
                            "waiting": {
                                "reason": "PodInitializing"
                            }
                        },
                        "lastState": {},
                        "ready": false,
                        "restartCount": 0,
                        "image": "registry-proxy.engineering.redhat.com/rh-osbs/container-native-virtualization-virt-launcher@sha256:03a96f4bbd4f2ea1ce089f59e47a382a7383265b0a0d04f5fb2075c0a21fcc5c",
                        "imageID": "",
                        "started": false
                    },
                    {
                        "name": "volumedisk0",
                        "state": {
                            "waiting": {
                                "reason": "PodInitializing"
                            }
                        },
                        "lastState": {},
                        "ready": false,
                        "restartCount": 0,
                        "image": "kubevirt/cirros-container-disk-demo:v0.30.0",
                        "imageID": "",
                        "started": false
                    }
```

There are known corner cases where it can take a very long time until a pod gets finally deleted. I just wonder why it is still in `Pending`. We should not mark a VMI as running when the pod is in such a state.

**Comment by ashleyschuett** [comment] 2020-06-17 12:22
If I understand correctly the issue is that the VMI is marked as "Running" which then lets the rest of the test proceed. But in this time the pod is still initializing the containers. Then when a delete request gets made it is not deleted in within the allowed timeout time since the containers can not exit due to not yet running. 

It seems like the proper fix for this flaky test case then is to see why the controller is marking the VMI as running when the pod is still `Pending`? And instead the VMI should be kept in the state of `Scheduled`?

**Comment by rmohr** [comment] 2020-06-17 12:41
> It seems like the proper fix for this flaky test case then is to see why the controller is marking the VMI as running when the pod is still `Pending`? And instead the VMI should be kept in the state of `Scheduled`?

I think, out of my head, that `Scheduled` is already only set when the Pod is started. As soon as virt-controller sets `Scheduled`, virt-handler is taking over and should try to define the VMI.

**Comment by ashleyschuett** [comment] 2020-06-17 14:53
In that case I am misunderstanding the relationship that you are pointing out in your previous comment. I'm not sure what is being pointed out then between the VMI having the status of `Running` when the `virt-launcher` pod is in the state `Pending` ?

**Comment by rmohr** [comment] 2020-06-17 14:56
> In that case I am misunderstanding the relationship that you are pointing out in your previous comment. I'm not sure what is being pointed out then between the VMI having the status of `Running` when the `virt-launcher` pod is in the state `Pending` ?

I think you got it right, I may have expressed the relationship weird. virt-handler, which is the one setting the phase to `Running` should not even react at this stage to a VMI. virt-controller explicitly hands over the VMI when the pods is ready (the containers are ready).

**Comment by ashleyschuett** [comment] 2020-06-18 09:41
So maybe this makes sense but I'm seeing some weirdness in the timestamps. 

```

**Comment by ashleyschuett** [comment] 2020-06-18 09:41
```

**Closed** 2020-06-23 10:23 UTC
Labels: kind/bug, triage/build-officer
