### ISSUE TITLE
Pass DNS search domains from pod to VM

### ISSUE THREAD

**Issue by mlsorensen** [kubevirt/kubevirt#841] opened 2018-03-23 17:25 UTC
virt-launcher should publish search domains via DHCP per pod's /etc/resolv.conf

**Comment by mlsorensen** [comment] 2018-03-23 17:26
This can be assigned to me.

**Comment by simon3z** [comment] 2018-03-30 12:56
@mlsorensen duplicate of #781 ?
cc @fabiand @rmohr

**Comment by mlsorensen** [comment] 2018-03-30 17:41
That fix was nameservers, this fix is for search domains.

**Comment by fabiand** [comment] 2018-04-04 14:10
There was a fix in #856.

**Closed by fabiand** 2018-04-04 14:10 UTC
Labels: area/launcher, good first issue, topic/network
