### ISSUE TITLE
[Flaky CI] Infrastructure [rfe_id:3187][crit:medium]Prometheus Endpoints [test_id:4137]should find one leading virt-operator and two ready 

### ISSUE THREAD

**Issue by orenc1** [kubevirt/kubevirt#4171] opened 2020-09-13 21:32 UTC
/kind bug
/triage build-watcher

**What happened**:
A flaky test as been found on k8s-1.16 lane:
```
Infrastructure [rfe_id:3187][crit:medium][vendor:cnv-qe@redhat.com][level:component]Prometheus Endpoints [test_id:4137]should find one leading virt-operator and two ready 
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:2966
Should create VMI
Unexpected error:
    <*errors.StatusError | 0xc002741220>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "Timeout: request did not complete within requested timeout",
            Reason: "Timeout",
            Details: {Name: "", Group: "", Kind: "", UID: "", Causes: nil, RetryAfterSeconds: 0},
            Code: 504,
        },
    }
    Timeout: request did not complete within requested timeout
occurred
/root/go/src/kubevirt.io/kubevirt/tests/infra_test.go:207
```

**Anything else we need to know?**:
**[Prow Job link](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4165/pull-kubevirt-e2e-k8s-1.16/1304654863027671041)**

**Comment by oshoval** [comment] 2020-09-14 05:48
Duplicate of https://github.com/kubevirt/kubevirt/issues/4157

**Closed** 2020-12-10 12:48 UTC
Labels: kind/bug, triage/build-watcher
