### ISSUE TITLE
GPU card pass through

### ISSUE THREAD

**Issue by guleng** [kubevirt/kubevirt#8138] opened 2022-07-21 06:35 UTC
I have replaced the GPU card driver with vfio PCI, and then I saw this GPU card in the virtual machine, but after installing the driver, I can't make exceptions.

Both host and virtual machine systems are Ubuntu 18.04-server
kubevirt version：v0.54.0

IOMMU is enabled：
![image](https://user-images.githubusercontent.com/40238640/180145238-5f96ce29-b621-4731-83fa-84e2265bd17e.png)

lspci -nnk -d 10de:Drive information
![image](https://user-images.githubusercontent.com/40238640/180145290-ed094d89-2ff4-4ada-b7aa-42855b70498a.png)

configuration file：
![image](https://user-images.githubusercontent.com/40238640/180145325-6aff4c84-c3a5-450b-a414-64b9b16667bb.png)

Virtual machine reference：
![image](https://user-images.githubusercontent.com/40238640/180145371-b3f413c8-30a7-4946-9c8d-e70db4f46e8f.png)

Device plugin log：
![image](https://user-images.githubusercontent.com/40238640/180145426-f8f050fe-9840-4761-bcfe-28597958d4a0.png)

I saw it in kubernetes：
![image](https://user-images.githubusercontent.com/40238640/180145459-1fb2c55c-22c4-49f2-b388-0d516fe70676.png)

Seen in the virtual machine：
![image](https://user-images.githubusercontent.com/40238640/180145490-f910faed-8bce-4d3c-9cb8-6d62c469333a.png)

View kernel information：
![image](https://user-images.githubusercontent.com/40238640/180145538-da4ed4e7-2291-405d-a1da-54338e26b4ac.png)

I don't know what happened to the problem. I've checked it repeatedly for two weeks and failed to solve it. Can you help me have a look？

**Comment by alicefr** [comment] 2022-07-22 09:19
@guleng I'm far to be an expert in GPU (ping @vladikr)

However, just a couple of questions. You are providing logs of a device plugin. Is this an external plugin? If so, you need to set `externalResourceProvider: true` and this is commented from your pics. If you don't set the conig then you are relying on virt-handler device plugin. This could explain why the GPUs are appearing correctly on the node description. Not sure if the deviceplugin and the kubevirt plugin might conflict in this case. Virt-handler logs where the gpus is located could also be very useful

**Comment by vladikr** [comment] 2022-07-22 14:37
The setup looks correct to me. KubeVirt native device plugin will not be enabled for this device if an `externalResourceProvider` is set to true. I don't think there is a collision between the device plugins. In the end, the device has been assigned to the guest just fine, but it's the Nvidia driver that is not happy.

I think the issue is that Nvidia might be blocking this driver from loading correctly on KVM.
I'd say that to diagnose the issue you may want to try assigning this device to KVM VM without KubeVirt.
Alternatively, you may try disabling the KVM signature in the guest. See explanation in: https://github.com/kubevirt/kubevirt/pull/3471

**Closed** 2022-08-05 10:05 UTC
Labels: kind/bug
