### ISSUE TITLE
virt-launcher pod fails to start because of SELinux problems

### ISSUE THREAD

**Issue by cynepco3hahue** [kubevirt/kubevirt#1205] opened 2018-06-21 14:00 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Fail to start a VM on the environment with enabled SELinux
virt-launcher log
```
level=error timestamp=2018-06-21T10:11:09.670507Z pos=server.go:154 component=virt-launcher reason="listen unix /var/run/kubevirt/sockets/kubevirt-test-default_testvmi64qfv_sock: bind: permission denied" msg="failed to create unix socket for launcher cmd service"
level=error timestamp=2018-06-21T10:11:09.670570Z pos=virt-launcher.go:81 component=virt-launcher reason="listen unix /var/run/kubevirt/sockets/kubevirt-test-default_testvmi64qfv_sock: bind: permission denied" msg="Failed to start virt-launcher cmd server"
panic: listen unix /var/run/kubevirt/sockets/kubevirt-test-default_testvmi64qfv_sock: bind: permission deniedleve
```

**What you expected to happen**:
A VM must succeed to start without any SELinux errors

**How to reproduce it (as minimally and precisely as possible)**:
- start a VM on the environment with enabled SELinux

**Anything else we need to know?**:
SELinux errors
```
ausearch -m avc --start recent
----
time->Thu Jun 21 12:03:19 2018
type=PROCTITLE msg=audit(1529582599.229:10379): proctitle="/usr/sbin/libvirtd"
type=SYSCALL msg=audit(1529582599.229:10379): arch=c000003e syscall=257 success=no exit=-13 a0=ffffffffffffff9c a1=7f164122484e a2=80001 a3=0 items=0 ppid=20653 pid=20668 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="libvirtd" exe="/usr/sbin/libvirtd" subj=system_u:system_r:container_t:s0:c67,c240 key=(null)
type=AVC msg=audit(1529582599.229:10379): avc:  denied  { write } for  pid=20668 comm="libvirtd" name="mtrr" dev="proc" ino=4026531960 scontext=system_u:system_r:container_t:s0:c67,c240 tcontext=system_u:object_r:mtrr_device_t:s0 tclass=file
----
time->Thu Jun 21 12:03:28 2018
type=PROCTITLE msg=audit(1529582608.902:10398): proctitle=2E2F766972742D6C61756E63686572002D2D71656D752D74696D656F757400356D002D2D6E616D6500766D692D6665646F7261002D2D6E616D6573706163650064656661756C74002D2D6B756265766972742D73686172652D646972002F7661722F72756E2F6B75626576697274002D2D72656164696E6573732D66696C65
type=SYSCALL msg=audit(1529582608.902:10398): arch=c000003e syscall=49 success=no exit=-13 a0=7 a1=c4201b8410 a2=34 a3=0 items=0 ppid=20578 pid=20616 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="virt-launcher" exe="/virt-launcher" subj=system_u:system_r:container_t:s0:c67,c240 key=(null)
type=AVC msg=audit(1529582608.902:10398): avc:  denied  { write } for  pid=20616 comm="virt-launcher" name="sockets" dev="tmpfs" ino=112881 scontext=system_u:system_r:container_t:s0:c67,c240 tcontext=system_u:object_r:container_var_run_t:s0 tclass=dir
```

**Environment**:
```
oc v3.10.0-rc.0+c20e215
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v3.10.0-rc.0+c20e215
kubernetes v1.10.0+b81c8f8
```

**Comment by stu-gott** [comment] 2018-06-21 17:12
As a data point, this issue really is limited to SELinux (as opposed to being compounded by other issues). I temporarily turned off SElinux enforcement on my node and my VM instance booted fine.

audit2allow suggests adding these rules:

```

module local_rules 1.0;

require {
        type mtrr_device_t;
        type container_var_run_t;
        type container_t;
        class sock_file create;
        class dir { add_name write };
        class file write;
}

#============= container_t ==============

allow container_t container_var_run_t:dir { add_name write };
allow container_t container_var_run_t:sock_file create;

allow container_t mtrr_device_t:file write;
```

However, after adding those I'm still getting a failure in the pod's logs:

```
level=info timestamp=2018-06-21T16:49:44.168216Z pos=libvirt.go:256 component=virt-launcher msg="Connecting to libvirt daemon: qemu:///system"
level=info timestamp=2018-06-21T16:49:54.171291Z pos=libvirt.go:271 component=virt-launcher msg="Connected to libvirt daemon"
level=error timestamp=2018-06-21T16:49:54.171822Z pos=server.go:154 component=virt-launcher reason="listen unix /var/run/kubevirt/sockets/default_vmi-ephemeral_sock: bind: permission denied"
msg="failed to create unix socket for launcher cmd service"              
level=error timestamp=2018-06-21T16:49:54.171901Z pos=virt-launcher.go:81 component=virt-launcher reason="listen unix /var/run/kubevirt/sockets/default_vmi-ephemeral_sock: bind: permission de
nied" msg="Failed to start virt-launcher cmd server"                     
panic: listen unix /var/run/kubevirt/sockets/default_vmi-ephemeral_sock: bind: permission denied
                                       
goroutine 1 [running]:                                       
main.startCmdServer(0xc420043f40, 0x34, 0x12800e0, 0xc4200d0290, 0xc420096de0, 0xc42087de5f)
        /root/go/src/kubevirt.io/kubevirt/cmd/virt-launcher/virt-launcher.go:82 +0x446
main.main()                                                 
        /root/go/src/kubevirt.io/kubevirt/cmd/virt-launcher/virt-launcher.go:266 +0x569
virt-launcher exited with code 2
```

**Comment by stu-gott** [comment] 2018-06-21 18:21
@cynepco3hahue I've got VM's running on my local cluster with the following type enforcement file:

```
module virt_launcher 1.0;

require {
        type mtrr_device_t;
        type var_run_t;
        type container_var_run_t;
        type container_t;
        class sock_file create;
        class dir { add_name write };
        class file { create open read write };
}

#============= container_t ==============
allow container_t container_var_run_t:dir { add_name write };
                                                                                           
allow container_t container_var_run_t:file { create open read write };
allow container_t container_var_run_t:sock_file create;
allow container_t mtrr_device_t:file write;

allow container_t var_run_t:file { open read write };
```

To compile and install these rules on a running system, put the above into a file named `virt_launcher.te`, then run:

```
checkmodule -M -m -o virt_launcher.mod virt_launcher.te
semodule_package -o virt_launcher.pp -m virt_launcher.mod
semodule -i virt_launcher.pp
```

I'm unsure of the proper way to bake the above into the openshift provider image. Is that something you can do?

**Comment by fabiand** [comment] 2018-06-21 19:09
First: I think this is a side effect (as noted before) of moving to a non-privileged pod. privileged pods probably run as a different type.

Now, the real way how to fix this is (IMHO) to get this into the policies of a distro.

@rhatdan Any recommendations how we could do this for a Kubenretes application running on Origin on Fedora and CentOS?

**Comment by rmohr** [comment] 2018-06-21 19:37
Try giving virt-launcher and virt-handler identical mcs labels: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#assign-selinux-labels-to-a-container. That a non-privileged pod can't access sockets from other pods is the default and it should work by labeling them the same way.

**Comment by cynepco3hahue** [comment] 2018-06-21 20:30
@rmohr Do not sure if it will help because in this case, all `virt-launcher` pods will have the SELinux MCS label of the virt-handler pod, in general, it means that one `virt-launcher` pod can access private resources of an other `virt-launcher` pod(at least from SELinux perspective)

**Comment by stu-gott** [comment] 2018-06-21 21:38
@fabiand I'm not sure that distro defaults makes sense here. the specific privileges needed are tailored to the exact workflow of the virt-launcher pod.

**Comment by rthallisey** [comment] 2018-06-21 21:55
These rule make sense to me based on what's happening (opening a socket).
```bash
allow container_t container_var_run_t:dir { add_name write }; 
allow container_t container_var_run_t:file { create open read write };
allow container_t container_var_run_t:sock_file create;
```

I'm not sure these are relevant unless virt-launcher needs to access something from the hosts' ```/var/run/``` or ```/proc/mtrr```.
```bash
allow container_t mtrr_device_t:file write;
allow container_t var_run_t:file { open read write };
```

**Comment by cynepco3hahue** [comment] 2018-06-22 06:07
I versus this policy, this rules relevant to `virt-launcher` containers, but they do not relevant for normal containers.
I think we must create a new label, something like container_svirt_t that will extend container_t with new rules. And apply this label on `virt-launcher` containers.

**Comment by rhatdan** [comment] 2018-06-22 11:00
If you volume mount in the socket using :z it will eliminate the AVCs for container reading and writing to the container_var_run_t socket.

I would like to see the raw AVC messages.

**Comment by rhatdan** [comment] 2018-06-22 11:06
What is the docker or preferably podman command used to start these containers?  Or are these containers running under kubernetes/CRI-O?

**Comment by cynepco3hahue** [comment] 2018-06-22 11:08
@rhatdan it OpenShift Origin 3.10 rc.0 with docker
[audit.log](https://github.com/kubevirt/kubevirt/files/2127363/audit.log)

Give me you know if you need any additional information, and thanks for your help

**Comment by rhatdan** [comment] 2018-06-22 11:30
The logs you attaches show in one, libvirtd running inside of a container.  If this is supposed to be full libvirtd running in a container, I believe you will have to run with SELinux separation turned off (Run with spc_t)

As far as virt-launcher talking to the container_var_run_t socket, I think you just need to tell the container runtime to relabel the socket as a shared content.

podman run -v /run/PATHTOSOCEKTDIR:/run/PATHTOSOCKETDIR:z ...
or 
docker run -v /run/PATHTOSOCEKTDIR:/run/PATHTOSOCKETDIR:z ...

And the container runtime will relabel the socket dir and socket to something the container can write to.

Now once you get beyond that AVC, their could be one blocking the container from talking to the other end, I would need to see that AVC as well.  If you run in permissive mode, we could see the full list of AVCs

**Comment by cynepco3hahue** [comment] 2018-06-24 06:43
@rhatdan I added `audit.log` with the run under the permissive mode, can you please take a look and say if you have some additional thoughts until then I will try to apply your above proposals.
[audit_permissive.log](https://github.com/kubevirt/kubevirt/files/2130542/audit_permissive.log)

**Comment by cynepco3hahue** [comment] 2018-06-24 08:42
@rmohr I tried to set the same SELinux `level` on the `virt-handler` and `virt-launcher` container(I tried both on pod and container level), but it did not help, maybe I did something wrong :worried: 

@rhatdan Setting `spc_t` on `virt-launcher` pod solved the SELinux problem(more correctly will say, that it will just ignore all SELinux restrictions), I think like short term solution it works fine. Thanks for your help.

**Comment by fabiand** [comment] 2018-06-24 10:07
> The logs you attaches show in one, libvirtd running inside of a container. If this is supposed to be full libvirtd running in a container, I believe you will have to run with SELinux separation turned off (Run with spc_t)

Yes, we run libvirtd in a pod, but with very reduced functionality (as in we use a limited set). Thus it's our goal to be able to run libvirt inside an un-privileged pod.
The privileged operations should be done by external components (like kubelet, device plugins or alike).

@rhatdan thus the question - how should wd configure the pod/kube considering that libvirt should be running as an un-privileged pod. And what should we do until we could remove all operations which caused selinux denials?

@nertpinx maybe also something for you, as we'll need to see what code paths still require privileges - and the question is if we can "eliminate" them.

**Comment by rhatdan** [comment] 2018-06-24 11:18
Is libvirtd going to be launching VMs?

Running your audit.log though audit2allow shows:

```
 audit2allow  -i /tmp/t1


#============= container_t ==============
allow container_t container_var_run_t:dir { add_name write };
allow container_t container_var_run_t:file { create open read write };
allow container_t container_var_run_t:sock_file create;
```
These three can be solved by mounting the container /var/run volume directory with a :Z or :z option

```
#!!!! This avc can be allowed using the boolean 'domain_kernel_load_modules'
allow container_t kernel_t:system module_request;
```
This is caused by libvirtd trying to load the kernel module, kmod="char-major-10-200" .  Is there any way for you guys to get this loaded outside of the container.


```
allow container_t mtrr_device_t:file write;
```
How does this device get into the container?  /dev/cpu/mtrr?
```
#============= dnsmasq_t ==============
allow dnsmasq_t spc_t:dbus send_msg;
```
This is allowed in the latest container-selinux policy.

**Comment by fabiand** [comment] 2018-06-24 14:08
Also CC'ing @berrange on this issue

>> This is caused by libvirtd trying to load the kernel module, kmod="char-major-10-200" . Is there any way for you guys to get this loaded outside of the container.
> 
> We can load this module under our CI, but we can not guarantee that this module will be available on user nodes

A few things we can do:

1. Understand if libvirt really needs it and why  - Do you know @nertpinx @berrange ?
2. Check for it #1023 - and leave it to the operator to load it
3. Check for it #1023 - and let launcher or DP load it (i.e. part of kvm resource)

>>   How does this device get into the container? /dev/cpu/mtrr?
> 
> I think we can mount it

1. Let's understand if libvirt really needs it and why - @nertpinx @berrange ?

> 
>>    allow dnsmasq_t spc_t:dbus send_msg;
> 
> Can you please provide exact version?

… and distro :)

In general - For all of those issues we need ot file **individual** bugs on libvirt in order to

- understand if the feature causing the issue is _really_ needed in our flows
- get them fixed in cooperation with the libvirt team

@berrange @nertpinx where would you like to see the bugs getting opened https://github.com/kubevirt/libvirt or in some bugzilal instance?

**Comment by berrange** [comment] 2018-06-25 08:37
> > This is caused by libvirtd trying to load the kernel module, kmod="char-major-10-200" . Is there any way for you guys to get this loaded outside of the container.

>     Understand if libvirt really needs it and why - Do you know @nertpinx @berrange ?

char 10,200 is /dev/net/tun. AFAIK, libvirt doesn't try to load the kernel module for this device.

> >         How does this device get into the container? /dev/cpu/mtrr?
>     Let's understand if libvirt really needs it and why - @nertpinx @berrange ?

Libvirt hasn't ever used that AFAIK

> @berrange @nertpinx where would you like to see the bugs getting opened https://github.com/kubevirt/libvirt or in some bugzilal instance?

Any libvirt bugs must go to the libvirt bug tracker - either upstream, or the distro bug tracker if using distro packages.

**Comment by rhatdan** [comment] 2018-06-25 10:23
@cynepco3hahue 
If the module is not a particular node and libvirt needs it, then libvirtd would not work, I would figure

dnsmasq fix is in container-selinux-2.66-1.el7_5

@berrange libvirtd is not loading it, it is relying on a kernel mechanims that triggeres the kernel to load the module.  We don't allow this mechanism by default from SELinux, although their is a boolean.  Our thinking  is that the Admin should load all of the modules the containers need rather then allow a rogue container cause the kernel to load a module, that might allow breakout.

The real question here that you guys have not answered is what is libvirtd purpose in the container, if it is to launch VM's, then we should not be confining it with SELinux.  We need to make sure that libvirtd can launch vm's with sVirt, and SELinux in the container will definitely prevent this.  I am not sure that libvirtd will see that SELinux is enabled either, which could cause issues.  Finally I would figure that dropped capabiltiies and seccomp rules would prevent libvirtd from doing what is can do.

**Comment by fabiand** [comment] 2018-06-26 23:55
@cynepco3hahue why was this closed?

**Comment by cynepco3hahue** [comment] 2018-06-27 06:08
@fabiand I believe it because of my W/A PR was merged.

**Comment by fabiand** [comment] 2018-07-03 13:00
Deferring this and will break it up into smaller bugs, as we've got the workaround in place and need to find a long term solution.

**Closed** 2018-09-05 08:35 UTC
Labels: area/launcher, kind/bug, topic/integration
