### ISSUE TITLE
Try to install kubevirt with kind, get Init:CrashLoopBackOff for virt-handler

### ISSUE THREAD

**Issue by vincent-pli** [kubevirt/kubevirt#9588] opened 2023-04-07 03:03 UTC
**What happened**:
Follow guide: https://kubevirt.io/quickstart_kind/
but get result like below:
```
[root@experimental ~]# kubectl -n kubevirt get po
NAME                               READY   STATUS                  RESTARTS      AGE
virt-api-7c5cfd5d95-q62zp          1/1     Running                 0             121m
virt-controller-596c94796d-bhltg   1/1     Running                 0             120m
virt-controller-596c94796d-tzwzs   1/1     Running                 0             120m
virt-handler-2g9n7                 0/1     Init:CrashLoopBackOff   8 (49s ago)   16m
virt-operator-7d87c66f76-4bs5v     1/1     Running                 0             146m
virt-operator-7d87c66f76-62qr6     1/1     Running                 0             146m
```

**Additional context**:
Here is the describe of pod virt-handler:
```
[root@experimental ~]# kubectl -n kubevirt describe po virt-handler-2g9n7
Name:                 virt-handler-2g9n7
Namespace:            kubevirt
Priority:             1000000000
Priority Class Name:  kubevirt-cluster-critical
Node:                 kind-control-plane/172.18.0.2
Start Time:           Thu, 06 Apr 2023 22:40:53 -0400
Labels:               app.kubernetes.io/component=kubevirt
                      app.kubernetes.io/managed-by=virt-operator
                      app.kubernetes.io/version=v0.60.0-alpha.0
                      controller-revision-hash=668885bdd6
                      kubevirt.io=virt-handler
                      pod-template-generation=1
                      prometheus.kubevirt.io=true
Annotations:          kubevirt.io/install-strategy-identifier: 0466738dfbacc058ab65b757864fef7b2ad2a2a7
                      kubevirt.io/install-strategy-registry: quay.io/kubevirt
                      kubevirt.io/install-strategy-version: v0.60.0-alpha.0
Status:               Pending
IP:                   10.244.0.14
IPs:
  IP:           10.244.0.14
Controlled By:  DaemonSet/virt-handler
Init Containers:
  virt-launcher:
    Container ID:  containerd://beca32a6f1087abb808fbe0389754ead0cf4d751ad6ab9fa5fd4aedd922b32c5
    Image:         quay.io/kubevirt/virt-launcher:v0.60.0-alpha.0
    Image ID:      quay.io/kubevirt/virt-launcher@sha256:854d8f210fd8e8dab9f663292f2960a61f904564cdfa29af9011dd2a58ec502b
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
    Args:
      node-labeller.sh
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 06 Apr 2023 22:56:33 -0400
      Finished:     Thu, 06 Apr 2023 22:56:33 -0400
    Ready:          False
    Restart Count:  8
    Environment:    <none>
    Mounts:
      /var/lib/kubevirt-node-labeller from node-labeller (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jphzm (ro)
Containers:
  virt-handler:
    Container ID:
    Image:         quay.io/kubevirt/virt-handler:v0.60.0-alpha.0
    Image ID:
    Port:          8443/TCP
    Host Port:     0/TCP
    Command:
      virt-handler
    Args:
      --port
      8443
      --hostname-override
      $(NODE_NAME)
      --pod-ip-address
      $(MY_POD_IP)
      --max-metric-requests
      3
      --console-server-port
      8186
      --graceful-shutdown-seconds
      315
      -v
      2
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      10m
      memory:   325Mi
    Liveness:   http-get https://:8443/healthz delay=15s timeout=10s period=45s #success=1 #failure=3
    Readiness:  http-get https://:8443/healthz delay=15s timeout=10s period=20s #success=1 #failure=3
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
      MY_POD_IP:   (v1:status.podIP)
    Mounts:
      /etc/podinfo from podinfo (rw)
      /etc/virt-handler/clientcertificates from kubevirt-virt-handler-certs (ro)
      /etc/virt-handler/servercertificates from kubevirt-virt-handler-server-certs (ro)
      /pods from kubelet-pods-shortened (rw)
      /profile-data from profile-data (rw)
      /var/lib/kubelet/device-plugins from device-plugin (rw)
      /var/lib/kubelet/pods from kubelet-pods (rw)
      /var/lib/kubevirt from virt-lib-dir (rw)
      /var/lib/kubevirt-node-labeller from node-labeller (rw)
      /var/run/kubevirt from virt-share-dir (rw)
      /var/run/kubevirt-libvirt-runtimes from libvirt-runtimes (rw)
      /var/run/kubevirt-private from virt-private-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jphzm (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kubevirt-virt-handler-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubevirt-virt-handler-certs
    Optional:    true
  kubevirt-virt-handler-server-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubevirt-virt-handler-server-certs
    Optional:    true
  profile-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  libvirt-runtimes:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt-libvirt-runtimes
    HostPathType:
  virt-share-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt
    HostPathType:
  virt-lib-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubevirt
    HostPathType:
  virt-private-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt-private
    HostPathType:
  device-plugin:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/device-plugins
    HostPathType:
  kubelet-pods-shortened:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/pods
    HostPathType:
  kubelet-pods:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/pods
    HostPathType:
  node-labeller:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubevirt-node-labeller
    HostPathType:
  podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.annotations['k8s.v1.cni.cncf.io/network-status'] -> network-status
  kube-api-access-jphzm:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 CriticalAddonsOnly op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  18m                   default-scheduler  Successfully assigned kubevirt/virt-handler-2g9n7 to kind-control-plane
  Normal   Pulled     17m (x5 over 18m)     kubelet            Container image "quay.io/kubevirt/virt-launcher:v0.60.0-alpha.0" already present on machine
  Normal   Created    17m (x5 over 18m)     kubelet            Created container virt-launcher
  Normal   Started    17m (x5 over 18m)     kubelet            Started container virt-launcher
  Warning  BackOff    3m45s (x71 over 18m)  kubelet            Back-off restarting failed container
```

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
```
[root@experimental ~]# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): 
```
[root@experimental ~]# cat /etc/os-release
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```
- Kernel (e.g. `uname -a`): 
`Linux experimental 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: N/A
- Others: 
The  log of init container: virt-launcher
```
[root@experimental ~]# kubectl -n kubevirt logs -f virt-handler-2g9n7 -c virt-launcher
x86_64
```

**Comment by dollierp** [comment] 2023-04-11 17:14
It might be caused by your node missing nested virtualization.

Since the `pipefail` option has been enabled in https://github.com/kubevirt/kubevirt/pull/9320, the InitContainer is failing (not gracefully) on the `grep` command on this line: https://github.com/kubevirt/kubevirt/blob/a1d2db5aaac691374111f5d09dda7872aadcd376/cmd/virt-launcher/node-labeller/node-labeller.sh#L11 when nested virtualization is not enabled on a node.

**Comment by EdDev** [comment] 2023-04-30 13:36
@vincent-pli , there was an issue with running KubeVirt on Kind due to https://github.com/kubernetes-sigs/kind/issues/2999 .

Per what I see it got resolved only in the latest 0.18 version.
Please confirm you tested with it.

/assign

**Comment by BenTheElder** [comment] 2023-05-02 14:58
https://github.com/kubernetes-sigs/kind/issues/2999 Was fixed by runc update in the images so just updating the kind binary won't work if you're explicitly configuring the node image. If you're using the default it will.

**Comment by xpivarc** [comment] 2023-05-02 15:08
Most probably https://github.com/kubevirt/kubevirt/commit/ec80fb48c42a30bad828edc8fdcd0417ecd3db6a would fix your issue.

**Comment by EdDev** [comment] 2023-06-04 09:23
@vincent-pli , there has been no activity on this issue for over a month now.
We are closing this issue, if the above notes did not resolved your issues on the latest release/main please re-open it (or a new one).

/close

**Closed by EdDev** 2023-06-04 09:23 UTC
Labels: kind/bug
