### ISSUE TITLE
[Flakey Test] VM Live Migration Starting a VirtualMachineInstance with an Cirros shared ISCSI PVC [test_id:3240]should be successfully with a cloud init 

### ISSUE THREAD

**Issue by shwetaap** [kubevirt/kubevirt#4004] opened 2020-08-17 20:44 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-officer

**What happened**:

[rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration Starting a VirtualMachineInstance with an Cirros shared ISCSI PVC [test_id:3240]should be successfully with a cloud init 

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3973/pull-kubevirt-e2e-k8s-1.17/1293448134076141568

**What you expected to happen**:
Test should pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment] 2020-08-18 08:52
/close

Thanks @shwetaap, closing this as a duplicate of #3872.

**Closed by rmohr** 2020-08-18 08:52 UTC
Labels: kind/bug, triage/build-officer
