### ISSUE TITLE
IOThreads IOThreads Policies [test_id:864][ref_id:2065] Should honor a mix of shared and dedicated ioThreadsPolicy

### ISSUE THREAD

**Issue by tiraboschi** [kubevirt/kubevirt#3753] opened 2020-07-03 16:18 UTC
/kind bug
/triage build-officer

**What happened**:
`IOThreads IOThreads Policies [test_id:864][ref_id:2065] Should honor a mix of shared and dedicated ioThreadsPolicy`

```
/root/go/src/kubevirt.io/kubevirt/tests/vmi_iothreads_test.go:85
Unexpected Warning event received: testvmiw6xhgk4fsg8h7668gcbsnm8lbbnbtmqx6c7d296k9s577xrv,c2f27921-31ab-4dcf-a0a5-bcf42ba2e24e: server error. command SyncVMI failed: "failed to invoke qemu-img: open /dev/null: operation not permitted"
Expected
    <string>: Warning
not to equal
    <string>: Warning
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:410
```

**How to reproduce it (as minimally and precisely as possible)**:
[Prow Job Link](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3166/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1278728546977583104)
**Lane**:
pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6

**Comment by rmohr** [comment] 2020-08-18 11:26
/close

Thanks @tiraboschi, closing this as duplicate of #2566

**Closed by rmohr** 2020-08-18 11:26 UTC
Labels: kind/bug, triage/build-officer
