### ISSUE TITLE
Starting and stopping the same VirtualMachineInstance with ephemeral registry disk [test_id:1463]should success multiple times expand_more

### ISSUE THREAD

**Issue by awels** [kubevirt/kubevirt#3976] opened 2020-08-11 13:30 UTC
/kind bug
/triage build-officer

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3961/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1293065443069661184

/root/go/src/kubevirt.io/kubevirt/tests/container_disk_test.go:110
Unexpected Warning event received: testvmibrscc5ffthnjslf4vlc97f45llhpqs4s498q88b6tqpf86wf,269e8463-a62a-4ddb-9a92-4df8f7a1f06e: server error. command SyncVMI failed: "LibvirtError(Code=38, Domain=0, Message='cannot open /dev/null: Operation not permitted')"
Expected
    <string>: Warning
not to equal
    <string>: Warning
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:359

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment] 2020-08-18 09:01
/close

@awels thanks, closing this as a duplicate of #2566.

**Closed by rmohr** 2020-08-18 09:01 UTC
Labels: kind/bug, triage/build-officer
