### ISSUE TITLE
[Flaky CI][test_id:802][rfe_id:897][crit:medium]Configurations::VirtualMachineInstance with CPU pinning with cpu pinning enabled should configure correct number of vcpus with requests.cpus

### ISSUE THREAD

**Issue by orenc1** [kubevirt/kubevirt#4170] opened 2020-09-13 21:29 UTC
/kind bug
/triage build-watcher

**What happened**:
A flaky CI test has been found on k8s-1.16 lane:
```
Configurations [rfe_id:897][crit:medium][vendor:cnv-qe@redhat.com][level:component]VirtualMachineInstance with CPU pinning with cpu pinning enabled [test_id:802]should configure correct number of vcpus with requests.cpus 
/root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:2165
Unexpected Warning event received: testvmigskz8m59x2zwzfk896hmxgm5hvxrj7wl5khjqtcr4866q2pp,31fdf846-40bf-4ec5-9009-aa7db0f898c4: failed to detect socket for containerDisk disk0: dial unix /pods/46d0de97-3511-4e71-b802-b43344be483f/volumes/kubernetes.io~empty-dir/container-disks/disk_0.sock: connect: connection refused
Expected
    <string>: Warning
not to equal
    <string>: Warning
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:357
```

**[Prow Job link](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4165/pull-kubevirt-e2e-k8s-1.16/1304654863027671041)**

**Comment by oshoval** [comment] 2020-09-14 05:49
Duplicate of
https://github.com/kubevirt/kubevirt/issues/3758
https://github.com/kubevirt/kubevirt/issues/3740
https://github.com/kubevirt/kubevirt/issues/3668

**Closed** 2020-12-10 12:48 UTC
Labels: kind/bug, triage/build-watcher
