### ISSUE TITLE
Unable to launch virt-handler v0.20.4 on CoreOS with selinux

### ISSUE THREAD

**Issue by CoRfr** [kubevirt/kubevirt#2664] opened 2019-09-04 06:08 UTC
/kind bug

**What happened**:
I started kubevirt v0.20.4 using some instructions from https://kubevirt.io/quickstart_minikube/ on a Kubernetes v1.15 cluster running on bare-metal nodes with CoreOS 1883.0.0 (~1yo ...).

**What you expected to happen**:
`virt-handler` fails to start with:
```
{"component":"virt-handler","hostname":"carmd-er-lxtb0cc47a4c27b6","level":"info","pos":"virt-handler.go:187","timestamp":"2019-09-04T06:02:51.362115Z"}
panic: failed to list labels:  

goroutine 1 [running]:
main.(*virtHandlerApp).Run(0xc0001f6000)
	cmd/virt-handler/virt-handler.go:205 +0x1ad6
main.main()
	cmd/virt-handler/virt-handler.go:457 +0x6e
```

**How to reproduce it (as minimally and precisely as possible)**:
I think running kubevirt on CoreOS should be enough, but hard to say.

**Anything else we need to know?**:
It looks like the `selinux/labels.go` is calling `semanage`, and I couldn't find it in the image.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.20.4
- Kubernetes version (use `kubectl version`): v1.15.1
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: bare-metal x86-64 servers
- OS (e.g. from /etc/os-release): CoreOS 1883.0.0 (w/ ACS patch)
- Kernel (e.g. `uname -a`): 4.18.5-coreos
- Install tools:
- Others:

**Comment by CoRfr** [comment] 2019-09-04 06:11
Also the created date of the image is not set: `"Created": "1970-01-01T00:00:00Z"`

**Comment by cynepco3hahue** [comment] 2019-09-04 06:46
@CoRfr thanks for the report, looks like we have wrong log message - https://github.com/kubevirt/kubevirt/blob/0a69f68c14f26af53d21d454dd087e038a68335e/pkg/virt-handler/selinux/labels.go#L119
we do not really print the error, so its hard to say what the problem, I will create the PR with the fix, and can you try again after it will be merged, just to see what the error?

**Comment by slintes** [comment] 2019-09-04 07:49
> Also the created date of the image is not set: `"Created": "1970-01-01T00:00:00Z"`

Works as designed, that's how bazel produces reproducable images.

**Comment by CoRfr** [comment] 2019-09-04 13:18
@slintes , sounds good, didn't knew that was expected.

@cynepco3hahue , I tried the PR #2665 and I see the following:
```
{"component":"virt-handler","hostname":"carmd-er-lxtb0cc47a4c2598","level":"info","pos":"virt-handler.go:187","timestamp":"2019-09-04T13:15:55.797845Z"}
panic: failed to list labels: out: "", error: could not find binary semanage
goroutine 1 [running]:
main.(*virtHandlerApp).Run(0xc000316100)
	cmd/virt-handler/virt-handler.go:205 +0x1ba0
main.main()
	cmd/virt-handler/virt-handler.go:461 +0x6e
```
Seems like we would need to ship `semanage` with the image, provided by package `policycoreutils-python-utils`.

**Comment by CoRfr** [comment] 2019-09-04 14:34
I'm trying to see if I can bring in `/usr/sbin/semanage` and (minimal) dependencies through an `
`rpm_image`.

**Comment by CoRfr** [comment] 2019-09-04 15:38
I was able to do that in https://github.com/CoRfr/kubevirt/commit/a1c91af9b0e658c0730cca4d86dabb216ae9d372 , but I still get `error: could not find binary semanage`.

I suspect there is some error in the lookupPath function:
```
Looking up semanage
Trying /proc/1/root/sbin/semanage
Error stat /proc/1/root/sbin/semanage: no such file or directory
Trying /proc/1/root/usr/sbin/semanage
Error stat /proc/1/root/usr/sbin/semanage: no such file or directory
Trying /proc/1/root/bin/semanage
Error stat /proc/1/root/bin/semanage: no such file or directory
Trying /proc/1/root/usr/bin/semanage
Error stat /proc/1/root/usr/bin/semanage: no such file or directory
panic: failed to list labels: out: "", error: could not find binary semanage
```

**Comment by CoRfr** [comment] 2019-09-04 16:35
Ok I had not understood that the container is running with `PidMode: host`, so that `/proc/1/root` actually refers to the init of the host (systemd for instance) and not the init of the container.

So when we are executing `getenforce`, it's actually executing the host binaries, not the container ones. There is therefore no need to ship anything else with the container.

Two things that caused problem on CoreOS:
- `getenforce` returns `Permissive`, which made the code related to SELinux execute (since it's not `Disabled`)
- CoreOS does not ship `semanage` (it's python and typically, CoreOS does not provide any python tools)

I would think the fix here is to consider SELinux as Disabled even if it's Permissive. It seems that from the application, both behave the same.

**Comment by slintes** [comment] 2019-09-04 16:47
thanks for the detailed investigation and the PR :+1:

**Comment by CoRfr** [comment] 2019-09-10 21:16
Is there anything missing from the PR?

**Comment by rmohr** [comment] 2019-09-13 08:25
@CoRfr, I played a bit with container linux. The bottom line is that we can't install policies on core os, since everything is read-only. It is not yet clear to me on how to best solve that. However, since you already have #2670 in place, I want to take in your PR. I will then rebase #2694, which will be an additional improvement, but will still only partially configure selinux on container linux.

@vladikr let's investigate independently what we can do in the future regarding to container linux and Red Hat CoreOS.

**Comment by cynepco3hahue** [comment] 2019-09-15 07:26
Maybe you can re-mount the whole system as `rw`, apply the policy and back it to `ro`, at least it worked for RHVH.

**Comment by rmohr** [comment] 2019-09-16 07:00
> Maybe you can re-mount the whole system as `rw`, apply the policy and back it to `ro`, at least it worked for RHVH.

I tried that out of curiosity. `semodule` then tries to call some executeables in libexec which are not available on core os :D

**Closed** 2019-09-16 12:49 UTC
Labels: kind/bug
