### ISSUE TITLE
openshift-ci nightly fails, it seems to be caused by outdated Kernel on hosts

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#3565] opened 2020-06-15 08:30 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Half of the tests on openshift-ci nightly fail. It seems to be caused by outdated kernel on hosts after our update to newer release of libvirt.

Test run: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-e2e-periodic-gcp-nested-virt/1272363794462412800

**Comment by dhiller** [comment] 2020-06-16 09:30
We need to change cloud provider to azure to fix this.

**Comment by dhiller** [comment] 2020-06-16 09:32
This needs to be done here: https://github.com/openshift/release/blob/master/ci-operator/config/kubevirt/kubevirt/kubevirt-kubevirt-master.yaml#L49

**Comment by ksimon1** [comment] 2020-06-19 07:51
Azure job is failing: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-e2e-periodic-azure-nested-virt/1273813341147500544

**Comment by dhiller** [comment] 2020-06-19 09:03
Due to this issue being related to failure being caused by using gcp with old kernel and move to azure mitigating that, closing this. See other issue for further investigation: kubevirt/kubevirt#3606

**Closed** 2020-06-19 09:04 UTC
Labels: build-officer, kind/bug
