### ISSUE TITLE
VM crash with network passt mode

### ISSUE THREAD

**Issue by Icarus9913** [kubevirt/kubevirt#10583] opened 2023-10-18 06:33 UTC
**What happened**:
Once I create a VM with Passt mode, it crashed. It's very strange, I tested it in 3 env. (both dual stack)
1. PC with standard kubernetes cluter (it works well)
> kubernetes version v1.25.4
> Linux virtnest-rook-ceph-1 4.18.0-193.el8.x86_64 #1 SMP Fri May 8 10:59:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

2. Kind A (it works well)
> kubernetes version: v1.27.1
> kind version: kind v0.19.0 go1.20.4 linux/amd64
> kind node kernel: Linux spider-worker 6.5.5-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Sep 23 14:20:35 EDT 2023 x86_64 GNU/Linux

3. Kind B (crash)
> kubernetes version: v1.27.1
> kind version: kind v0.16.0 go1.19.1 linux/amd64
> kind node kernel: Linux spider-control-plane 6.4.0-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jun 26 18:48:41 EDT 2023 x86_64 GNU/Linux

**What you expected to happen**:
work well

**How to reproduce it (as minimally and precisely as possible)**:
In my Kind B environment can reprocuded it 100%.

Steps:
```text
1. kind version: kind v0.16.0 go1.19.1 linux/amd64 to set up a cluster
2. In one node, create VLAN sub-interfaces just like I have `eth0` in the node, create `eth0.30` as the sub-interface
5. use the following yaml to create a VM with Passt network mode and spiderpool macvlan underlay solution (create vlan sub-interface, macvlan, veth-pair and router to let Node reaches Pod):

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: kubevirt-macvlan-vlan30
  namespace: kube-system
spec:
  config: '{"cniVersion":"0.3.1","name":"kubevirt-macvlan-vlan30","plugins":[{"vlanID":30,"type":"ifacer","interfaces":["eth0"]},{"type":"macvlan","master":"eth0.30","mode":"bridge","ipam":{"type":"spiderpool","default_ipv4_ippool":["default-v4-ippool"],"default_ipv6_ippool":["default-v6-ippool"]}},{"mode":"auto","type":"coordinator"}]}'
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-passt
  name: vm-passt
spec:
  runStrategy: Always
  template:
    metadata:
      annotations:
        v1.multus-cni.io/default-network: kube-system/kubevirt-macvlan-vlan30
      labels:
        kubevirt.io/vm: vm-passt
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          interfaces:
          - name: default
            passt: {}
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: kubevirt/cirros-container-disk-demo:latest
        name: containerdisk
```

**Additional context**:

***The key is: virt-launcher pod panic, and the corresponding virt-handler lost connections with it and restart it again and again.***
> "dial unix //pods/cb7ee872-0e9c-443f-8959-965412db385b/volumes/kubernetes.io~empty-dir/sockets/launcher-sock: connect: connection refused"

launcher error is :
> {"component":"virt-launcher","level":"fatal","msg":"failed to create libvirt configuration","pos":"podnic.go:214","reason":"exit status 1","timestamp":"2023-10-18T01:44:10.204283Z"}
panic: failed to create libvirt configuration
> {"component":"virt-launcher","level":"info","msg":"passt: No external routable interface for IPv4","pos":"generators.go:295","timestamp":"2023-10-18T01:44:10.203649Z"}
> {"component":"virt-launcher","level":"info","msg":"passt: No external routable interface for IPv6","pos":"generators.go:295","timestamp":"2023-10-18T01:44:10.203672Z"}

error logs:
I got virt-launcher logs and virt-handler logs:
[virt-launcher.log](https://github.com/kubevirt/kubevirt/files/12992964/virt-launcher.log)

[virt-handler.log](https://github.com/kubevirt/kubevirt/files/12992992/virt-handler.log)

**Environment**:
- KubeVirt version (use `virtctl version`): v1.1.0-alpha.0
- Kubernetes version (use `kubectl version`): N/A
- Kernel (e.g. `uname -a`): N/A

**Comment by Icarus9913** [comment] 2023-10-18 06:34
With 3 environment tested, 2 are good. Only one failed. I have to doubt that Passt requires for specific OS kernel?

**Comment by Icarus9913** [comment] 2023-10-18 06:40
Reference issue #9771 and #9824 , I also doubt that the virt-launcher pod paniced.

Referece issue from podman with pasta netowork failed: 
https://github.com/containers/podman/issues/20170
https://github.com/containers/podman/issues/19428

**Comment by xpivarc** [comment] 2023-10-18 08:27
What is the Kubernetes version with the 0.16 kind?

**Comment by Icarus9913** [comment] 2023-10-18 08:31
> What is the Kubernetes version with the 0.16 kind?

Hi, [Kind](https://github.com/kubernetes-sigs/kind).
run kubernetes in docker.

**Comment by ormergi** [comment] 2023-10-18 08:41
Hi, 
Please share K8S version (kind version is not enough) and Kubevirt version.
It would be more effective if you share the full log of virt-launcher and not parts of it.

It seems that the cluster CNI you use is not comply with KIND 0.16.0, and passt crush with the following errors: 
```
{"component":"virt-launcher","level":"info","msg":"passt: No external routable interface for IPv4","pos":"generators.go:295","timestamp":"2023-10-18T01:44:10.203649Z"}
{"component":"virt-launcher","level":"info","msg":"passt: No external routable interface for IPv6","pos":"generators.go:295","timestamp":"2023-10-18T01:44:10.203672Z"}
{"component":"virt-launcher","level":"info","msg":"passt: External interface not usable","pos":"generators.go:295","timestamp":"2023-10-18T01:44:10.203704Z"}
```
I suggest you to test it with k8s conformance tests before testing it with Kubevirt to verify basic networking functionalities works
https://github.com/cncf/k8s-conformance/blob/master/instructions.md

Since passt works for you on 2/3 env I dont think this is no Kubevirt bug and we should close this issue, but we can still have the discussion here.

Note that Kind 0.16 is pretty old version (year old) there has been lots of changes from this version to latest 0.20.
By quick look in 0.17 the release notes we see that the CNI that bundled with Kind has changed 
https://github.com/kubernetes-sigs/kind/releases/tag/v0.17.0 see Fixes sections, about routes.
There might be more meaningful changes since then.

**Comment by Icarus9913** [comment] 2023-10-18 08:57
Hi @ormergi , I update the description and add kubernetes version.
And you can notice the `virt-launcher.log` I uploaded is the full logs.

Yeah, I used our CNI or other else CNIs in Kind cluster. I would like to update the Kind version and test it again. 
Thanks for your reminder, I gonna test it again in a higher Kind version ENV

**Comment by Icarus9913** [comment] 2023-10-18 12:02
oh bad, I update my kind version to `v0.19.0` for my ENV KInd B but still failed. Then I try to switch the macvlan master back to `eth0` again, everything fine. 

So, `Kind A` works well with vlan sub-interface. `Kind B` only works with eth0 interface.
 
the launcher panic logs:
```text
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2023-10-18T11:52:35.816799Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-10-18T11:52:35.816918Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:545","timestamp":"2023-10-18T11:52:35.818343Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:553","timestamp":"2023-10-18T11:52:35.819122Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 9.5.0, package: 6.el9 (builder@centos.org, 2023-08-25-08:53:56, )","subcomponent":"libvirt","thread":"48","timestamp":"2023-10-18T11:52:35.850000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: vm-passt","subcomponent":"libvirt","thread":"48","timestamp":"2023-10-18T11:52:35.850000Z"}
{"component":"virt-launcher","level":"error","msg":"Unable to open /dev/kvm: No such file or directory","pos":"virHostCPUGetCPUID:1422","subcomponent":"libvirt","thread":"48","timestamp":"2023-10-18T11:52:35.850000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory","pos":"virGDBusGetSessionBus:126","subcomponent":"libvirt","thread":"48","timestamp":"2023-10-18T11:52:35.850000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get system bus connection: Could not connect: No such file or directory","pos":"virGDBusGetSystemBus:99","subcomponent":"libvirt","thread":"48","timestamp":"2023-10-18T11:52:35.850000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:561","timestamp":"2023-10-18T11:52:36.321915Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:543","timestamp":"2023-10-18T11:52:36.328622Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:75","timestamp":"2023-10-18T11:52:36.329212Z"}
{"component":"virt-launcher","level":"info","msg":"Hardware emulation device '/dev/kvm' not present. Using software emulation.","pos":"converter.go:1273","timestamp":"2023-10-18T11:52:48.109730Z"}
{"component":"virt-launcher","level":"info","msg":"In-kernel virtio-net device emulation '/dev/vhost-net' not present. Falling back to QEMU userland emulation.","pos":"converter.go:2056","timestamp":"2023-10-18T11:52:48.109864Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Executing PreStartHook on VMI pod environment","name":"vm-passt","namespace":"default","pos":"manager.go:628","timestamp":"2023-10-18T11:52:48.110431Z","uid":"f5519857-3325-4654-b62f-a61a685f789c"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Starting PreCloudInitIso hook","name":"vm-passt","namespace":"default","pos":"manager.go:649","timestamp":"2023-10-18T11:52:48.110503Z","uid":"f5519857-3325-4654-b62f-a61a685f789c"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 46 bytes to syslog","pos":"generators.go:295","timestamp":"2023-10-18T11:52:48.124066Z"}
{"component":"virt-launcher","level":"info","msg":"passt: No external routable interface for IPv4","pos":"generators.go:295","timestamp":"2023-10-18T11:52:48.124193Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 46 bytes to syslog","pos":"generators.go:295","timestamp":"2023-10-18T11:52:48.124210Z"}
{"component":"virt-launcher","level":"info","msg":"passt: No external routable interface for IPv6","pos":"generators.go:295","timestamp":"2023-10-18T11:52:48.124224Z"}
{"component":"virt-launcher","level":"info","msg":"passt: Failed to send 36 bytes to syslog","pos":"generators.go:295","timestamp":"2023-10-18T11:52:48.124239Z"}
{"component":"virt-launcher","level":"info","msg":"passt: External interface not usable","pos":"generators.go:295","timestamp":"2023-10-18T11:52:48.124251Z"}
{"component":"virt-launcher","level":"error","msg":"failed waiting for passt going to background","pos":"generators.go:310","reason":"exit status 1","timestamp":"2023-10-18T11:52:48.124811Z"}
{"component":"virt-launcher","level":"fatal","msg":"failed to create libvirt configuration","pos":"podnic.go:214","reason":"exit status 1","timestamp":"2023-10-18T11:52:48.124876Z"}
panic: failed to create libvirt configuration

goroutine 48 [running]:
kubevirt.io/client-go/log.FilteredLogger.Critical({{0x1eca980, 0xc000593aa0}, {0x1c05376, 0xd}, 0x0, 0x0, 0x2, 0x2, {0x1ecd9a0, 0xc000648980}}, ...)
	staging/src/kubevirt.io/client-go/log/log.go:334 +0x194
kubevirt.io/kubevirt/pkg/network/setup.(*podNIC).PlugPhase2(0xc0006450d0, 0x1?)
	pkg/network/setup/podnic.go:214 +0x10e
kubevirt.io/kubevirt/pkg/network/setup.(*VMNetworkConfigurator).SetupPodNetworkPhase2(0xc000430000?, 0x1ece1a0?, {0xc000648660?, 0x0?, 0x0?})
	pkg/network/setup/network.go:150 +0x168
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap.(*LibvirtDomainManager).preStartHook(0xc0001b64e0, 0xc000430000, 0xc000430580, 0x40?)
	pkg/virt-launcher/virtwrap/manager.go:681 +0x7b3
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap.(*LibvirtDomainManager).SyncVMI(0xc0001b64e0, 0xc000430000, 0x0?, 0x101?)
	pkg/virt-launcher/virtwrap/manager.go:988 +0x345
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/cmd-server.(*Launcher).SyncVirtualMachine(0xc0004142b8, {0xc000111a00?, 0x51e326?}, 0xc000111a00)
	pkg/virt-launcher/virtwrap/cmd-server/server.go:201 +0x8a
kubevirt.io/kubevirt/pkg/handler-launcher-com/cmd/v1._Cmd_SyncVirtualMachine_Handler({0x1b7f0a0?, 0xc0004142b8}, {0x1ee5560, 0xc0006514d0}, 0xc000324c60, 0x0)
	bazel-out/k8-fastbuild/bin/pkg/handler-launcher-com/cmd/v1/v1_go_proto_/kubevirt.io/kubevirt/pkg/handler-launcher-com/cmd/v1/cmd.pb.go:3136 +0x173
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000130d80, {0x1eeb7f8, 0xc000130f00}, 0xc000674100, 0xc0002cb290, 0x2d84460, 0x0)
	external/org_golang_google_grpc/server.go:1024 +0xd2f
google.golang.org/grpc.(*Server).handleStream(0xc000130d80, {0x1eeb7f8, 0xc000130f00}, 0xc000674100, 0x0)
	external/org_golang_google_grpc/server.go:1313 +0xa16
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	external/org_golang_google_grpc/server.go:722 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	external/org_golang_google_grpc/server.go:720 +0xea
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 18 with status 512","pos":"virt-launcher-monitor.go:125","timestamp":"2023-10-18T11:52:48.133501Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:143","timestamp":"2023-10-18T11:52:48.134001Z"}
```

**Comment by ormergi** [comment] 2023-10-18 12:10
I am not sure how you upgraded KIND, just incase, make sure you use kind nodes images from the same release as the binary https://github.com/kubernetes-sigs/kind/releases/tag/v0.19.0 see "New features" section "Images pre-built for this release"

**Comment by Icarus9913** [comment] 2023-10-18 12:14
Yeah, I'm sure the Kind is 0.19.0, I replaced the kind binary. Download from the github release.

```text
root@e2e-test:~ # kind version                
kind v0.19.0 go1.20.4 linux/amd64
```

**Comment by Icarus9913** [comment] 2023-10-18 16:31
I reproduced it in a new standard kubernetes cluster.
> kubernetes: v1.28.3
> Linux wk-virtual-machine 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

This cluster only has one node(master node), and one network interface ens160.

First, I tested the kubevirt bridge network with ovs-cni, steps:
```text
0. ip addr    // ens160 with 10.6.183.25/16
1. install openvswitch
2. ovs-vsctl add-br br1
3. ovs-vsctl add-port br1 eth0
4. ip addr add 10.6.183.25/16 dev br1
5. ip link set br1 up
6. ip route add default via 10.6.183.1 dev br1
```
Then I create one vm with bridge network mode + this ovs-cni, which works well.

Finally, I guess how about use the br1 as the macvlan master interface? Unfortunately, same launcher panic with same key error:
```text
{"component":"virt-launcher","level":"error","msg":"failed waiting for passt going to background","pos":"generators.go:310","reason":"exit status 1","timestamp":"2023-10-18T16:27:56.749277Z"}
{"component":"virt-launcher","level":"fatal","msg":"failed to create libvirt configuration","pos":"podnic.go:214","reason":"exit status 1","timestamp":"2023-10-18T16:27:56.749394Z"}
panic: failed to create libvirt configuration
``` 

I think this is a convenient way to reproduce it because this is a real PC standard kubernetes cluster.

**Comment by Icarus9913** [comment] 2023-10-31 02:11
Now I meet this question in a standard k8s cluster with CNI ip4-only.

Kubernetes version: `v1.26.7`
Kernal: `Linux controller-node-1 6.5.9-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 25 17:13:43 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux`

```shell
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-passt
  name: vm-passt
spec:
  runStrategy: Always
  template:
    metadata:
      annotations:
        v1.multus-cni.io/default-network: kube-system/macvlan-vlan0
      labels:
        kubevirt.io/vm: vm-passt
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          interfaces:
          - name: default
            passt: {}
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: kubevirt/cirros-container-disk-demo:latest
        name: containerdisk
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"spiderpool.spidernet.io/v2beta1","kind":"SpiderMultusConfig","metadata":{"annotations":{},"name":"macvlan-vlan0","namespace":"kube-system"},"spec":{"cniType":"macvlan","coordinator":{"mode":"auto"},"enableCoordinator":true,"macvlan":{"ippools":{"ipv4":["default-v4-ippool"]},"master":["ens192"],"vlanID":0}}}
  creationTimestamp: "2023-10-30T14:09:06Z"
  generation: 2
  name: macvlan-vlan0
  namespace: kube-system
  ownerReferences:
  - apiVersion: spiderpool.spidernet.io/v2beta1
    blockOwnerDeletion: true
    controller: true
    kind: SpiderMultusConfig
    name: macvlan-vlan0
    uid: d67ce694-bb31-4e5b-ac85-9747ba9b804f
  resourceVersion: "845077"
  uid: 01fea740-baee-4b99-a8be-bd7ac3d3acd2
spec:
  config: '{"cniVersion":"0.3.1","name":"macvlan-vlan0","plugins":[{"type":"macvlan","master":"ens192","mode":"bridge","ipam":{"type":"spiderpool","default_ipv4_ippool":["default-v4-ippool"]}}]}'
```

And just like the same logs upper: the Passt binary call with exist 1 returned and the launcher panic.
https://github.com/kubevirt/kubevirt/blob/67902ed9de43d7a0b94aa72b8fd7f48f31ca4285/pkg/network/setup/podnic.go#L214

**Comment by ormergi** [comment] 2023-10-31 09:43
I am not sure what you trying to achieve, Passt is supported for pod network only, which means Kubevirt will attach the interface that created by the **cluster** CNI to the guest (through libvirt API).
No additional configurations needed.

Here we see the VM spec template is annotated with `v1.multus-cni.io/default-network: kube-system/macvlan-vlan0` and the corresponding net-attach-def.
This annotation will be added the VM pod as well, I am not sure what it trigger,  but it might be the root cause why the VM wont boot due to the error you mention.

I recall that in previous iteration the original error was passt not being able to use the given interface, that is the one that created in the pod by the cluster CNI.

**Comment by Icarus9913** [comment] 2023-10-31 10:58
> I am not sure what you trying to achieve, Passt is supported for pod network only, which means Kubevirt will attach the interface that created by the **cluster** CNI to the guest (through libvirt API). No additional configurations needed.
> 
> Here we see the VM spec template is annotated with `v1.multus-cni.io/default-network: kube-system/macvlan-vlan0` and the corresponding net-attach-def. This annotation will be added the VM pod as well, I am not sure what it trigger, but it might be the root cause why the VM wont boot due to the error you mention.
> 
> I recall that in previous iteration the original error was passt not being able to use the given interface, that is the one that created in the pod by the cluster CNI.

I just remove the net-attach-def annotation and set the `macvlan-vlan0` as my **cluster CNI** to test it, but it failed either.
Actually, with this annotation to specify the net-attach-def resources, there are some environment OK but some failed. As the upper logs shows and many test I did. And I still can not find the rules.

All in all, all crashed logs with Passt binary `exit 1` return.

**Comment by Icarus9913** [comment] 2024-03-11 11:19
I'll try to use the new kubevirt `passt binding plugin` to test in these clusters.

**Comment by Icarus9913** [comment] 2024-03-13 07:27
new progress:

I got 2 cluster pure kubernetes cluster in metal machine that met the upper `passt crash` before  and update the kubevirt to v1.2.0 to test the `passt-network-binding-plugin`.

The first one is good and I also exec into the vm and tested the network connectivity well.

The second one shows `NotReady`. 
And here's the VMI events:
```text
  Normal   SuccessfulCreate  13s              virtualmachine-controller  Created virtual machine pod virt-launcher-vm-net-binding-passt-rwqrb
  Warning  SyncFailed        5s               virt-handler               server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=0, Message='internal error: Child process (/usr/bin/passt --one-off --socket /var/run/libvirt/qemu/run/passt/1-default_vm-net-bindi-ua-passtnet.socket --mac-addr 52:54:00:d3:39:0e --pid /var/run/libvirt/qemu/run/passt/1-default_vm-net-bindi-ua-passtnet-passt.pid --interface eth0 --log-file /var/run/kubevirt/passt.log --tcp-ports 80) unexpected exit status 1: Template interface: eth0 (IPv4)\nMAC:\n    host: 52:54:00:d3:39:0e\nDHCP:\n    assign: 10.6.183.26\n    mask: 255.255.0.0\n    router: 10.6.0.1\nDNS:\n    10.96.0.10\nDNS search list:\n    default.svc.cluster.local\n    svc.cluster.local\n    cluster.local\nUNIX domain socket bound at /var/run/libvirt/qemu/run/passt/1-default_vm-net-bindi-ua-passtnet.socket\n\nYou can now start qemu (>= 7.2, with commit 13c6be96618c):\n    kvm ... -device virtio-net-pci,netdev=s -netdev stream,id=s,server=off,addr.type=unix,addr.path=/var/run/libvirt/qemu/run/passt/1-default_vm-net-bindi-ua-passtnet.socket\nor qrap, for earlier qemu versions:\n    ./qrap 5 kvm ... -net socket,fd=5 -net nic,model=virtio\nmount /: Permission denied\nFailed to sandbox process, exiting\n')"
```

Here's the VMI Pod logs:
[vm.log](https://github.com/kubevirt/kubevirt/files/14583951/vm.log)

**Comment by Icarus9913** [comment] 2024-03-18 09:43
> @Icarus9913 So you have two k8s cluster, on one cluster the VM run just fine, and on the other cluster it doesnt? (due to the mentioned error) Note that this time there is this error:
> 
> ```
> {"component":"virt-launcher","level":"info","msg":"mount /: Permission denied","subcomponent":"libvirt","timestamp":"2024-03-13T07:21:42.489912Z"}
> ```
> 
> Could you please share what are the differences between these clusters? Which Kubevirt version each cluster runs? Does Kubevirt config is different on each cluster?
> 
> Do you see this error only when you try to update Kubevirt to v1.2.0? If so, does it fails on both clusters? what is the version you try to upgrade **from**?

@ormergi Hello!

Briefly, 2 clusters (both single Node). The ubuntu runs `passt-network-binding-plugin` bad.
1. ubuntu
 - kernel `5.15.0-91-generic`
 - k8s version `v1.28.3`

2. centos 7.9
 - kernel `5.4.271-1.el7.elrepo.x86_64`
 - k8s version `v1.27.5`

These 2 clusters were installing kubevirt v1.2.0 from clean. No upgrade operation. (I just cleaned up the previous v1.0.0  kubevirt, I cleaned up the vm, cleaned up the CRD, cleaned up the operator. How I installed before, all I cleaned up. So I think I was installing kubevirt v1.2.0 in a pure clean cluster.)

And I'm 100% make sure these 2 kubevirt installation configurations are same.

**Closed** 2024-04-17 18:27 UTC
Labels: kind/bug, sig/network, lifecycle/rotten
