### ISSUE TITLE
[Flaky CI][Serial]VMIDefaults Disk defaults [test_id:4115]Should be applied to VMIs

### ISSUE THREAD

**Issue by borod108** [kubevirt/kubevirt#4931] opened 2021-01-29 12:25 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/triage build-watcher
/kind bug

**What happened**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4885/pull-kubevirt-e2e-k8s-1.18/1354225912467427328

```
tests/vmidefaults_test.go:78
Unexpected error:
    <*errors.StatusError | 0xc0038f32c0>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "Internal error occurred: failed calling webhook \"virtualmachineinstances-mutator.kubevirt.io\": Post https://virt-api.kubevirt.svc:443/virtualmachineinstances-mutate?timeout=30s: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kubevirt.io\")",
            Reason: "InternalError",
            Details: {
                Name: "",
                Group: "",
                Kind: "",
                UID: "",
                Causes: [
                    {
                        Type: "",
                        Message: "failed calling webhook \"virtualmachineinstances-mutator.kubevirt.io\": Post https://virt-api.kubevirt.svc:443/virtualmachineinstances-mutate?timeout=30s: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kubevirt.io\")",
                        Field: "",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 500,
        },
    }
    Internal error occurred: failed calling webhook "virtualmachineinstances-mutator.kubevirt.io": Post https://virt-api.kubevirt.svc:443/virtualmachineinstances-mutate?timeout=30s: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubevirt.io")
occurred
tests/vmidefaults_test.go:81
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fgimenez** [comment] 2021-02-08 10:53
Happened here again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev/1357811414370095104 this time on `test_id:3200`

**Comment by fgimenez** [comment] 2021-02-24 10:06
/reopen

Happened here again on test_id:4558 https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev/1363609743758725120

**Comment by fgimenez** [comment] 2021-02-24 10:11
/close

In fact this is the same underlying issue as #4649 and #4698, reopening the oldest one.

Duplicate of #4649

**Comment by fgimenez** [comment] 2021-02-24 10:12
Duplicate of #4649

**Closed by fgimenez** 2021-02-24 10:11 UTC
Labels: kind/bug, triage/build-watcher
