### ISSUE TITLE
[flaky test] [rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:component]Networking VirtualMachineInstance with custom interface model [test_id:1770]should expose the right device type to the guest

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#3575] opened 2020-06-16 10:49 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

Test appears flaky: 
24h report: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2020-06-15-024h.html#row5
168h report: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2020-06-15-168h.html#row90

failed once on k8s-1/17 and once on k8s-1.18 with same error, once failed with a different error, and succeeded otherwise.

Failure log:
```
/root/go/src/kubevirt.io/kubevirt/tests/vmi_networking_test.go:415
VMI testvmij2hd6h95rvdp4rcr5nrfxcb9wsft9z5tnlw8m6flrnlnv47g unexpectedly stopped. State: Failed
Expected
    <bool>: true
to be false
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:2650
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment] 2020-06-17 06:38
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3507/pull-kubevirt-e2e-k8s-1.18/1272379038165372928/artifacts/2_pods.log

```
                "hostname": "testvmij2hd6h95rvdp4rcr5nrfxcb9wsft9z5tnlw8m6flrnlnv47g",
                "schedulerName": "default-scheduler",
                "tolerations": [
                    {
                        "key": "node.kubernetes.io/not-ready",
                        "operator": "Exists",
                        "effect": "NoExecute",
                        "tolerationSeconds": 300
                    },
                    {
                        "key": "node.kubernetes.io/unreachable",
                        "operator": "Exists",
                        "effect": "NoExecute",
                        "tolerationSeconds": 300
                    }
                ],
                "priority": 0,
                "enableServiceLinks": true
            },
            "status": {
                "phase": "Failed",
                "message": "Pod Allocate failed due to requested number of devices unavailable for devices.kubevirt.io/kvm. Requested: 1, Available: 0, which is unexpected",
                "reason": "UnexpectedAdmissionError",
                "startTime": "2020-06-15T07:17:40Z"
            }
```

**Comment by oshoval** [comment] 2020-06-21 10:52
still under investigation, due to a panic of virt-handler (grpc server is closing ?), which cause the kvm to disappear, 

test 1466 on those 2 links suffer from same thing i think:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3539/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1272566802886430720

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3540/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1271432801291341825

**Comment by oshoval** [comment] 2020-06-23 09:20
The label network is not right here.

The problem is that after getting a domain even of ERROR, the Server is closed on virt-handler,
and there is an event sometimes, due to a race, which is sent to a closed channel.
it panics the virt-handler, and then a new virt-handler will start.
its takes time for the new virt-handler to report allocatable kvm devices, hence the test fails.

back to the root cause, i did see locally that sometimes the ERROR is reached, the server is closed and reopened, an no domain events are sent between, so this ERROR goes silent.
but sometimes because of bad synchronisation between the closing of the channel and the handling of the events, the event will be sent to a closed channel and then panic.

panic can be seen at the bottom of this file
https://gcsweb.apps.ovirt.org/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3507/pull-kubevirt-e2e-k8s-1.18/1272379038165372928/artifacts/pods/2_kubevirt_virt-handler-2lgh4-virt-handler_previous.log

**Comment by rmohr** [comment] 2020-06-29 08:55
@davidvossel maybe you can assist @oshoval on this one?

**Comment by davidvossel** [comment] 2020-06-29 12:39
I don't think we're waiting for the grpc server to stop properly.  We tell the server to "stop" but don't wait for it to exit.

It might be as simple as something like this. 

```
diff --git a/pkg/virt-handler/notify-server/server.go b/pkg/virt-handler/notify-server/server.go
index a8d681fa4..b5c26c79e 100644
--- a/pkg/virt-handler/notify-server/server.go
+++ b/pkg/virt-handler/notify-server/server.go
@@ -150,13 +150,14 @@ func RunServer(virtShareDir string, stopChan chan struct{}, c chan watch.Event,
        }()
 
        // wait for either the server to exit or stopChan to signal
-       select {
-       case <-done:
-               log.Log.Info("notify server done")
-       case <-stopChan:
-               grpcServer.Stop()
-               log.Log.Info("notify server stopped")
+       for {
+               select {
+               case <-done:
+                       log.Log.Info("notify server done")
+                       return nil
+               case <-stopChan:
+                       grpcServer.Stop()
+                       log.Log.Info("notify server stopped")
+               }
        }
-
-       return nil
 }
```

**Comment by davidvossel** [comment] 2020-06-29 12:46
I opened a pr #3709 maybe this addresses it.

**Comment by oshoval** [comment] 2020-06-29 13:03
Thanks David,

Discussed with Alona, Serve wont wait for handleRawConn which is a function that serveStreams runs in a go routine.
We think that we should add a mechinsem that will protect closing the channel. with a reader writer lock of the handleRawConn.
Wdyt ?

Commented in the PR about what i think would happen.

**Comment by oshoval** [comment] 2020-06-29 17:13
Purposing this
https://github.com/kubevirt/kubevirt/pull/3713/files

**Closed** 2020-07-04 06:05 UTC
Labels: kind/bug, topic/network, triage/build-officer
