### ISSUE TITLE
[flaky ci] [test_id:1635] VMIlifecycle Creating a VirtualMachineInstance with node tainted the vmi with  tolerations should be scheduled 

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3664] opened 2020-06-25 15:46 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
kind bug
> /kind enhancement

**What happened**:

[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]VMIlifecycle   [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]Creating  a VirtualMachineInstance with node tainted [test_id:1635]the vmi with  tolerations should be scheduled 

/root/go/src/kubevirt.io/kubevirt/tests/vmi_lifecycle_test.go:689 VMI testvmisl2862zxxqshrwtcj6g4z7glf445q486fhwww6cglsmfmt5c unexpectedly stopped. State: Failed Expected     <bool>: true to be false /root/go/src/kubevirt.io/kubevirt/tests/utils.go:2657

Link to the failing job : https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-k8s-1.17/1275546119513837568

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by maya-r** [comment] 2020-07-05 16:08
Searching for "unexpectedly stopped" finds #3669 and #3666 as well as this bug.
In one of them there is [a comment](https://github.com/kubevirt/kubevirt/issues/3666#issuecomment-653877000) suggesting the issue was fixed.

**Comment by oshoval** [comment] 2020-07-05 17:04
> Searching for "unexpectedly stopped" finds #3669 and #3666 as well as this bug.
> In one of them there is [a comment](https://github.com/kubevirt/kubevirt/issues/3666#issuecomment-653877000) suggesting the issue was fixed.

Thanks Maya, you right,
but it should come with panic in the previous virt-handler,
anyway we would know soon what the real leftovers are.

**Comment by oshoval** [comment] 2020-07-05 17:23
> Searching for "unexpectedly stopped" finds #3669 and #3666 as well as this bug.
> In one of them there is [a comment](https://github.com/kubevirt/kubevirt/issues/3666#issuecomment-653877000) suggesting the issue was fixed.

Thanks Maya, but In this one i didn't see panic in the previous handler, so this isnt a blind dupe of #3575
"unexpectedly stopped" should come with panic in previous virt-handler in order to know its a dupe of #3575 ,
(more precisely, panic "send on closed channel")

**Comment by awels** [comment] 2020-08-11 13:04
Another instance of this: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3961/pull-kubevirt-e2e-k8s-1.16/1292906884843442176

**Closed** 2020-08-23 23:00 UTC
Labels: triage/build-officer
