### ISSUE TITLE
Disabled SELinux detected as Permissive Mode

### ISSUE THREAD

**Issue by pothos** [kubevirt/kubevirt#5298] opened 2021-03-23 09:58 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

KubeVirt tries to relabel `/dev/net/tun` when running on Flatcar Container Linux 2765.2.1 with SELinux disabled, which results in a panic and crash (because SELinux is not reachable).

The relabeling attempt happens because KubeVirt detects the system would be in Permissive Mode just because the filesystem `/sys/fs/selinux` is mounted and it only looks at the `enforce` file there:
https://github.com/kubevirt/kubevirt/blob/0c0c443d4e656068b005a534436cb99e49d32749/cmd/virt-chroot/selinux.go#L19

But instead, it should do first a check whether SELinux is disabled. This is reported correctly by `sestatus` or `getenforce`.

**What you expected to happen**:

Check the value of ` /proc/thread-self/attr/current` and if it's `kernel`, then SELinux is disabled and not in Permissive Mode (which has the respective label like, e.g., `system_u:system_r:kernel_t:s0` or similar).
This is also how `sestatus` or `getenforce` check whether SELinux is disabled on Flatcar Container Linux.

**How to reproduce it (as minimally and precisely as possible)**:

This is how to disable SELinux on Flatcar Container Linux:

```
sudo cp --remove-destination $(readlink -f /etc/selinux/config) /etc/selinux/config
sudo sed -i "s/SELINUX=permissive/SELINUX=disabled/g" /etc/selinux/config
sudo systemctl reboot
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Flatcar Container Linux 2765.2.1
- Kernel (e.g. `uname -a`): 5.10
- Install tools:
- Others:

**Comment by phoracek** [comment] 2021-03-31 14:56
@pothos is the problem that KubeVirt does not work on a system without SELinux present? If so, it may be already fixed in 0.39.1.

If that is not the case, your proposal may be a nice improvement for the SELinux detection.

**Comment by pothos** [comment] 2021-03-31 20:13
It works without SELinux present but only if the the filesystem is unmounted, too. Simply disabling SELinux is not enough because KubeVirt detects it as Permissive as long as the filesystem is mounted.

**Comment by terinjokes** [comment] 2021-04-05 21:13
I've written a patch to `virt-chroot` inspired by the checks conducted by libselinux. It works well on the systems I've tested with, but doesn't work inside a KubeVirt container because `/etc/selinux/config` from the host is not mounted into the container.

I can modify the checks to check procfs (though it looks like `thread-self` is too new for RHEL), but I would prefer to match the checkes done by getenfroce.

**Comment by pothos** [comment] 2021-04-06 07:45
As mentioned, this here should work from inside the container to detect if SELinux is on or not:
> Check the value of /proc/thread-self/attr/current and if it's kernel, then SELinux is disabled and not in Permissive Mode (which has the respective label like, e.g., system_u:system_r:kernel_t:s0 or similar).
This is also how sestatus or getenforce check whether SELinux is disabled on Flatcar Container Linux.

**Comment by phoracek** [comment] 2021-04-06 08:12
@pothos would you mind opening a PR with your suggested fix? Please don't hesitate to reach out if you would need any assistance with it

**Comment by terinjokes** [comment] 2021-04-06 08:12
That's not how [getenforce checks](https://github.com/SELinuxProject/selinux/blob/d155b410d4bbc90d28f361b966f0429598da8188/libselinux/src/enabled.c#L11), it uses a combination of checking the mountpount at `/sys/fs/selinux` or `/selinux` for the magic selinux type and for the existence of `/etc/selinux/config`.

As mentioned in my previous comment, checking `/proc/thread-self/attr/current` might work (I haven't yet fully tested), but is not supported across all distributions, and I'd rather match the checks getenforce does.

**Comment by pothos** [comment] 2021-04-08 08:39
Hm, I have not checked when this code was dropped but it was part of at least version 2.4:
https://github.com/SELinuxProject/selinux/blob/libselinux-2.4/libselinux/src/enabled.c#L26

Checking the config file does not make much sense to me not only due to the mount namespaces but also because the file can be changed/removed/created independently from the current setting and vice versa.

About `/proc/thread-self/attr/current`: you can use any valid PID, like `/proc/self/attr/current` or `/proc/1/attr/current`.

**Comment by pothos** [comment] 2021-04-08 08:50
Here the commit that removed detecting that no policy was loaded: https://github.com/SELinuxProject/selinux/commit/685f4aeeadc0b60f3770404d4f149610d656e3c8
I can understand trying to follow what upstream does and check for the config file in the right mount namespace and Flatcar will need to change its behavior to not mount the filesystem (probably by updating the SELinux libraries). Still I think the upstream behavior is misleading (because it misses corner cases), specially if it happens to run in a container…

**Comment by terinjokes** [comment] 2021-04-08 08:53
Looks like the config file check was added due to a regression: https://bugzilla.redhat.com/show_bug.cgi?id=1219045

It might be worth asking libselinux if they want to revisit this. I also thought checking the config file was unusual.

**Comment by pothos** [comment] 2021-04-08 09:13
Yes, I think the circumstances are also a bit different now and it's quite likely that `getenforce` ends up being used in a container where `selinux_mnt && has_selinux_config` would lead to SELinux being detected as disabled while it's enforcing/permissive, even assuming that the mounting of the filesystem is done as expected by newer versions.

**Comment by pothos** [comment] 2021-04-08 09:19
Test on a new Fedora host and a Fedora container (which does not ship `/etc/selinux/config` by default):
```
$ getenforce ; podman run --rm -it fedora sh -c 'dnf install -y /usr/sbin/getenforce >/dev/null && getenforce'
Permissive
Disabled
```

**Comment by pothos** [comment] 2021-04-08 18:20
@terinjokes I sent a mail: https://lore.kernel.org/selinux/CAL6HQvHN+9pp8+h0kqf9mJAtYS6_ZQvVE2JNkk3QqqUveXiTzg@mail.gmail.com/T/#u

**Comment by rstober** [comment] 2021-04-08 20:33
I'm not a developer, just an admin trying to use Kubevirt. I've got selinux disabled, so I run into this bug and cannot start a VM. 
Is there any workaround?

**Comment by terinjokes** [comment] 2021-04-08 20:38
I believe setting the kernel parameter `selinux=0` will disable mounting the filesystem. Alternatively, from the host you can unmount `/sys/fs/selinux` and restart the KubeVirt pod.

**Comment by bachradsusi** [comment] 2021-04-09 07:15
Actually using the kernel parameter `selinux=0` is only reliable way how to disable SELinux. Run time disabling SELinux is deprecated since 5.6 kernel and it's supposed to be removed in near future - https://lwn.net/Articles/831748/

**Comment by terinjokes** [comment] 2021-04-09 07:26
In this case, SELinux is already disabled though?

**Comment by pothos** [comment] 2021-04-12 09:58
So, in summary the way forward is to ensure that the filesystem is not mounted when SELinux is disabled. One can also argue that the purpose of the check in `getenforce` and in KubeVirt is different and for KubeVirt it does not make sense to exactly copy this behavior (e.g., don't check if the config file exists) – this is also an opportunity to include the sanity check for `/proc/PID/attr/current` but it's not really needed because the recommended way to disable SELinux is to pass the `selinux=0` kernel parameter which doesn't even mount the filesystem in the first place.
If the additional `attr/current` check is wanted, we can leave this ticket open, otherwise I'm fine with closing this now.

**Comment by terinjokes** [comment] 2021-04-14 00:01
I think this should be well described in the release notes, but otherwise seems like a reasonable position to take.

**Closed** 2021-09-11 02:17 UTC
Labels: lifecycle/rotten, triage/needs-information
