### ISSUE TITLE
[Flakey CI] Infrastructure [rfe_id:3187][crit:medium][vendor:cnv-qe@redhat.com][level:component]Prometheus Endpoints [test_id:4142]should include the storage metrics for a running VM

### ISSUE THREAD

**Issue by omeryahud** [kubevirt/kubevirt#3810] opened 2020-07-12 12:53 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-officer

**What happened**:
Flakefinder reported a flakey test:
```
Infrastructure [rfe_id:3187][crit:medium][vendor:cnv-qe@redhat.com][level:component]Prometheus Endpoints [test_id:4142]should include the storage metrics for a running VM
```
in this Prow job:
- https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3738/pull-kubevirt-e2e-k8s-1.18/1280492741075144704

**What you expected to happen**:
Test to pass, and provide a proper failure message (description of the failed `Expect`ation) when it fails 
**How to reproduce it (as minimally and precisely as possible)**:
See Prow job

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jean-edouard** [comment] 2020-07-13 21:02
Duplicate of https://github.com/kubevirt/kubevirt/issues/3689

**Closed** 2020-12-10 18:54 UTC
Labels: kind/bug, lifecycle/rotten, triage/build-watcher
