### ISSUE TITLE
[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]VMIlifecycle   [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]Delete  a VirtualMachineInstance's Pod [test_id:1650]should result in the  VirtualMachineInstance moving to a finalized state

### ISSUE THREAD

**Issue by ashleyschuett** [kubevirt/kubevirt#3863] opened 2020-07-21 10:06 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/triage build-officer 

**What happened**:
```
[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]VMIlifecycle [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]Delete  a VirtualMachineInstance's Pod [test_id:1650]should result in the  VirtualMachineInstance moving to a finalized state 

/root/go/src/kubevirt.io/kubevirt/tests/vmi_lifecycle_test.go:1326 Unexpected Warning event received:
 testvmiwkvr5p7mbxvqpdngvv98xckg8hpmx9q95l8x2m2w82wd7rxf,00457587-ac7a-4e0f-9ab9-2a47511793b5: server error.
 command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: Failed to start QEMU binary /usr/libexec/qemu-kvm for probing: ')" 
Expected     
     <string>: Warning 
not to equal     
     <string>: Warning 
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:356
```

**What you expected to happen**:
Test to pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Failed Job: 

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3852/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1285347225106386944

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment] 2020-08-18 11:47
/close

Thanks @ashleyschuett closing this as a duplicate of #3757

**Closed by rmohr** 2020-08-18 11:48 UTC
Labels: kind/bug, triage/build-officer
