### ISSUE TITLE
cannot start vmi/vms on ubuntu 20.04LTS using microk8s

### ISSUE THREAD

**Issue by jasonbunch** [kubevirt/kubevirt#5455] opened 2021-04-14 19:01 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
cannot start VMI or VMS on Ubuntu 20.04 LTS running microK8S.

**What you expected to happen**:
vmi / vms to start

**How to reproduce it (as minimally and precisely as possible)**:
install 20.04LTS
install microk8s from snap
install dns and multus using microk8s.enable
deploy kubectl using quick start guides
apply yaml file of a VMI

**Anything else we need to know?**:
vmi is deployed and the container starts.  The VMI (using get VMI) shows as failed, container runs and falls into failed state.  Still learning K8S checked the usual logs recommended online but nothing jumps out as a reason for the failure

**Environment**:
- KubeVirt version (use `virtctl version`):
microk8s.kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.5-34+40f5951bd9888a", GitCommit:"40f5951bd9888a0e27960e88d1250627fb085871", GitTreeState:"clean", BuildDate:"2021-03-22T16:58:38Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.5-34+40f5951bd9888a", GitCommit:"40f5951bd9888a0e27960e88d1250627fb085871", GitTreeState:"clean", BuildDate:"2021-03-22T16:59:52Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-fedora-1
  name: vmi-fedora-1
spec:
        #networks:
        #- name: default
        #pod: {}
  domain:
    devices:
            #interfaces:
            #- name: default
            #masquerade: {}
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      rng: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:v0.21.0
    name: containerdisk
  - cloudInitNoCloud:
      userData: |
        #cloud-config
        hostname: fedora-0
        password: fedora
        chpasswd: { expire: False }
        ssh_pwauth: True
        disable_root: false
        ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDsYL8SnJf3blzXmsqJrdyz8RF88W+k9tv/5muoL9ieUGpI67cCKbzCInfKRiuMaDd51D8f+ezZzwx6x/sSbhaDIA90cPBCJIVXY3sVLTSIYK+EzfzDdgYBdpphsRCapwK++5Yev68NT/02BJRbqXhNrYcE4bj2GEQX6Tq8n3LqOYg3j5TvmCBvxut7qztn16rNHFBFF2K/AEavzkyFrzaddFAdVzmV79zBAhCYwoRWhXffMr0NxihxdbglT7qNRtJbOlvBgbYinn2rSsXrSF+1TdCHk3Uo+H5q2sfSDtMQCN32Oh+bCG/zxwL8p2hbdC6AKIk3LzICTqFa+gRCvOWR
    name: cloudinitdisk
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
- Kernel (e.g. `uname -a`):
5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
MicroK8S
- Others:

microk8s.kubectl get pods --all-namespaces
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
kube-system   kube-multus-ds-amd64-v6pcp                1/1     Running   7          3d8h
kube-system   calico-kube-controllers-847c8c99d-j82px   1/1     Running   8          3d8h
kube-system   calico-node-vthjv                         1/1     Running   9          3d8h
kube-system   coredns-86f78bb79c-k5v92                  1/1     Running   5          3d6h
kubevirt      virt-api-555f7bb78-mppw7                  1/1     Running   7          3d8h
kubevirt      virt-handler-4l6pd                        1/1     Running   7          3d8h
kubevirt      virt-controller-85688dbdb6-zq6sn          1/1     Running   7          3d8h
kubevirt      virt-controller-85688dbdb6-n95j5          1/1     Running   2          3d4h
kubevirt      virt-api-555f7bb78-c7fds                  1/1     Running   2          3d4h
kubevirt      virt-operator-79574b7dc5-6h2c6            1/1     Running   7          3d8h

microk8s.kubectl get vmi
NAME           AGE   PHASE    IP    NODENAME
vmi-fedora-1   7s    Failed         edge01

microk8s.kubectl describe vmi
Events:
  Type     Reason            Age   From                       Message
  ----     ------            ----  ----                       -------
  Normal   SuccessfulCreate  11s   virtualmachine-controller  Created virtual machine pod virt-launcher-vmi-fedora-1-qgs28
  Warning  Stopped           7s    virt-handler               The VirtualMachineInstance crashed.

microk8s.kubectl describe pod virt-launcher-vmi-fedora-1-qgs28
Events:
  Type    Reason          Age   From               Message
  ----    ------          ----  ----               -------
  Normal  Scheduled       80s   default-scheduler  Successfully assigned default/virt-launcher-vmi-fedora-1-qgs28 to edge01
  Normal  AddedInterface  79s   multus             Add eth0 [10.1.204.44/32]
  Normal  Pulled          79s   kubelet            Container image "quay.io/kubevirt/virt-launcher@sha256:84123d7271da7da8c5099a329ca55c38f228cc9e1d9c572a97c          9d96badeccda2" already present on machine
  Normal  Created         79s   kubelet            Created container container-disk-binary
  Normal  Started         79s   kubelet            Started container container-disk-binary
  Normal  Pulled          78s   kubelet            Container image "kubevirt/fedora-cloud-container-disk-demo:v0.21.0" already present on machine
  Normal  Created         78s   kubelet            Created container volumecontainerdisk-init
  Normal  Started         78s   kubelet            Started container volumecontainerdisk-init
  Normal  Pulled          77s   kubelet            Container image "quay.io/kubevirt/virt-launcher@sha256:84123d7271da7da8c5099a329ca55c38f228cc9e1d9c572a97c          9d96badeccda2" already present on machine
  Normal  Created         77s   kubelet            Created container compute
  Normal  Started         77s   kubelet            Started container compute
  Normal  Pulled          77s   kubelet            Container image "kubevirt/fedora-cloud-container-disk-demo:v0.21.0" already present on machine
  Normal  Created         77s   kubelet            Created container volumecontainerdisk
  Normal  Started         77s   kubelet            Started container volumecontainerdisk

microk8s.kubectl logs  virt-launcher-vmi-fedora-1-qgs28 compute
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:68","timestamp":"2021-04-14T18:53:33.710067Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:71","       timestamp":"2021-04-14T18:53:33.710453Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu:///system","pos":"libvirt.go:417","timestamp":"2021-04-14T18:53:33.714197Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libv       irt/libvirt-sock': No such file or directory')","pos":"libvirt.go:425","timestamp":"2021-04-14T18:53:33.718871Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 6.6.0, package: 13.fc32 (Unknown, 2021-01-21-11:33:00, )","subcomponent":"libvirt","thread":"48","t       imestamp":"2021-04-14T18:53:33.733000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: vmi-fedora-1","subcomponent":"libvirt","thread":"48","timestamp":"2021-04-14T18:53:33.733000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Child process (dmidecode -q -t 0,1,2,3,4,11,17) unexpected exit status 1: /dev/mem: No such file or        directory","pos":"virCommandWait:2741","subcomponent":"libvirt","thread":"48","timestamp":"2021-04-14T18:53:33.733000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:433","timestamp":"2021-04-14T18:53:34.221747Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:432","timestamp":"2021-04-14T18:53:34.226567Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:73","timestamp":"2021-04-14T18:53:34.226808Z"}

sudo virt-host-validate qemu
  QEMU: Checking for hardware virtualization                                 : PASS
  QEMU: Checking if device /dev/kvm exists                                   : PASS
  QEMU: Checking if device /dev/kvm is accessible                            : PASS
  QEMU: Checking if device /dev/vhost-net exists                             : PASS
  QEMU: Checking if device /dev/net/tun exists                               : PASS
  QEMU: Checking for cgroup 'cpu' controller support                         : PASS
  QEMU: Checking for cgroup 'cpuacct' controller support                     : PASS
  QEMU: Checking for cgroup 'cpuset' controller support                      : PASS
  QEMU: Checking for cgroup 'memory' controller support                      : PASS
  QEMU: Checking for cgroup 'devices' controller support                     : PASS
  QEMU: Checking for cgroup 'blkio' controller support                       : PASS
  QEMU: Checking for device assignment IOMMU support                         : PASS
  QEMU: Checking if IOMMU is enabled by kernel                               : PASS
  QEMU: Checking for secure guest support                                    : WARN (Unknown if this platform has Secure Guest support)

kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used

**Comment by rmohr** [comment] 2021-04-19 08:34
This seems to be the selinux issue fixed in https://github.com/kubevirt/kubevirt/pull/5243. It should be part of 0.,39.1 but we had release issues. You can try this pre-release: https://github.com/kubevirt/kubevirt/releases/tag/v0.40.0-rc.2

**Comment by jasonbunch** [comment] 2021-04-19 18:29
Hi rmohr,

I recreated the server using v0.40.0-rc.2 as requested and the output in the same, the VMI transitions to failed and the log outputs are the same.

microk8s.kubectl get pods --all-namespaces
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
kube-system   coredns-86f78bb79c-vd8sv                  1/1     Running   0          40m
kube-system   calico-kube-controllers-847c8c99d-qdk5f   1/1     Running   1          47m
kube-system   calico-node-km698                         1/1     Running   1          47m
kube-system   kube-multus-ds-amd64-s4c48                1/1     Running   0          39m
kubevirt      virt-operator-5d6fd8ff6f-wxq5p            1/1     Running   0          36m
kubevirt      virt-api-58f59b564c-xdd4l                 1/1     Running   0          35m
kubevirt      virt-api-58f59b564c-trn9g                 1/1     Running   0          35m
kubevirt      virt-controller-56846964c7-2zrkr          1/1     Running   0          35m
kubevirt      virt-controller-56846964c7-78d88          1/1     Running   0          35m
kubevirt      virt-handler-x9vkk                        1/1     Running   0          35m
default       virt-launcher-vmi-fedora-1-7bfkb          0/2     Error     0          5m33s

microk8s.kubectl get vmi
NAME           AGE    PHASE    IP    NODENAME
vmi-fedora-1   7m5s   Failed         edge01

microk8s.kubectl describe vmi
Events:
  Type     Reason            Age    From                       Message
  ----     ------            ----   ----                       -------
  Normal   SuccessfulCreate  7m18s  virtualmachine-controller  Created virtual machine pod virt-launcher-vmi-fedora-1-7bfkb
  Warning  Stopped           7m15s  virt-handler               The VirtualMachineInstance crashed.

microk8s.kubectl logs virt-launcher-vmi-fedora-1-7bfkb compute
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:76","timestamp":"2021-04-19T18:20:05.135450Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:79","timestamp":"2021-04-19T18:20:05.135508Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu:///system","pos":"libvirt.go:455","timestamp":"2021-04-19T18:20:05.137933Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory')","pos":"libvirt.go:463","timestamp":"2021-04-19T18:20:05.139225Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 6.6.0, package: 13.fc32 (Unknown, 2021-01-21-11:33:00, )","subcomponent":"libvirt","thread":"48","timestamp":"2021-04-19T18:20:05.148000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: vmi-fedora-1","subcomponent":"libvirt","thread":"48","timestamp":"2021-04-19T18:20:05.148000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Child process (dmidecode -q -t 0,1,2,3,4,11,17) unexpected exit status 1: /dev/mem: No such file or directory","pos":"virCommandWait:2741","subcomponent":"libvirt","thread":"48","timestamp":"2021-04-19T18:20:05.148000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:471","timestamp":"2021-04-19T18:20:05.640867Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:475","timestamp":"2021-04-19T18:20:05.643197Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:73","timestamp":"2021-04-19T18:20:05.643653Z"}
panic: timed out waiting for domain to be defined

goroutine 1 [running]:
main.waitForDomainUUID(0x45d964b800, 0xc000312840, 0xc0000ad1a0, 0x1ef1020, 0xc0016b2000, 0xc000312840)
        cmd/virt-launcher/virt-launcher.go:226 +0x3f4
main.main()
        cmd/virt-launcher/virt-launcher.go:451 +0x1023
{"component":"virt-launcher","level":"error","msg":"dirty virt-launcher shutdown","pos":"virt-launcher.go:532","reason":"exit status 2","timestamp":"2021-04-19T18:25:05.650209Z"}

Thanks, hope this helps, if you need additional logs please let me know.

**Comment by rmohr** [comment] 2021-04-20 07:26
could you share the logs from `virt-handler` on that node from the `virt-handler` daemonset?

**Comment by jasonbunch** [comment] 2021-04-20 18:13
{"component":"virt-handler","level":"info","msg":"Processing event default/vmi-fedora-1","pos":"vm.go:1410","timestamp":"2021-04-20T18:11:39.678224Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed\n","name":"vmi-fedora-1","namespace":"default","pos":"vm.go:1412","timestamp":"2021-04-20T18:11:39.678275Z","uid":"a8ef97e4-f052-4cdf-a24f-2d7da05ae092"}
{"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1419","timestamp":"2021-04-20T18:11:39.678294Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid a8ef97e4-f052-4cdf-a24f-2d7da05ae092","name":"vmi-fedora-1","namespace":"default","pos":"vm.go:1661","timestamp":"2021-04-20T18:11:39.678344Z","uid":"a8ef97e4-f052-4cdf-a24f-2d7da05ae092"}
{"component":"virt-handler","kind":"","level":"info","msg":"No container disk mount entries found to unmount","name":"vmi-fedora-1","namespace":"default","pos":"mount.go:326","timestamp":"2021-04-20T18:11:39.678385Z","uid":"a8ef97e4-f052-4cdf-a24f-2d7da05ae092"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up remaining hotplug volumes","name":"vmi-fedora-1","namespace":"default","pos":"mount.go:729","timestamp":"2021-04-20T18:11:39.678408Z","uid":"a8ef97e4-f052-4cdf-a24f-2d7da05ae092"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"vmi-fedora-1","namespace":"default","pos":"vm.go:1693","timestamp":"2021-04-20T18:11:39.678443Z","uid":""}
{"component":"virt-handler","level":"info","msg":"Processing event default/vmi-fedora-1","pos":"vm.go:1410","timestamp":"2021-04-20T18:11:39.711010Z"}
{"component":"virt-handler","level":"info","msg":"VMI does not exist","pos":"vm.go:1414","timestamp":"2021-04-20T18:11:39.711050Z"}
{"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1419","timestamp":"2021-04-20T18:11:39.711066Z"}
{"component":"virt-handler","kind":"VirtualMachineInstance","level":"info","msg":"Performing final local cleanup for vmi with uid ","name":"vmi-fedora-1","namespace":"default","pos":"vm.go:1661","timestamp":"2021-04-20T18:11:39.711097Z","uid":""}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"vmi-fedora-1","namespace":"default","pos":"vm.go:1693","timestamp":"2021-04-20T18:11:39.711130Z","uid":""}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: kvm","pos":"generic_device.go:257","timestamp":"2021-04-20T18:11:56.118654Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [\u0026ContainerAllocateRequest{DevicesIDs:[kvm77],}]","pos":"generic_device.go:258","timestamp":"2021-04-20T18:11:56.118724Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: tun","pos":"generic_device.go:257","timestamp":"2021-04-20T18:11:56.119046Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [\u0026ContainerAllocateRequest{DevicesIDs:[tun88],}]","pos":"generic_device.go:258","timestamp":"2021-04-20T18:11:56.119087Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: vhost-net","pos":"generic_device.go:257","timestamp":"2021-04-20T18:11:56.119316Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [\u0026ContainerAllocateRequest{DevicesIDs:[vhost-net71],}]","pos":"generic_device.go:258","timestamp":"2021-04-20T18:11:56.119353Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vmi-fedora-1","pos":"vm.go:1410","timestamp":"2021-04-20T18:11:59.597790Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled\n","name":"vmi-fedora-1","namespace":"default","pos":"vm.go:1412","timestamp":"2021-04-20T18:11:59.597823Z","uid":"dd12d50b-c6e6-42f2-a2f0-2a74b8a61ae3"}
{"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1419","timestamp":"2021-04-20T18:11:59.597837Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vmi-fedora-1","pos":"vm.go:1410","timestamp":"2021-04-20T18:11:59.607338Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed\n","name":"vmi-fedora-1","namespace":"default","pos":"vm.go:1412","timestamp":"2021-04-20T18:11:59.607373Z","uid":"dd12d50b-c6e6-42f2-a2f0-2a74b8a61ae3"}
{"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1419","timestamp":"2021-04-20T18:11:59.607392Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid dd12d50b-c6e6-42f2-a2f0-2a74b8a61ae3","name":"vmi-fedora-1","namespace":"default","pos":"vm.go:1661","timestamp":"2021-04-20T18:11:59.607436Z","uid":"dd12d50b-c6e6-42f2-a2f0-2a74b8a61ae3"}
{"component":"virt-handler","kind":"","level":"info","msg":"No container disk mount entries found to unmount","name":"vmi-fedora-1","namespace":"default","pos":"mount.go:326","timestamp":"2021-04-20T18:11:59.607475Z","uid":"dd12d50b-c6e6-42f2-a2f0-2a74b8a61ae3"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up remaining hotplug volumes","name":"vmi-fedora-1","namespace":"default","pos":"mount.go:729","timestamp":"2021-04-20T18:11:59.607502Z","uid":"dd12d50b-c6e6-42f2-a2f0-2a74b8a61ae3"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"vmi-fedora-1","namespace":"default","pos":"vm.go:1693","timestamp":"2021-04-20T18:11:59.607540Z","uid":""}

**Comment by rmohr** [comment] 2021-07-20 08:52
@jasonbunch sorry I think I missed your updated back then.

The error line:

```
{"component":"virt-handler","kind":"","level":"info","msg":"No container disk mount entries found to unmount","name":"vmi-fedora-1","namespace":"default","pos":"mount.go:326","timestamp":"2021-04-20T18:11:59.607475Z","uid":"dd12d50b-c6e6-42f2-a2f0-2a74b8a61ae3"}
```

is a typical indicator that the kubelet pod-directory is not at the default location. This is very likely a duplicate of #5913.

**Closed** 2021-09-18 16:59 UTC
Labels: kind/bug, lifecycle/rotten
