### ISSUE TITLE
Custom MAC address functional test case fails on OpenShift

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1282] opened 2018-07-05 10:08 UTC
From https://rfenkhuber.fedorapeople.org/jenkins/143/openshift-3.10-release-console.log

```
------------------------------
• Failure [186.187 seconds]
Networking
/root/go/src/kubevirt.io/kubevirt/tests/vmi_networking_test.go:48
  should be able to reach
  /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
    the Inbound VirtualMachineInstance with custom MAC address [It]
    /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46

    Expected error:
        <expect.TimeoutError>: 180000000000
        expect: timer expired after 180 seconds
    not to have occurred

    /root/go/src/kubevirt.io/kubevirt/tests/vmi_networking_test.go:225
------------------------------
STEP: checking br1 MTU inside the pod
level=info timestamp=2018-07-04T09:38:00.596783Z pos=vmi_networking_test.go:186 component=tests msg="4: br1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default \n    link/ether 0a:58:0a:fb:d3:e6 brd ff:ff:ff:ff:ff:ff\n    inet 169.254.75.86/32 brd 169.254.75.86 scope global br1\n       valid_lft forever preferred_lft forever\n    inet6 fe80::858:aff:fefb:d3e6/64 scope link \n       valid_lft forever preferred_lft forever\n"
STEP: checking eth0 MTU inside the VirtualMachineInstance
level=info timestamp=2018-07-04T09:38:01.063936Z pos=vmi_networking_test.go:206 component=tests msg="[{1 \r\n$  [$ ]} {3 ip address show eth0\r\n2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast qlen 1000\r\n [2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast qlen 1000\r\n]} {5     link/ether 0 [0]}]"
STEP: checking the VirtualMachineInstance can send MTU sized frames to another VirtualMachineInstance
level=info timestamp=2018-07-04T09:41:06.564108Z pos=utils.go:1186 component=tests namespace=kubevirt-test-default name=testvmiqrv5q kind=VirtualMachineInstance uid=9fc7491e-7f6d-11e8-9aab-525500d15501 msg="[{1 \r\n\r\n$  [$ ]} {3 ping 10.128.0.26 -c 1 -w 5 -s 1422\r\nPING 10.128.0.26 (10.128.0.26): 1422 data bytes\r\n\r\n--- 10.128.0.26 ping statistics ---\r\n5 packets transmitted, 0 packets received, 100% packet loss\r\n$  [$ ]} {5 echo $?\r\n1\r\n$  []}]"
kubevirt.io
••
```

**Comment by booxter** [comment] 2018-07-06 20:59
This is not a *sometimes* issue. I can consistently reproduce it on OpenShift. I believe it's because of how its SDN is configured. Here is the OVS flow rule that is configured to steer ARP traffic from pods:

```
 cookie=0x0, duration=1382.053s, table=20, n_packets=44, n_bytes=1848, priority==
100,arp,in_port=9,arp_spa=10.129.0.8,arp_sha=00:00:0a:81:00:08/00:00:ff:ff:ff:fff
 actions=load:0->NXM_NX_REG0[],goto_table:21
```

See that it assumes a specific arp_sha (hardware address). I believe the flow is the culprit, though I need some more time to dig it.

**Comment by booxter** [comment] 2018-07-09 20:58
The reason why it happens on OpenShift is because its SDN configures specific rules to forbid traffic that carries a MAC address that was not configured for the pod. The code is here: https://github.com/openshift/origin/blob/cd9faeeb75810a8141a08e5a5e1d288964641227/pkg/network/node/ovscontroller.go#L241

Since we pass frames from vnet0 directly to eth0 (through br1) without overriding hwaddr, OVS flow rules block ARP traffic needed to communicate to outside.

I don't see a proper hooking mechanism to make SDN add more flows to accommodate for a new MAC address. We can try to craft something in-house, adding a new flow when pod interface is configured by virt-launcher. There are two complications here:

1. we would need to pull / vendorize openshift code into kubevirt to get access to ovsController;
2. there may be complications in pulling all the relevant pieces to reconstruct the needed flow (for example, I am not yet sure how to determine the vnid to use though 0 would work for basic single tenant setup);
3. we would need to decide whether to set up the flow depending on platform we run on (while we originally wanted to isolate ourselves from underlying SDN).

To be completely transparent to SDN, we may explore a more complex networking setup where we would have a router in between vNIC and external pod interface (eth0) to override MAC address to the address allocated by SDN. This of course impedes performance, though it may be ok for pod network.

**Comment by fabiand** [comment] 2018-07-10 14:44
Awesome debug effort!

How do you think about accepting this limitation on the Kubernetes pod network, and rather add a check to the pod backend to raise an error if a mac address is specified which diverges from the pod's mac?

Actually. This should be with delegateIP only - but not be affected by SLIRP. Could this be correct?

**Comment by booxter** [comment] 2018-07-10 17:36
@fabiand I would prefer that we build a more complex in-pod networking solution to accommodate for a custom MAC address to have it transparent to everyone. While there is a performance / complexity hit to endure, we can isolate it to the custom MAC address case, leaving the current br1 setup as-is for regular case.

Having a piece of API not working for the happy / default path seems rather limiting / not graceful.

**Comment by booxter** [comment] 2018-07-11 20:48
@fabiand you've asked if SLIRP is affected. No, though it has its own issues (like ICMP not working at all).

**Comment by fabiand** [comment] 2019-01-13 17:15
Any idea?

**Comment by fabiand** [comment] 2019-01-14 13:39
Sebastian, haven't we moved this test to the multus  interface?
There is no need nor hope to control the mac address of the default network.

**Comment by SchSeba** [comment] 2019-01-14 13:48
@fabiand I think we can close this issue. We have tests for multus and also we have tests for the default network on kubernetes because flannel cni allow us to change the mac address. 

```golang
tests.SkipIfOpenShift("Custom MAC addresses on pod networks are not supported")
```

**Comment by fabiand** [comment] 2019-01-16 20:54
Please handle as you wish :)

**Comment by SchSeba** [comment] 2019-02-16 10:10
We have tests for multus and also we have tests for the default network on kubernetes because flannel cni allow us to change the mac address.

```go
tests.SkipIfOpenShift("Custom MAC addresses on pod networks are not supported")
```

**Closed by SchSeba** 2019-02-16 10:10 UTC
Labels: kind/bug, lifecycle/rotten, topic/ci, topic/network, topic/testing
