### ISSUE TITLE
[rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration Starting a VirtualMachineInstance  live migration cancelation should be able to cancel a migration [It] [test_id:2226]with ContainerDisk 

### ISSUE THREAD

**Issue by orenc1** [kubevirt/kubevirt#3739] opened 2020-07-02 17:42 UTC
/kind bug
/triage build-officer

**What happened**:
[Prow Job link](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3708/pull-kubevirt-e2e-k8s-1.17/1278479781469360129#1:build-log.txt%3A6844)
```
 • Failure [779.690 seconds]
[rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration
/root/go/src/kubevirt.io/kubevirt/tests/migration_test.go:63
  Starting a VirtualMachineInstance 
  /root/go/src/kubevirt.io/kubevirt/tests/migration_test.go:346
    live migration cancelation
    /root/go/src/kubevirt.io/kubevirt/tests/migration_test.go:1102
      should be able to cancel a migration
      /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
        [test_id:2226]with ContainerDisk [It]
        /root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43
        Timed out after 720.000s.
        Should have AgentConnected condition
        Expected
            <bool>: false
        to be true
        /root/go/src/kubevirt.io/kubevirt/tests/utils.go:4490 
```
**Lane**:
pull-kubevirt-e2e-k8s-1.17

**Comment by oshoval** [comment] 2020-07-05 05:39
Possible dupe of https://github.com/kubevirt/kubevirt/issues/3662

**Closed** 2020-12-02 07:57 UTC
Labels: kind/bug, lifecycle/rotten, triage/build-watcher
