### ISSUE TITLE
howto deploy kubevirt on an existing k8s cluster

### ISSUE THREAD

**Issue by KennethNagin** [kubevirt/kubevirt#581] opened 2017-11-20 15:01 UTC
I want to deploy kubevirt on an existing k8s cluster, Could you direct me to some documentation on the subject; I could not find anything.

**Comment by mz-pdm** [comment] 2017-11-21 11:36
You can follow docs/dev-env-local.md, just skip "Running kubernetes" part.

**Comment by fabiand** [comment] 2017-11-23 14:20
Closing as a dupe of #265

**Closed by fabiand** 2017-11-23 14:20 UTC
