### ISSUE TITLE
Investigate unexpected error

### ISSUE THREAD

**Issue by xpivarc** [kubevirt/kubevirt#8423] opened 2022-09-07 08:35 UTC
**What happened**:
Unexpected error occurred :
`Unexpected Warning event received: vmi-kernel-boot,40972611-13bf-40e8-be4a-8e96b76e9f7e: unable to create virt-launcher client connection: can not add ghost record when entry already exists with differing UID`

Seen in https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8419/pull-kubevirt-e2e-k8s-1.23-sig-compute-nonroot/1567301949986967552

This might be a quick turnaround or a real issue with clean up.

**What you expected to happen**:
Not to see this warning.

**How to reproduce it (as minimally and precisely as possible)**:
The mentioned test might be helpful.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by xpivarc** [comment] 2022-09-07 13:06
The impact on CI is high https://search.ci.kubevirt.io/?search=external+alpine-based+kernel+only&maxAge=12h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

**Comment by xpivarc** [comment] 2023-02-10 14:33
/reopen
/remove-lifecycle rotten
@iholder101 Did you have a chance to look into this?

**Comment by xpivarc** [comment] 2023-02-10 14:35
I see this is now relevant for all VMs, not only for those using kernel boot.

**Comment by iholder101** [comment] 2023-02-12 13:41
@enp0s3 had found the root cause and is now working on a fix.
Thanks a lot @enp0s3!!

**Comment by enp0s3** [comment] 2023-02-12 15:04
@iholder101 Thank you!
From what I've seen in Itamar's PR, it can happen when using a VMI with fixed name. I will backport the randname usage when creating VMs with libvmi

**Comment by iholder101** [comment] 2023-02-14 07:35
PR fix is merged: https://github.com/kubevirt/kubevirt/pull/9222.
I think we can close this now.
/close

**Comment by xpivarc** [comment] 2023-03-11 12:06
/reopen
@iholder101  
Are we sure we did not treat the symptom rather than the root cause? I mean our records should be fast enough.
The change also seems no-op to me but maybe I am missing something.

**Comment by iholder101** [comment] 2023-03-12 16:08
> /reopen @iholder101 Are we sure we did not treat the symptom rather than the root cause? I mean our records should be fast enough.

Can you elaborate?

> The change also seems no-op to me but maybe I am missing something.

Also here. What do you mean? why a no-op?

**Comment by iholder101** [comment] 2023-04-09 10:19
> > > /reopen @iholder101 Are we sure we did not treat the symptom rather than the root cause? I mean our records should be fast enough.
> > 
> > 
> > Can you elaborate?
> 
> The message says that a record with the same key ( namespace + name ) but different uid already exists. This is a case when you delete/stop a VM/I and create/start VM/I with same name in the same namespace (of course the VM/I needs to land on the same node). This is valid case imho and the problem is that the cache is not cleared. In other words the cleanup is not called or we might have a bottle neck somewhere. I think it is worth to have a look on.

Hey @xpivarc!
IIRC, the root cause was that two tests, that were running in parallel, created a VMI with the same name on the same namespace. Therefore, the error message seems entirely valid. Since now the VMI names are randomized the test it not flakie anymore.

> > > The change also seems no-op to me but maybe I am missing something.
> > 
> > 
> > Also here. What do you mean? why a no-op?
> 
> Only test was changed and the `randname` was moved into `New` while before we passed the result as argument. This is not a big change.

Right, it's not a big change but it was necessary and solved the root cause. It isn't a no-op. Or am I missing something?

**Closed** 2023-09-06 12:46 UTC
Labels: kind/bug, lifecycle/rotten
