### ISSUE TITLE
[Flaky CI]ImageUpload Upload an image and start a VMI with PVC on rook-ceph [test_id:4621] Should succeed DataVolume expand_more

### ISSUE THREAD

**Issue by awels** [kubevirt/kubevirt#4868] opened 2021-01-21 18:46 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-watcher

> /kind enhancement

**What happened**:
Test failed during run: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4853/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1351899458278789120
Seems likely that the port-forward did not succeed.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tomob** [comment] 2021-01-22 13:06
Again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4672/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1350881373799321602

**Comment by nelsonspbr** [comment] 2021-02-04 05:36
Again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4953/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1356899908354838528

**Comment by phoracek** [comment] 2021-02-10 13:37
Happened again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4948/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1357325966732431361

**Comment by oshoval** [comment] 2021-02-18 19:14
two 4621 failures here
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5039/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1362430350462029824
```
vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43
Unexpected error:
    <*errors.errorString | 0xc0001f8ba0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
tests/imageupload_test.go:152
```

**Comment by tomob** [comment] 2021-03-03 12:45
And here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4387/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1364692756617760768
And here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4387/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1365237344944263168

**Comment by awels** [comment] 2021-03-04 16:09
And here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5126/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1367273577207828480

**Comment by brybacki** [comment] 2021-03-09 09:50
Able to reproduce locally, looks like sometimes the upload pod has a slow start. No idea why. Updating timeout should help.
```
Events:
Type Reason Age From Message
---- ------ ---- ---- -------
Warning FailedScheduling 18s default-scheduler persistentvolumeclaim "alpine-dv-scratch" not found
Normal Scheduled 17s default-scheduler Successfully assigned kubevirt-test-default1/cdi-upload-alpine-dv to node01
Normal SuccessfulAttachVolume 17s attachdetach-controller AttachVolume.Attach succeeded for volume "pvc-9d033262-714b-49e4-b056-61c68da6caf2"
Normal Pulled 1s kubelet Container image "quay.io/kubevirt/cdi-uploadserver:v1.31.0" already present on machine
Normal Created 1s kubelet Created container cdi-upload-server
Normal Started 0s kubelet Started container cdi-upload-server

**Comment by brybacki** [comment] 2021-03-09 09:57
Looking at the prow logs I can see the pod logs are not available. It means so pod did not start yet. This confirms my findings from local runs. 

Now lets wait for test lanes on #5178.

**Comment by brybacki** [comment] 2021-03-10 15:56
But anyway, now I think it is not the pulling that is problematic, when pulling image, the events look like this:
```
  Normal   Pulling                 9s    kubelet                  Pulling image "quay.io/kubevirt/cdi-uploadserver:v1.31.0"
  Normal   Pulled                  4s    kubelet                  Successfully pulled image "quay.io/kubevirt/cdi-uploadserver:v1.31.0"
```

And in the few cases, where the test failed the message was:
```
Normal Pulled 1s kubelet Container image "quay.io/kubevirt/cdi-uploadserver:v1.31.0" already present on machine
```

So there was some time spent between the event `Normal SuccessfulAttachVolume` and the event `Pull`.

**Comment by fabiand** [comment] 2021-03-16 10:04
CLosing b/c referencing PR got merged.

**Closed** 2021-03-30 10:46 UTC
Labels: kind/bug, triage/build-watcher
