### ISSUE TITLE
Windows VM cannot ping the default gateway.

### ISSUE THREAD

**Issue by visheshtanksale** [kubevirt/kubevirt#1615] opened 2018-10-13 03:02 UTC
**What happened**:
Created a windows VM using kubevirt windows template. It does not have internet access. It cannot even ping its default gateway. I have a centos vm with same network config on same node which can access internet. 
**What you expected to happen**:
Windows VM to be able to ping its default gateway and access internet
**Anything else we need to know?**:
I am using Weave as CNI
**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.8.0", GitCommit:"6165ead7201d8b96946fdfcfb026e44b86d3d980", GitTreeState:"clean", BuildDate:"2018-09-05T15:38:18Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: &version.Info{GitVersion:"v0.9.1", GitCommit:"93e8226fa15325a0eaea2b693de82824a8b98270", GitTreeState:"clean", BuildDate:"2018-10-05T07:01:51Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"} 
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
```
[root@jb win-image]# k describe vmis testvm-win
Name:         testvm-win
Namespace:    default
Labels:       kubevirt.io/nodeName=rlab-os-sdgx-1
              kubevirt.io/os=win2k12r2
Annotations:  virtualmachinepreset.kubevirt.io/win2k12r2=kubevirt.io/v1alpha2
API Version:  kubevirt.io/v1alpha2
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2018-10-13T02:56:49Z
  Finalizers:
    foregroundDeleteVirtualMachine
  Generate Name:  testvm-win
  Generation:     1
  Owner References:
    API Version:           kubevirt.io/v1alpha2
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  VirtualMachine
    Name:                  testvm-win
    UID:                   9a244c56-ce93-11e8-a130-9886095b9a4f
  Resource Version:        5440422
  Self Link:               /apis/kubevirt.io/v1alpha2/namespaces/default/virtualmachineinstances/testvm-win
  UID:                     a1342c25-ce93-11e8-a63d-988609f66bbb
Spec:
  Domain:
    Clock:
      Timer:
        Hpet:
          Present:  false
        Hyperv:
          Present:  true
        Pit:
          Present:      true
          Tick Policy:  delay
        Rtc:
          Present:      true
          Tick Policy:  catchup
      Utc:
    Cpu:
      Cores:  2
    Devices:
      Disks:
        Disk:
          Bus:        sata
        Name:         rootdisk
        Volume Name:  rootvolume
      Interfaces:
        Bridge:
        Model:  e1000
        Name:   default
    Features:
      Acpi:
        Enabled:  true
      Apic:
        Enabled:  true
      Hyperv:
        Relaxed:
          Enabled:  true
        Spinlocks:
          Enabled:    true
          Spinlocks:  8191
        Vapic:
          Enabled:  true
    Firmware:
      Uuid:  8d86b81d-379f-5973-8358-47e8188339be
    Machine:
      Type:  q35
    Resources:
      Requests:
        Memory:  4Gi
  Networks:
    Name:  default
    Pod:
  Termination Grace Period Seconds:  0
  Volumes:
    Name:  rootvolume
    Persistent Volume Claim:
      Claim Name:  win-claim
Status:
  Interfaces:
    Ip Address:  10.34.0.5
  Node Name:     rlab-os-sdgx-1
  Phase:         Running
Events:
  Type    Reason              Age                            From                          Message
  ----    ------              ----                           ----                          -------
  Normal  SuccessfulCreate    5m                             virtualmachine-controller     Created virtual machine pod virt-launcher-testvm-win-px79l
  Normal  SuccessfulHandOver  4m                             virtualmachine-controller     Pod ownership transferred to the node virt-launcher-testvm-win-px79l
  Normal  Created             <invalid> (x3 over <invalid>)  virt-handler, rlab-os-sdgx-1  VirtualMachineInstance defined.
  Normal  Started             <invalid>                      virt-handler, rlab-os-sdgx-1  VirtualMachineInstance started.
```
- OS (e.g. from /etc/os-release):
Windows Server 2012 r2

**Comment by fabiand** [comment] 2018-10-15 07:42
@duyanyan can you reproduce this issue?

**Comment by karmab** [comment] 2018-10-15 13:38
can you share the yaml definition of your vm with the following command

```
kubectl get vm testvm-win -o yaml
```

i suspect the definition lacks an interface+network section, which seems to be mandatory starting from 0.9.X to get nics in the vm

**Comment by karmab** [comment] 2018-10-15 13:49
possibly related to https://github.com/kubevirt/kubevirt/issues/1618

**Comment by SchSeba** [comment] 2018-10-15 14:06
I think it is related to https://github.com/kubevirt/kubevirt/issues/1620
also I think I fix it here https://github.com/kubevirt/kubevirt/pull/1621

**Comment by duyanyan** [comment] 2018-10-16 03:48
I only have a OCP env with openshift sdn, and I can not reproduce the issue on OCP3.11+kubevirt v0.9.1. Maybe it is related to weave cni.

**Comment by SchSeba** [comment] 2018-10-18 08:19
merged https://github.com/kubevirt/kubevirt/pull/1621

**Closed by SchSeba** 2018-10-18 08:19 UTC
Labels: kind/bug, topic/network
