### ISSUE TITLE
Storage Starting a VirtualMachineInstance [rfe_id:3106][crit:medium][vendor:cnv-qe@redhat.com][level:component]with Alpine PVC should be successfully started with NFS Disk PVC using ipv4 address of the NFS pod not owned by qemu

### ISSUE THREAD

**Issue by nelsonspbr** [kubevirt/kubevirt#4962] opened 2021-02-03 16:39 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/triage build-watcher

**What happened**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev/1356519903128981504

```
vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43
Timed out after 180.000s.
expected phase is Running but got Pending
tests/storage_test.go:93
```

```
09:52:01: • [SLOW TEST:73.350 seconds]
09:52:01: Storage
09:52:01: tests/storage_test.go:66
09:52:01:   Starting a VirtualMachineInstance
09:52:01:   tests/storage_test.go:76
09:52:01:     [rfe_id:3106][crit:medium][vendor:cnv-qe@redhat.com][level:component]with Alpine PVC
09:52:01:     tests/storage_test.go:147
09:52:01:       should be successfully started and stopped multiple times
09:52:01:       vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
09:52:01:         [test_id:3133]with CDRom PVC
09:52:01:         vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43
09:52:01: ------------------------------
09:52:10: W0202 09:49:04.565515   48019 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
09:52:10: W0202 09:49:05.352537   48019 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
09:52:10: W0202 09:49:06.754048   48019 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
09:52:10: 
09:52:10: 
09:52:10: • Failure [186.036 seconds]
09:52:10: Storage
09:52:10: tests/storage_test.go:66
09:52:10:   Starting a VirtualMachineInstance
09:52:10:   tests/storage_test.go:76
09:52:10:     [rfe_id:3106][crit:medium][vendor:cnv-qe@redhat.com][level:component]with Alpine PVC
09:52:10:     tests/storage_test.go:147
09:52:10:       should be successfully
09:52:10:       tests/storage_test.go:149
09:52:10:         started
09:52:10:         vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
09:52:10:           with NFS Disk PVC using ipv4 address of the NFS pod not owned by qemu [It]
09:52:10:           vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43
09:52:10: 
09:52:10:           Timed out after 180.000s.
09:52:10:           expected phase is Running but got Pending
09:52:10: 
09:52:10:           tests/storage_test.go:93
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nelsonspbr** [comment] 2021-02-03 17:27
Also observed here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1356724248772612098

```
23:09:49: • Failure [186.420 seconds]
23:09:49: Storage
23:09:49: tests/storage_test.go:66
23:09:49:   Starting a VirtualMachineInstance
23:09:49:   tests/storage_test.go:76
23:09:49:     [rfe_id:3106][crit:medium][vendor:cnv-qe@redhat.com][level:component]with Alpine PVC
23:09:49:     tests/storage_test.go:147
23:09:49:       should be successfully
23:09:49:       tests/storage_test.go:149
23:09:49:         started
23:09:49:         vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
23:09:49:           with NFS Disk PVC using ipv4 address of the NFS pod not owned by qemu [It]
23:09:49:           vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43
23:09:49: 
23:09:49:           Timed out after 180.001s.
23:09:49:           expected phase is Running but got Pending
23:09:49: 
23:09:49:           tests/storage_test.go:93

...

23:13:12: 
23:13:12: Summarizing 1 Failure:
23:13:12: 
23:13:12: [Fail] Storage Starting a VirtualMachineInstance [rfe_id:3106][crit:medium][vendor:cnv-qe@redhat.com][level:component]with Alpine PVC should be successfully started [It] with NFS Disk PVC using ipv4 address of the NFS pod not owned by qemu 
23:13:12: tests/storage_test.go:93
23:13:12: 
23:13:12: Ran 326 of 739 Specs in 3189.708 seconds
23:13:12: FAIL! -- 325 Passed | 1 Failed | 1 Pending | 412 Skipped
23:13:12: 
23:13:12: 
23:13:12: Ginkgo ran 1 suite in 53m11.950507359s
23:13:12: Test Suite Failed
make: *** [Makefile:74: functest] Error 1
+ make cluster-down
"Timestamp is enabled"
./cluster-up/down.sh
+ EXIT_VALUE=2
+ set +o xtrace
Cleaning up after docker in docker.

```

**Comment by nelsonspbr** [comment] 2021-02-04 05:35
Also being reported at the moment at https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-02-04-024h.html. Failed for:

- pull-kubevirt-e2e-k8s-1.18
    - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4953/pull-kubevirt-e2e-k8s-1.18/1357005226543943681
- pull-kubevirt-e2e-k8s-1.20
    - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4953/pull-kubevirt-e2e-k8s-1.20/1357111425310396416
    - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4953/pull-kubevirt-e2e-k8s-1.20/1357061094014717953
    - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4953/pull-kubevirt-e2e-k8s-1.20/1356962067667488768

**Comment by dhiller** [comment] 2021-02-04 10:07
We have it failing more than half of the time on [kubevirt 1.20 lane](https://prow.apps.ovirt.org/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.20), also often on [kubevirt 1.19](https://prow.apps.ovirt.org/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.19) since a while.

@mhenriks could you take a look why this is happening?

FYI @aglitke

**Comment by davidvossel** [comment] 2021-02-04 22:28
container gets stuck in ContainerCreating

```
                "containerStatuses": [
                    {
                        "name": "nfsserver",
                        "state": {
                            "waiting": {
                                "reason": "ContainerCreating"
                            }
                        },
                        "lastState": {},
                        "ready": false,
                        "restartCount": 0,
                        "image": "registry:5000/kubevirt/nfs-server:devel",
                        "imageID": "",
                        "started": false
                    }
                ],
```


found event that says this

```
            "reason": "FailedMount",
            "message": "MountVolume.SetUp failed for volume \"nfsdata\" : hostPath type check failed: /tmp/hostImages/alpine1-nopriv is not a directory",
            "source": {
                "component": "kubelet",
                "host": "node01"
            },
```

the nfs server is trying to mount a hostPath that doesn't exist now I think... so the question is what happened to that host path.

**Comment by dhiller** [comment] 2021-02-05 14:01
Also observed again here:
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4937/pull-kubevirt-e2e-k8s-1.19/1357310991280377856
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4937/pull-kubevirt-e2e-k8s-1.19/1357249585390555136
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4937/pull-kubevirt-e2e-k8s-1.19/1357188180461228032
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4937/pull-kubevirt-e2e-k8s-1.19/1357050020678864896
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4937/pull-kubevirt-e2e-k8s-1.19/1356988617083326464
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4937/pull-kubevirt-e2e-k8s-1.19/1356911861647282176
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4937/pull-kubevirt-e2e-k8s-1.19/1356850455501606912
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4937/pull-kubevirt-e2e-k8s-1.19/1356753064366706689
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4937/pull-kubevirt-e2e-k8s-1.20/1357372396872404992
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4937/pull-kubevirt-e2e-k8s-1.20/1357188180465422336
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4937/pull-kubevirt-e2e-k8s-1.20/1357126776190406656
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4937/pull-kubevirt-e2e-k8s-1.20/1357050020674670592
*

**Comment by xpivarc** [comment] 2021-02-09 20:46
Again: (caused by single PR #4736 )
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4736/pull-kubevirt-e2e-k8s-1.20/1357571958752940032
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4736/pull-kubevirt-e2e-k8s-1.20/1357433800719601664
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4736/pull-kubevirt-e2e-k8s-1.19/1356957915285557248
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4736/pull-kubevirt-e2e-k8s-1.19/1356896509504786432
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4736/pull-kubevirt-e2e-k8s-1.19/1356834601527414785
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4736/pull-kubevirt-e2e-k8s-1.18/1356435974426464256
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4736/pull-kubevirt-e2e-k8s-1.19/1356957915285557248
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4736/pull-kubevirt-e2e-k8s-1.18/1356512731951271936

**Comment by phoracek** [comment] 2021-02-10 13:42
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4552/pull-kubevirt-e2e-k8s-1.20/1357472429466718208
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4948/pull-kubevirt-e2e-k8s-1.20/1357328236014473216
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4552/pull-kubevirt-e2e-k8s-1.19/1357349497239244800
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4948/pull-kubevirt-e2e-k8s-1.19/1357325966740819968

**Comment by oshoval** [comment] 2021-02-17 09:02
Has in common to https://github.com/kubevirt/kubevirt/issues/4829
Both tests  are skipped with  a comment
```
					// Skipping the following 2 tests until https://github.com/kubevirt/kubevirt/issues/4829 is fixed
					table.PEntry("with NFS Disk PVC using ipv6 address of the NFS pod", tests.NewRandomVMIWithPVC, "nfs", k8sv1.IPv6Protocol, true),
					table.PEntry("with NFS Disk PVC using ipv4 address of the NFS pod not owned by qemu", tests.NewRandomVMIWithPVC, "nfs", k8sv1.IPv4Protocol, false),
```

for nfs ignoreWarnings is true, so even Error events will be ignored
Please consider this fix
https://github.com/kubevirt/kubevirt/pull/5012
so we see the exact Error event in the log and assert on it,
In case desired, also warnings can be enabled, and by using
https://github.com/kubevirt/kubevirt/pull/5002
We can ignore specific warnings that are problematic but accept the rest

I saw on https://github.com/kubevirt/kubevirt/issues/4829 a lot of context deadline exceed, from what i undersand
it comes from the 20 seconds gRPC tunnel between virt-handler and virt-launcher, should we increase the timeout there?

**Comment by jean-edouard** [comment] 2021-02-17 15:48
Opened a PR to re-enable the tests and see what happens: https://github.com/kubevirt/kubevirt/pull/5042
It they still fail, https://github.com/kubevirt/kubevirt/pull/5012 should help debug once merged, thanks!

**Comment by oshoval** [comment] 2021-02-21 10:29
Maybe worth running all this Context as [Serial] first for a while ?

**Closed** 2021-03-07 13:54 UTC
Labels: kind/bug, triage/build-watcher
