### ISSUE TITLE
Cirros VM hangs very long on dhcp discover

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#936] opened 2018-04-23 09:03 UTC
When I boot my cirros VM, it takes some time until it finally gets past the dhcp configuration (up to 30 secons).

Console output: 

```
Starting acpid: OK
mcb [info=/dev/vdb dev=/dev/vdb target=tmp unmount=true callback=mcu_drop_dev_arg]: mount '/dev/vdb' '-o,ro' '/tmp/nocloud.mp.ODGQgF'
mcudda: fn=cp dev=/dev/vdb mp=/tmp/nocloud.mp.ODGQgF : -a /tmp/cirros-ds.INNIox/nocloud/raw
Starting network...
udhcpc (v1.23.2) started
Sending discover...
```

It hangs at the last line very long until it continues. Let's check if we have a general issue, or if it is just cirros related. At the end it always works, but we don't see something on the console for a very long time.

**Comment by rmohr** [comment] 2018-04-23 09:03
@vladikr FYI

**Comment by vladikr** [comment] 2018-04-24 16:41
Thanks, I'll take a look.

**Comment by booxter** [comment] 2018-04-26 14:04
For the record, we are using Cirros in OpenStack gates and I am not aware of an issue like that one there. If there is indeed an issue, it is probably something kubevirt related.

**Comment by rmohr** [comment] 2018-04-26 14:11
@vladikr giving this high priority, since it is currently the number 1 issue on ci for flaky tests.

@davidvossel ^^ FYI

**Comment by vladikr** [comment] 2018-04-27 13:08
@rmohr strange, I ran it several times and I get a response immediately...
I'll try on a different environment.

**Comment by davidvossel** [comment] 2018-04-27 13:14
@rmohr where were you able to reproduce this? Was this on CI or your local machine?

@vladikr Looking at the code, since the DHCP server starts in a goroutine in parallel to the VM starting there's technically a race condition there where the VM could start before DHCP was listening in virt-launcher... that seems really unlikely though.

**Comment by vladikr** [comment] 2018-05-01 13:51
@rmohr @davidvossel I think I've managed to reproduce the issue, only on openshift though.
However, I see that both the test VMs got an ip from dhcp:

```
udhcpc (v1.23.2) started\r\nSending discover...\r\nSending select for 10.129.0.8...\r\n [Sending discover...]} {1 Lease of 10.129.0.8 obtained, lease time 86313600\r [Lease of 10.129.0.8 obtained, lease time 86313600]}]"
```
And 
```
Sending discover...\r\nSending select for 10.129.0.7...\r\nL [Sending discover...]} {1 ease of 10.129.0.7 obtained, lease time 86313600\r\n
```
Looks like the outbound vm crashes after the login:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xf06cc2]

goroutine 199 [running]:
kubevirt.io/kubevirt/tests.NewConsoleExpecter.func1(0x12e0e60, 0xc42027c0c0, 0x0, 0xc42000eea8, 0xc42000eec0, 0xc4206d0d80)
	/root/go/src/kubevirt.io/kubevirt/tests/utils.go:957 +0x32
created by kubevirt.io/kubevirt/tests.NewConsoleExpecter
	/root/go/src/kubevirt.io/kubevirt/tests/utils.go:956 +0x329
```

Roman, is it similar to what you've been seeing?

**Comment by rmohr** [comment] 2018-05-02 07:28
> Looks like the outbound vm crashes after the login:

That looks like a null nil pointer exception in our golang testing code and not really related to the vm.

> Roman, is it similar to what you've been seeing?

No, booting the vm always works and nothing crashes. It just sometimes hangs for a **very** long time until it reached the boot prompt.

**Comment by booxter** [comment] 2018-05-02 19:31
This issue and the comment by David above reminded me of a very old OpenStack Neutron bug where DHCP agent was not quick enough to start dnsmasq to serve VM lease before Nova started it and Cirros (or whatever is in the image) starts networking configuration.

The OpenStack bug is https://bugs.launchpad.net/neutron/+bug/1453350 ; the fix is https://review.openstack.org/#/c/181674/

The general idea of the fix is to not update port status to ACTIVE until all entities (L2 agent, DHCP agent...) confirm completion of their part of the job. Only when all entities report back, we bump port status to ACTIVE which triggers a notification message back to Nova Compute service to unpause the VM and proceed with its boot.

We may need a similar mechanism in kubevirt.

**Comment by rmohr** [comment] 2018-05-02 19:47
@booxter great that you were able to reproduce it. I think that the solution may be much simpler, than to do something that complex, like pausing the vm (but let's see ...). First we are not using dnsmasq, we just have a go-routine which understands dhcp-requests and can respond. That should be extremely fast. If there is no bug in the dhcp code (causing slow start, not understanding a valid dhcp frame, ...), using a waiting-group to wait with booting qemu until dhcp is ready, should be sufficient.

Looking forward to see what finally caused the issue and what will solve it.

**Comment by davidvossel** [comment] 2018-05-02 19:50
> using a waiting-group to wait with booting qemu until dhcp is ready, should be sufficient.

We just need to avoid marking the pod as ready until we're certain dhcp is both listening and accepting connections. 

Essentially by delaying the execution of cmd/virt-launcher/virt-launcher.go's markReady() function, we delay the possibility of the VM being started in the pod.

**Comment by rmohr** [comment] 2018-05-02 19:57
@davidvossel yes, if we move the dhcp-server start out from the preStart hook and start it right away (which makes more sense anyway). I guess that we will not even see the issue then, no matter if we delay the marking or not. Sounds good in general.

**Comment by davidvossel** [comment] 2018-05-02 20:03
oh wow, I actually forgot we started dhcp server during sync command. That makes this race condition much more likely than I originally though.

**Comment by vladikr** [comment] 2018-05-02 20:07
> if we move the dhcp-server start out from the preStart hook
I don't see how will it work.
We discover the pod ip and routes during the preStart hook.
What am I missing?

**Comment by rmohr** [comment] 2018-05-02 20:11
> We discover the pod ip and routes during the preStart hook.
> What am I missing?

The whole network setup can be done immediately. No need to wait for the preStart hook, which is invoked much later, when virt-handler tells virt-launcher to start the vm.

**Comment by booxter** [comment] 2018-05-02 21:07
Some updates from my environment.

First, I don't believe it's an issue with late DHCP server goroutine startup. In docker log for virt-launcher container I see that the server was started long before the VM is spawned (there is a "Starting SingleClientDHCPServer").

I believe the issue is because the spawned server doesn't receive a DHCP request frame when Cirros issues the first discover message. Only when the second message is logged by Cirros, virt-launcher container, and DHCP goroutine, receive the request. (I confirmed it twice, by enabling debug messages and looking for "The request has message type DISCOVER" message in container log; as well as by running tcpdump inside the container and (not) observing BOOTP messages until 1 minute later from the first "Starting discover..." log message.)

I also tried to boot a Fedora image, and it booted just fine; tcpdump shows that BOOTP messages are received almost immediately when network.target is started inside the VM; the lease is immediately served, and in a second I get to getty.

Note it doesn't necessarily mean the issue is with Cirros. There is some space for a time sensitive race condition that could be triggered for Cirros only because it e.g. boots slightly quicker.

**Comment by davidvossel** [comment] 2018-05-02 21:37
> First, I don't believe it's an issue with late DHCP server goroutine startup. In docker log for virt-launcher container I see that the server was started long before the VM is spawned (there is a "Starting SingleClientDHCPServer").

This isn't a guarantee that the DHCP server is accepting requests yet. 

I think we should make issuing and receiving a response from the DHCP server a condition that has to be met before the pod is marked as ready. If we do that, then we at least know the DHCP server is capable of receiving requests before the VM starts.

If the problem persists after that, then I'm really not sure what else can be done from our end.

**Comment by booxter** [comment] 2018-05-02 21:47
@davidvossel while I can't rule out there is an issue with DHCP goroutine, it won't work regardless if we don't even receive DHCP frames into the pod. There must be an issue in VM connectivity to the pod bridge.

One potential lead that @vladikr found is https://bugzilla.redhat.com/show_bug.cgi?id=1411025#c2 that suggests there is expected wait time for libvirt bridges when no traffic from VM is allowed in. The comment suggests that the delay is 2 seconds by default but I see forward delay in brctl showstp for br1 set to 15.0 (seconds?) that would explain why the frame doesn't reach the pod.

**Comment by booxter** [comment] 2018-05-03 18:59
An alternative to customizing interface model type via API would be labeling / tagging images with metadata that would specify hardware requirements. Then kubevirt would consume the metadata to make decisions on which model type to choose. (This is how OpenStack Nova does it: Glance images carry hw_vif_model tags that then Nova Compute consumes.)

**Comment by davidvossel** [comment] 2018-05-03 19:03
excellent work on tracking this down!

> An alternative to customizing interface model type via API would be labeling / tagging images with metadata that would specify hardware requirements.

I think we're going to have to add VIF info into the VM's domainSpec. This is going to take some discussion

@rmohr did you have any thoughts on now we should represent network devices in the KubeVirt API?

**Comment by booxter** [comment] 2018-05-03 19:17
For the record, I reported a bug for Cirros suggesting they should wait for interface link ready before starting udhcpc: https://bugs.launchpad.net/cirros/+bug/1768955

**Comment by rmohr** [comment] 2018-05-04 11:58
> @rmohr did you have any thoughts on now we should represent network devices in the KubeVirt API?

I am in conflict. On the one hand for a huge amount of "legazy" workloads inside VMs, the pod network is exactly what they will need. For more specific use-cases like VNF, ... it is definitely not good enough. I would love the give the pod network interface a place on the API which underlines its very special role and not just make it an entry in "anonymous" list of interfaces. On the other hand I want to keep the interfaces unified.

For now, for the sake of stabilising the tests, I would even be fine to just add an annotation like `alpha.kubevirt.io/network.device: virtio`, or something similar, just to buy us some time for a reasonable debate.

**Comment by fabiand** [comment] 2018-05-06 14:56
Just for reference, we are working on a doc to outline our proposal of how to represent multiple nics in the kubevirt API.

At the same time work with upstream kubernetes on (3) proposal of how K8s can be thought to support multiple networks (and other things).

**Comment by booxter** [comment] 2018-05-10 20:46
Asked in libvirt-users@ about link establishment slowdown for e1000 in case someone has insight into the issue: https://www.redhat.com/archives/libvirt-users/2018-May/msg00065.html

**Comment by booxter** [comment] 2018-05-10 21:47
A user suggested in libvirt-users@ thread that we could explore other model types for our interface defaults, for example, rtl8139. I tried it, and indeed it is not affected by the delay either. That being said, I am told the rtl driver is slower / not well supported. On the bright side, it should work for both Linux and Windows guests.

**Comment by booxter** [comment] 2018-05-11 18:35
I also reported a bug against qemu for the slow e1000 initialization: https://bugs.launchpad.net/qemu/+bug/1770724

**Comment by davidvossel** [comment] 2018-05-14 15:52
the e1000e device is causing problems with the test suite apparently.

A solution that came up in the community meeting is for us to create a value in the VM Spec's feature section to define the pod network driver. This avoids us having to define network interfaces in the api for now, and lets us give users the ability to define what drive to use just for the pod network. I think this is something we can support long term possibly. 

Example

```
metadata:
  creationTimestamp: null
  name: vm-windows
spec:
  domain:
    clock:
      timer:
        hpet:
          present: false
        hyperv: {}
        pit:
          tickPolicy: delay
        rtc:
          tickPolicy: catchup
      utc: {}
    cpu:
      cores: 2
    devices:
      disks:
      - disk:
          bus: sata
        name: pvcdisk
        volumeName: pvcvolume
    features:
      podNetworkDriver: virtio
      acpi: {}
      apic: {}
      hyperv:
        relaxed: {}
        spinlocks:
          spinlocks: 8191
        vapic: {}
    firmware:
      uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
    machine:
      type: ""
    resources:
      requests:
        memory: 2Gi
  terminationGracePeriodSeconds: 0
  volumes:
  - name: pvcvolume
    persistentVolumeClaim:
      claimName: disk-windows
status: {}

```

**Comment by vladikr** [comment] 2018-05-14 16:39
My take on this is that we simply need to increase the tests timeout, to make tests more resilient, instead of introducing a new feature.
We are still going to implement a new API to represent network interfaces in order to support various connections methods to the pod network (bridge or proxy) and connecting various devices using device plugins. 
As @fabiand  mentioner earlier, we are currently drafting a document and submit a proposal that would include all of the above as well as allowing the users to set a nic model.

The implentation of a proxy connection to the pod networking is being worked on in #787  

From point of view it's better to give a bit more time and increase the timeout for now.

**Comment by booxter** [comment] 2018-05-16 21:57
I've made a bunch of tests with cirros and alpine images, and it seems like we have no single good option. To list:

* e1000 works for both but results in test timeouts;
* (despite what I was saying before) e1000e works for neither of 'simple' images (guest drivers are not included; not sure how I missed that, probably libvirt side changes were not applied when I was testing it before;
* rtl* makes console hang up;
* virtio is not supported by Windows machines.

Overall, it looks like the list of kernel modules included in cirros / alpine is very limited.

There is no "easy" solution here.

We can either revive https://github.com/kubevirt/kubevirt/pull/990 to use virtio for cirros; or have a spin on the PR like using virtio by default but change the model to e1000 for win* matches.

Or we can complete API design for advanced networking to include ability to choose a driver, and then modify example templates for cirros / windows accordingly: https://github.com/kubevirt/kubevirt/issues/718 (which is probably a piece of a more general https://github.com/kubevirt/kubevirt/pull/787)

**Comment by itamarh** [comment] 2018-05-17 02:46
@booxter just to clrify - virtio should be supported by Windows, just required installing the drivers (not saying it solves our problem, just to make sure).

**Comment by fabiand** [comment] 2018-05-23 12:03
A nice fix - based around presets and the correct annotations - depends on https://github.com/kubevirt/kubevirt/issues/1067

**Closed** 2018-05-25 07:07 UTC
Labels: help wanted, kind/bug, priority/backlog, priority/critical-urgent, topic/network
