### ISSUE TITLE
v0.39.1 virt-operator ErrImagePull 

### ISSUE THREAD

**Issue by ansijain** [kubevirt/kubevirt#5355] opened 2021-03-31 10:30 UTC
Deployment failing
I tried installing kubevirt on minikube using quickstart guide https://kubevirt.io/quickstart_minikube/ 
there was an error in image pull of virt -operator
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

**What you expected to happen**:
Deployment of kubevirt should be successful

**How to reproduce it (as minimally and precisely as possible)**:
minikube addons enable kubevirt
kubevirt version:- v0.39.1

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.39.1
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  20m                 default-scheduler  Successfully assigned kubevirt/virt-operator-6d5988c4bf-fk7j5 to minikube
  Normal   Pulling    18m (x4 over 20m)   kubelet, minikube  Pulling image "quay.io/kubevirt/virt-operator@sha256:2429917d5fa837c5b3f7a8ebcc4df6f9574d3bbab8f9d47c45d1a71d150e0c7f"
  Warning  Failed     18m (x4 over 20m)   kubelet, minikube  Failed to pull image "quay.io/kubevirt/virt-operator@sha256:2429917d5fa837c5b3f7a8ebcc4df6f9574d3bbab8f9d47c45d1a71d150e0c7f": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/kubevirt/virt-operator@sha256:2429917d5fa837c5b3f7a8ebcc4df6f9574d3bbab8f9d47c45d1a71d150e0c7f not found: manifest unknown: manifest unknown
  Warning  Failed     18m (x4 over 20m)   kubelet, minikube  Error: ErrImagePull
  Warning  Failed     18m (x7 over 20m)   kubelet, minikube  Error: ImagePullBackOff
  Normal   BackOff    25s (x83 over 20m)  kubelet, minikube  Back-off pulling image "quay.io/kubevirt/virt-operator@sha256:2429917d5fa837c5b3f7a8ebcc4df6f9574d3bbab8f9d47c45d1a71d150e0c7f"

**Comment by phoracek** [comment] 2021-03-31 14:41
Thanks for reporting this. I believe it is a duplicate of https://github.com/kubevirt/kubevirt/issues/5352

**Closed by phoracek** 2021-03-31 14:41 UTC
Labels: kind/bug, triage/accepted
