### ISSUE TITLE
[Flaky CI] Configurations  VirtualMachineInstance definition  [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]with  diverging guest memory from requested memory [test_id:1669]should show  the requested guest memory inside the VMI 

### ISSUE THREAD

**Issue by tomob** [kubevirt/kubevirt#4210] opened 2020-09-18 15:10 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-watcher

**What happened**:

CI Test failed with libvirt error: 

```
Configurations  VirtualMachineInstance definition  [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]with  diverging guest memory from requested memory [test_id:1669]should show  the requested guest memory inside the VMI 

/root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:497 Unexpected Warning event received: testvmi8m4zxscrzmf7glxjk8m5vvgkjhpgglzrs9vqrvf9sv5b4vx7,4b791c49-3b37-4f52-bb3d-63402fe0b009: server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: Failed to start QEMU binary /usr/libexec/qemu-kvm for probing: ')" Expected     <string>: Warning not to equal     <string>: Warning /root/go/src/kubevirt.io/kubevirt/tests/utils.go:357
```

Prow link: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4035/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1305961095365660673

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Test lane: pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6

**Comment by rmohr** [comment] 2020-09-18 15:41
/close

Thanks for reporting. Duplicate of #3872. Sadly an infra issue which we so far can only make happen less often and could not identify the root cause.

**Closed** 2020-09-18 15:41 UTC
Labels: kind/bug, triage/build-watcher
