### ISSUE TITLE
VM Migrations fail on clusters with cri-o version v1.28 

### ISSUE THREAD

**Issue by brianmcarey** [kubevirt/kubevirt#10616] opened 2023-10-23 16:40 UTC
**What happened**:

The latest 1.28 release of cri-o has broken the migration conformance tests. This was encountered when trying to update the version of cri-o in kubevirtci[1]

It looks like we depend on the Image ID including the image digest[2] when creating the migration template which is no longer the case due to changes with how cri-o handles the image ID [3].

`{"component":"virt-controller","level":"info","msg":"reenqueuing Migration kubevirt-test-default1/test-migration-xpb7q","pos":"migration.go:233","reason":"failed to render launch manifest: can not proceed with the migration when no reproducible image digest can be detected: failed to identify image digest for container \"registry:5000/kubevirt/alpine-with-test-tooling-container-disk:devel\" with id \"8aba57ea67e3518f3b7fcbf32954bd2c0bd60d46ed55672a0fcec66076d4a6d4\"","timestamp":"2023-10-23T15:22:33.398815Z"}`

```
[root@node02 vagrant]# crictl images -o yaml registry:5000/kubevirt/alpine-with-test-tooling-container-disk:devel
images:
- id: 8aba57ea67e3518f3b7fcbf32954bd2c0bd60d46ed55672a0fcec66076d4a6d4
  pinned: false
  repoDigests:
  - registry:5000/kubevirt/alpine-with-test-tooling-container-disk@sha256:6f11f0558a09ae3d3cb88935d88d00f9f8e32f2396f251efc4a88d41bb0204ba
  repoTags:
  - registry:5000/kubevirt/alpine-with-test-tooling-container-disk:devel
  size: "160773933"
  spec: null
  uid: null
  username: ""
```

I ran the sig-compute-migrations suite against the newly published provider and this results in the majority of tests failing.

[1] https://github.com/kubevirt/kubevirtci/pull/1078
[2] https://github.com/kubevirt/kubevirt/blob/40b219b37714475a998c2cfd6129b9635400502a/pkg/container-disk/container-disk.go#L443
[3] https://github.com/cri-o/cri-o/pull/7149

**What you expected to happen**:
Migration to succeed

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to migrate a containerdisk based VM with crio v1.28 as the container runtime

**Additional context**:
Failed check-provision logs: 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/1078/check-provision-k8s-1.28/1716431053721178112

**Environment**:
- KubeVirt version (use `virtctl version`): Latest main (ae1014b26f9c49c373891903e83c6cc07d31e3b8)
- Kubernetes version (use `kubectl version`): v1.28.3
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: kubevirtci
- OS (e.g. from /etc/os-release): CentOS Stream 9
- Kernel (e.g. `uname -a`): 5.14.0-372.el9.x86_64
- Install tools: N/A
- Others: crio v1.28.1

**Comment by tiraboschi** [comment] 2023-10-30 17:13
Please notice that after https://github.com/cri-o/cri-o/pull/7393 `imageID` is now what was used to be `imageRef` and so we cannot directly extract the image digest (as we intend it) from it.

**Comment by tiraboschi** [comment] 2023-11-03 18:29
This is not a trivial fix like fixing a regexp to correctly match the imageID,
The point is that we using the imageID to build a reproducible pull URL for the target pod while imageID is something else.

In 
```bash
$ podman image inspect [quay.io/kubevirt/cirros-container-disk-demo:v1.0.0](http://quay.io/kubevirt/cirros-container-disk-demo:v1.0.0)
[
     {
          "Id": "fa539d77b76423c6fd37f244a2d32dfda613d503f07f1bde784cc1c733e32cc1",
          "Digest": "sha256:b3173a795eddc0c8f6923bb197928b7c0876aade4daf85d0558dfae65f403fe2",
          "RepoTags": [
               "[quay.io/kubevirt/cirros-container-disk-demo:v1.0.0](http://quay.io/kubevirt/cirros-container-disk-demo:v1.0.0)"
          ],
          "RepoDigests": [
               "[quay.io/kubevirt/cirros-container-disk-demo@sha256:9d36bdd2b8f86e37058a58be47f82c9e94e2741df8fc8144cecf80fd953c8643](http://quay.io/kubevirt/cirros-container-disk-demo@sha256:9d36bdd2b8f86e37058a58be47f82c9e94e2741df8fc8144cecf80fd953c8643)",
               "[quay.io/kubevirt/cirros-container-disk-demo@sha256:b3173a795eddc0c8f6923bb197928b7c0876aade4daf85d0558dfae65f403fe2](http://quay.io/kubevirt/cirros-container-disk-demo@sha256:b3173a795eddc0c8f6923bb197928b7c0876aade4daf85d0558dfae65f403fe2)"
          ],
          "Parent": "",
          "Comment": "",
          "Created": "1970-01-01T00:00:00Z",
          "Config": {},
          "Version": "",
          "Author": "Bazel",
          "Architecture": "amd64",
          "Os": "linux",
          "Size": 16314013,
          "VirtualSize": 16314013,
          "GraphDriver": {
               "Name": "overlay",
               "Data": {
                    "UpperDir": "/var/lib/containers/storage/overlay/a2d9f9e79a166d5ab4567ec230e72ce1879be9787ed59b252f687684560ab13e/diff",
                    "WorkDir": "/var/lib/containers/storage/overlay/a2d9f9e79a166d5ab4567ec230e72ce1879be9787ed59b252f687684560ab13e/work"
               }
          },
          "RootFS": {
               "Type": "layers",
               "Layers": [
                    "sha256:a2d9f9e79a166d5ab4567ec230e72ce1879be9787ed59b252f687684560ab13e"
               ]
          },
          "Labels": null,
          "Annotations": {},
          "ManifestType": "application/vnd.docker.distribution.manifest.v2+json",
          "User": "",
          "History": [
               {
                    "created": "1970-01-01T00:00:00Z",
                    "created_by": "bazel build ...",
                    "author": "Bazel"
               }
          ],
          "NamesHistory": [
               "[quay.io/kubevirt/cirros-container-disk-demo:v1.0.0](http://quay.io/kubevirt/cirros-container-disk-demo:v1.0.0)"
          ]
     }
]
```

for instance the repo digest are `9d36bdd2b8f86e37058a58be47f82c9e94e2741df8fc8144cecf80fd953c8643` and `b3173a795eddc0c8f6923bb197928b7c0876aade4daf85d0558dfae65f403fe2` while the `imageID` is 
`fa539d77b76423c6fd37f244a2d32dfda613d503f07f1bde784cc1c733e32cc1`.

and now CRI-O v1.28 (and so OKD v4.14) started correctly reporting `fa539d77b76423c6fd37f244a2d32dfda613d503f07f1bde784cc1c733e32cc1` as the `imageID`
but we use it to render something like:
`quay.io/kubevirt/cirros-container-disk-demo@sha256:fa539d77b76423c6fd37f244a2d32dfda613d503f07f1bde784cc1c733e32cc1` that is not pullable for the target pod while only `quay.io/kubevirt/cirros-container-disk-demo@sha256:9d36bdd2b8f86e37058a58be47f82c9e94e2741df8fc8144cecf80fd953c8643` and               `quay.io/kubevirt/cirros-container-disk-demo@sha256:b3173a795eddc0c8f6923bb197928b7c0876aade4daf85d0558dfae65f403fe2` are.

see: https://github.com/kubernetes/kubernetes/pull/121531

**Comment by tiraboschi** [comment] 2023-11-03 18:30
Removing myself as the assignee since it's by far more sensitive than what I was expecting.

**Comment by akalenyu** [comment] 2023-11-06 23:43
https://github.com/kubevirt/kubevirt/pull/6535 Gives some good context around why we needed this to begin with.
Is it possible that this cri-o change is breaking compatibility by not having this info available anymore?

**Comment by acardace** [comment] 2023-11-08 15:09
I've assigned this to myself as I'm implementing a fix for this and will be posting a PR soon.

**Closed** 2023-12-12 18:11 UTC
Labels: kind/bug
