### ISSUE TITLE
The execution process is interrupted inside the container, but there is ok when self-installing bazel is executed outside the container

### ISSUE THREAD

**Issue by Kate-DONG** [kubevirt/kubevirt#5994] opened 2021-07-08 01:45 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:BUG REPORT

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:The execution process is interrupted inside the container, but there is ok when self-installing bazel is executed outside the container.

**What you expected to happen**: We want to the execution process is ok inside the container.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: 

**Environment**:
- KubeVirt version (use `virtctl version`): v0.42.1
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment] 2021-07-08 07:28
@Kate-DONG could you explain in a little bit more detail what issue you are seeing? Since it seems to be related to running bazel, could you maybe share the commands you run together with the issue you are seeing?

**Comment by rmohr** [comment] 2021-07-08 07:29
/close

Closing this as duplicate of #5995 where there is also more info. Thanks.

**Closed by rmohr** 2021-07-08 07:29 UTC
