### ISSUE TITLE
[Flaky CI][Serial]Storage Starting a VirtualMachineInstance [rfe_id:2298][crit:medium][vendor:cnv-qe@redhat.com][level:component] With HostDisk and PVC initialization With a HostDisk defined With 'DiskExistsOrCreate' type Should create a disk image and start [test_id:851]with virtio driver 

### ISSUE THREAD

**Issue by qinqon** [kubevirt/kubevirt#4331] opened 2020-10-07 10:10 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-officer
> /kind enhancement

**What happened**:
Following test is flaky
`[Serial]Storage Starting a VirtualMachineInstance [rfe_id:2298][crit:medium][vendor:cnv-qe@redhat.com][level:component] With HostDisk and PVC initialization With a HostDisk defined With 'DiskExistsOrCreate' type Should create a disk image and start [test_id:851]with virtio driver `

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4287/pull-kubevirt-e2e-k8s-1.18/1313621572384198656

```

1/637 Tests Failed. | expand_less
-- | --
[Serial]Storage Starting a VirtualMachineInstance [rfe_id:2298][crit:medium][vendor:cnv-qe@redhat.com][level:component] With HostDisk and PVC initialization With a HostDisk defined With 'DiskExistsOrCreate' type Should create a disk image and start [test_id:851]with virtio driver expand_less1m22svendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43 Unexpected Warning event received: testvmiq6xf6hgftf5x9bqz9256nhp24skv5x5jkhpzxndk7j5cjj69,1cbc8ab2-9c0f-412d-9673-df72560f07d1: server error. command SyncVMI failed: "LibvirtError(Code=38, Domain=0, Message='Unable to open /dev/kvm: Operation not permitted')" Expected     <string>: Warning not to equal     <string>: Warning tests/utils.go:361 | [Serial]Storage Starting a VirtualMachineInstance [rfe_id:2298][crit:medium][vendor:cnv-qe@redhat.com][level:component] With HostDisk and PVC initialization With a HostDisk defined With 'DiskExistsOrCreate' type Should create a disk image and start [test_id:851]with virtio driver expand_less | 1m22s | vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43 Unexpected Warning event received: testvmiq6xf6hgftf5x9bqz9256nhp24skv5x5jkhpzxndk7j5cjj69,1cbc8ab2-9c0f-412d-9673-df72560f07d1: server error. command SyncVMI failed: "LibvirtError(Code=38, Domain=0, Message='Unable to open /dev/kvm: Operation not permitted')" Expected     <string>: Warning not to equal     <string>: Warning tests/utils.go:361
[Serial]Storage Starting a VirtualMachineInstance [rfe_id:2298][crit:medium][vendor:cnv-qe@redhat.com][level:component] With HostDisk and PVC initialization With a HostDisk defined With 'DiskExistsOrCreate' type Should create a disk image and start [test_id:851]with virtio driver expand_less | 1m22s
vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43 Unexpected Warning event received: testvmiq6xf6hgftf5x9bqz9256nhp24skv5x5jkhpzxndk7j5cjj69,1cbc8ab2-9c0f-412d-9673-df72560f07d1: server error. command SyncVMI failed: "LibvirtError(Code=38, Domain=0, Message='Unable to open /dev/kvm: Operation not permitted')" Expected     <string>: Warning not to equal     <string>: Warning tests/utils.go:361


```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment] 2020-10-22 15:17
@qinqon thanks for reporting. Duplicate of #3872

/close

**Closed by rmohr** 2020-10-22 15:17 UTC
Labels: kind/bug, triage/build-watcher
